### ISSUE TITLE
Do something about mentions

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#109]
The web client highlights channels in a special way when you've been @-mentioned. There's also the server-side configuration of mentions that we don't support.

**Comment by aisamanra** [comment]
I should update this to note that we've done _something_ about mentions: namely, we highlight channels with mentions differently. A few tasks I want to do before we close this:

- [ ] Fetch the number of mentions (on a scale of 1–9+) and display that
- [ ] Decide on a final presentation, including whether to highlight them with a different color or not

**Comment by jtdaugherty** [comment]
See also #261.

**Comment by jtdaugherty** [comment]
This is now done as far as this ticket goes, and we can close and continue work on #261.
