### ISSUE TITLE
Fetch emoji list from server

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#113]
Fetching the server's emoji list would allow:
- displaying the actual emoji (later, when brick/vty support multi-column characters)
- tab-completing the `:...:` form of emoji (important for users who don't know what the choices are but want to be sure the other users see the right thing)

**Comment by jtdaugherty** [comment]
It turns out that:
* You can only fetch the *custom* emoji list (I had hoped we could fetch all known emoji)
* Once fetched, the emoji list contains IDs that can be used to fetch imoji *images* (I had hoped that emoji were unicode characters, but they are images instead)

So this reduces the potential benefit; all we can really do is fetch the custom names and add them to the tab completion set, but we can't display them.

**Comment by dagit** [comment]
Bummer. Thanks for looking into it.

**Comment by jtdaugherty** [comment]
I also did some work on https://github.com/aisamanra/matterhorn/issues/125 and left a comment there that is relevant to this, too.

**Comment by jtdaugherty** [comment]
@dmwit mentioned this useful mapping of emoji names to Unicode characters: https://github.com/muan/emojilib/blob/master/emojis.json

**Comment by jtdaugherty** [comment]
Closing. For context, see #125.
