### ISSUE TITLE
sendbuf: resource vanished (Broken pipe)

### ISSUE THREAD

**Issue by leepike** [matterhorn-chat/matterhorn#116]
I received a 

```
[00:11] An unexpected error has occurred! The exception encountered was:
             sendBuf: resource vanished (Broken pipe)
             Please report this error at https://github.com/aisamanra/matterhorn/issues
```

error. I was on commit c07f82f2.

**Comment by jtdaugherty** [comment]
The code path for this is:
* Queue an async action
* Async thread runs queued action with `try`, exception is raised and converted to `Left`
* Exception is posted to the event loop with `AsyncErrEvent` and rendered as above

**Comment by jtdaugherty** [comment]
It is almost certainly safe to ignore this message: if the connection has gone down then the websocket monitoring will also notice. However, this particular exception (`resource vanished`) is probably specific enough that we could look for it and post a *different* error message like `Failed to <do whatever>; connection closed.` or something.

**Comment by aisamanra** [comment]
The long-term idea is that the `An unexpected error has occurred!` message should go away as much as possible: it's currently a catch-all in case we didn't anticipate something. Maybe we should cache the async computation we were trying to do and try to redo it after we connect successfully?

**Comment by jtdaugherty** [comment]
I'm concerned that async caching will lead to duplicate effects for computations that do more than one thing (i.e. they aren't transactional, so a failure doesn't mean we couldn't do anything, it just means we couldn't do something). In this case, couldn't we catch resource-vanished exceptions in particular? I think that one may be the one we can expect most often due to connection issues.

**Comment by jtdaugherty** [comment]
CC @tommd

**Comment by jtdaugherty** [comment]
Unfortunately "resource vanished" exceptions are not exposed in the exception API:
* No predicate for such exceptions exists: https://hackage.haskell.org/package/base-4.9.0.0/docs/System-IO-Error.html#g:5
* The constructor `ResourceVanished` is in a "GHC only" section and is not exported: https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.IO.Exception.html#IOErrorType

**Comment by dagit** [comment]
Oh that's really unfortunate. There must be something we can do, but I never realized it's not exposed with the rest of the exceptions.

**Comment by jtdaugherty** [comment]
Since this is not specifically catchable and occurs rarely, I'm going to close it. If it happens again and someone reports it, at that point I think it would be worth a hack based on the exception text.

**Comment by dagit** [comment]
I just got this again. I'm not sure how I got it, but once it happened, my client was stuck with `[Refreshing channel...]`.

**Comment by jtdaugherty** [comment]
We now address this cosmetically in https://github.com/matterhorn-chat/matterhorn/commit/e51129076ed11c88645ab5f5cc09cb0b7b0d4211 but there is still the issue of lingering state, e.g., the "Refreshing channel..." stuck state that @dagit mentioned. Fixing that is covered by https://github.com/matterhorn-chat/matterhorn/issues/255.

**Comment by andrewthad** [comment]
In `base-4.14.0.0`, `System.IO.Error` will export `isResourceVanishedError`, which will be a less hacky way to detect this exception.

**Comment by jtdaugherty** [comment]
Great, thanks @andrewthad!
