### ISSUE TITLE
Update for MatterMost 3.5

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#117]
Breaking API changes are listed at

https://github.com/mattermost/docs/blob/4688e3e3593e90a79f2951527f7628a5ef419782/source/administration/changelog.md#api-changes-from-v34-to-v35

CC @dwest-galois @dagit @aisamanra

**Comment by jtdaugherty** [comment]
@dwest-galois has agreed to set up a testing 3.5 instance for us and we'll have some time to test before it goes live. When that happens I'd like to set up a `mattermost-3.5` branch to do the upgrade work and then merge once everyone will need to run it.

**Comment by aisamanra** [comment]
Do we want to have some way of supporting multiple server versions? I don't know exactly what that would look like, or whether it would be worthwhile to do at this point when MM is still in pretty active breaking development (but will it ever not be?)

**Comment by jtdaugherty** [comment]
I'm not excited about doing the work to support multiple versions (and having strong typing often makes this hard to do nicely). However, as a stop-gap we can do better about making it clear when we modify Matterhorn and its API package to support new versions, and we can make the client tell you what version it is intended to work with (e.g. `matterhorn --version`).

**Comment by jtdaugherty** [comment]
I'm closing this since we've been running on 3.5 for some time now.
