### ISSUE TITLE
Create a script to produce a bindist

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#124]
Some users will need to install binaries rather than build from source. Creating binary releases should be really easy to script. I'm happy to take this on.

**Comment by jtdaugherty** [comment]
CC @chrisfatgalois

**Comment by jtdaugherty** [comment]
This is now underway as of ae802fe527b3dd72f04216b09d393f195b17deab. It will make a bindist for the current platform/version/git HEAD. More needs to be done to interact with tagging, etc., but this is a useful start (so I'm leaving this ticket open).

**Comment by glguy** [comment]
When doing binary releases it's necessary (for licenses like BSD3) to retain the copyright notice and license terms of your dependencies.

```
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
```

This isn't an issue for normal *sdist* packaging because the dependencies aren't being bundled in. 

For help getting started in tracking down all this information you might take a look at the Setup.hs from *Galua* : https://github.com/GaloisInc/galua/blob/master/galua/Setup.hs

**Comment by jtdaugherty** [comment]
@glguy I tried the `Setup.hs` from `galua` with `matterhorn`, but it didn't generate any of the `HS_*` files. What's the expected workflow and behavior for this?

**Comment by glguy** [comment]
In galua after the *configure* stage you'll get `HS_COPYRIGHTS` `HS_LIBRARIES_LIST` and `HS_LIBRARY_PATHS_LIST`

For example:

```
$ cat ./galua/dist/build/autogen/HS_COPYRIGHTS
process-1.4.2.0 - BSD3 -  - 
numeric-extras-0.1 - BSD3 -  - Edward Kmett
lua-bc-0.1.0.1 - MIT - 2015 Galois, Inc. - Eric Mertens
pretty-1.1.3.3 - BSD3 -  - 
language-lua-0.9.0 - BSD3 -  - mer Sinan Aacan, Eric Mertens
hashtables-1.2.1.0 - BSD3 - (c) 2011-2014, Google, Inc. - Gregory Collins
vector-0.11.0.0 - BSD3 - (c) Roman Leshchinskiy 2008-2012 - Roman Leshchinskiy <rl@cse.unsw.edu.au>
primitive-0.6.1.0 - BSD3 - (c) Roman Leshchinskiy 2009-2012 - Roman Leshchinskiy <rl@cse.unsw.edu.au>
transformers-0.5.2.0 - BSD3 -  - Andy Gill, Ross Paterson
hashable-1.2.4.0 - BSD3 -  - Milan Straka <fox@ucw.cz>
Johan Tibell <johan.tibell@gmail.com>
text-1.2.2.1 - BSD3 - 2009-2011 Bryan O'Sullivan, 2008-2009 Tom Harper - Bryan O'Sullivan <bos@serpentine.com>
directory-1.2.6.2 - BSD3 -  - 
unix-2.7.2.0 - BSD3 -  - 
time-1.6.0.1 - BSD3 -  - Ashley Yakeley
filepath-1.4.1.0 - BSD3 - Neil Mitchell 2005-2015 - Neil Mitchell <ndmitchell@gmail.com>
data-binary-ieee754-0.4.4 - MIT -  - John Millikin <jmillikin@gmail.com>
clock-0.7.2 - BSD3 - Copyright  Cetin Sert 2009-2016, Eugene Kirpichov 2010, Finn Espen Gundersen 2013, Gerolf Seitz 2013, Mathieu Boespflug 2014 2015, Chris Done 2015, Dimitri Sabadie 2015, Christian Burger 2015, Mario Longobardi 2016 - Cetin Sert <cetin@corsis.eu>, Corsis Research
binary-0.8.3.0 - BSD3 -  - Lennart Kolmodin <kolmodin@gmail.com>
containers-0.5.7.1 - BSD3 -  - 
bytestring-0.10.8.1 - BSD3 - Copyright (c) Don Stewart          2005-2009,
(c) Duncan Coutts        2006-2015,
(c) David Roundy         2003-2005,
(c) Jasper Van der Jeugt 2010,
(c) Simon Meier          2010-2013. - Don Stewart,
Duncan Coutts
deepseq-1.4.2.0 - BSD3 -  - 
array-0.5.1.1 - BSD3 -  - 
base-4.9.0.0 - BSD3 -  - 
integer-gmp-1.0.0.1 - BSD3 -  - Herbert Valerio Riedel
ghc-prim-0.5.0.0 - BSD3 -  - 
rts-1.0 - BSD3 -  - 
```

**Comment by jtdaugherty** [comment]
Interesting. After running `cabal configure` with the exact same `Setup.hs` in place, I have nothing in the `autogen` directory.

**Comment by glguy** [comment]
Make sure you have a `build-type: Custom` in your .cabal file

**Comment by jtdaugherty** [comment]
Yeah, I made that change, too.

**Comment by jtdaugherty** [comment]
Since bindists are now supported, let's continue the copyright notice discussion on #182.
