### ISSUE TITLE
Spell checker support

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#133]
I'm a terible spellir, so I wood like tu hav spellcheking suport.

**Comment by aisamanra** [comment]
We might be able to do this by shelling out to an external program optionally, for example, using `aspell` on Unix systems.

**Comment by travitch** [comment]
I am also a terrible speller

**Comment by elliottt** [comment]
There are (old) haskell bindings to aspell, I'd be happy to take a crack at integrating this if everyone is on board.

**Comment by jtdaugherty** [comment]
This has now been implemented as of bc153f9a0ae800735d692c87c58658e08d2a9a5b. It is initially turned off and can be enabled installing `aspell` and then by setting `enableAspell = True` in the Matterhorn `config.ini`. In addition, a dictionary override can be specified with the `aspellDictionary` config setting.

**Comment by benjaminfjones** [comment]
How does the feature work? I see how to enable it, but what should I expect after that?

**Comment by jtdaugherty** [comment]
See also #268.
