### ISSUE TITLE
channels header can get scrolled off the screen

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#138]
If you go far enough down the users list then the header for the channels can get scrolled off. It's hard to make it appear again because of the logic brick uses to scroll lists.

**Comment by jtdaugherty** [comment]
This *should* be fixed by 5d4d061e5edde9a706f8a47e3d3b34bc9b685897 but I can't test completely until someone other than me sends a message to Town Square while I'm offline.
