### ISSUE TITLE
Include mattermost-api version, too

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#141]
Since we depend on another crucial package, it'd be nice if that package's version could be included in the help page/version output.

More generally, a full manifest of all Haskell package dependencies would be nice, but we don't need to show that to people unless they really want to see it.

**Comment by dagit** [comment]
We can likely borrow the logic from [glirc](https://github.com/glguy/irc-core) to do this. I know it has support, but I can't easily point at the implementation.

/CC @glguy

**Comment by glguy** [comment]
The dependencies are gathered here: https://github.com/glguy/irc-core/blob/v2/Setup.hs#L92-L117

The dependencies are reported here: https://github.com/glguy/irc-core/blob/v2/src/Client/Options.hs#L127-L144
