### ISSUE TITLE
Client does not enforce server-side message length limit

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#142]
Long messages (not sure how long) give an exception like this:

```
An unexpected error has occurred! The exception encountered was:
MattermostServerError "Error requesting /api/v3/teams/[REDACTED]/channels/[REDACTED]/posts/create: Invalid message"
Please report this error at https://github.com/aisamanra/matterhorn/issues
```

We should see if we can give a better error to the user.

**Comment by jtdaugherty** [comment]
In a better world, we'd be able to interrogate the server to get its message limit. That would ensure that our enforcement of the limit matches the server behavior. But as far as I can tell, asking the server about its limit is not possible - which means it may become stale. I'd rather let the server give us the error shown above than enforce a stale limit, so I'm closing this. If anyone else has any other ideas, let's discuss.
