### ISSUE TITLE
Improve startup time by loading more data asynchronously

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#143]
At startup we:
* Request all channels
* For each channel, request the user-specific metadata for that channel to get the last-viewed time for it

Prior to server version 3.5 we got all of this data in one request and now we have to make O(N) requests for N channels. As a result startup time can be dramatically worse, especially on slow connections. The web client appears to asynchronously fetch user-specific metadata only when the user changes channels, and we could do the same. But that would require some redesign because right now we assume that we have that state from the beginning.

I'm also not sure how the web client determines that channels other than Town Square have unread messages on startup without fetching this data. (Maybe it doesn't, but just fetches it all asynchronously and updates the channel statuses as the responses come in. I haven't checked to see what it does.)

**Comment by dagit** [comment]
Has anyone complained about the slowness? It's not bothering me personally, for example. So from my point of view, I'd rather keep the code simple for now.

In terms of addressing it, I wonder if we could come up with an abstraction that hides the fetches so that we could program like all the data is available on startup but it's actually fetched as needed. Sort of like how laziness works for pure computations but instead applied to data we get from the MM server.

**Comment by jtdaugherty** [comment]
I haven't gotten any reports from anyone else, but I've noticed it myself, both at the office and offsite. I share your concern about complexity, but I think we can handle the complexity with abstraction. I also think that doing some things to make this better will not result in much more complexity, given that our async framework is already pretty easy to use.

**Comment by jtdaugherty** [comment]
This is now done. On my current slow connection, this caused my startup time (i.e. the time between running the command and seeing the UI) go to from 11 seconds to 2 seconds. That timing will improve even more for users subscribed to more channels than I am.

**Comment by jtdaugherty** [comment]
Attn @aisamanra as well:

In this vein I'd also like to mention that we now have *asynchronous work queue preemption* support which has really improved matters; see the commit message for https://github.com/matterhorn-chat/matterhorn/commit/43c137a768600c1f629b8d997373bd38b96d72e1.
