### ISSUE TITLE
Generate an error when host is not set in config

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#150]
Right now if the host is not set then authentication attempts will fail and the user is left to speculate on why they can't authenticate.

We could easily head off this problem by checking for an empty `host` and either prompting for the proper `host` or providing an appropriate error and requiring the user to set it in the config.

**Comment by rrwright** [comment]
also consider if a different key name would be more informative. Examples: `domain` or `server`

**Comment by jtdaugherty** [comment]
@dagit my preference is to make `host` optional and to provide a workflow similar to authentication when `user` is not set (i.e. prompt the user for the server hostname). Once implemented, this would make it possible to run `matterhorn` without even providing a config file.
