### ISSUE TITLE
vert_join on fully clipped

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#151]
I was editing in preview mode and I pasted from my clipboard when matterhorn crashed with the message:

```
matterhorn: vert_join on fully clipped
```

My copy and pasting from my terminal has been a bit flaky (using a nightly of iterm2 that seems to have copy&paste bugs). But I thought it might still be worth reporting the crash in case others see it.

**Comment by jtdaugherty** [comment]
This bug in Vty should be fixed in the latest release. Details are at https://github.com/coreyoconnor/vty/pull/116

**Comment by jtdaugherty** [comment]
I'd like to close this for now since work was done upstream. If this happens again, please re-open!
