### ISSUE TITLE
JSON decode exception

### ISSUE THREAD

**Issue by cdrage** [matterhorn-chat/matterhorn#153]
Getting an odd issue with JSON decode exception upon logging in.

Authenticating...
Loading channels for team "centos"...
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "mmGetJSONBody: Error in $: expected Seq a, encountered Object", jsonDecodeExceptionJSON = "{\"channels\":[{\"id\":\"7ii9r7nbi7r79dcykajcipwh9c\",\"create_at\":1482344373786,\"update_at\":1482344373786,\"delete_at\":0,\"team_id\":\"\",\"type\":\"D\",\"display_name\":\"\",\"name\":\"3gcaimpdr3gkujuhn3n4zhjcma__aiqzhbz8cpyjxf8u4reqj8as1h\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":0,\"total_msg_count\":0,\"extra_update_at\":1482344373786,\"creator_id\":\"\"},{\"id\":\"kkpizii5qbd7pmhu46i35bkuuo\",\"create_at\":1482992429938,\"update_at\":1482992429938,\"delete_at\":0,\"team_id\":\"\",\"type\":\"D\",\"display_name\":\"\",\"name\":\"aiqzhbz8cpyjxf8u4reqj8as1h__u5dic1hjapbaxepjzp5geg1j3c\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1482992841847,\"total_msg_count\":3,\"extra_update_at\":1482992429938,\"creator_id\":\"\"},{\"id\":\"xyckeuo743nytchaew8x3qj7fo\",\"create_at\":1476992885130,\"update_at\":1476992885130,\"delete_at\":0,\"team_id\":\"9nqq69f17tgkmmbwtnfkzqnhhy\",\"type\":\"O\",\"display_name\":\"Off-Topic\",\"name\":\"off-topic\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1480531109829,\"total_msg_count\":24,\"extra_update_at\":1483547857928,\"creator_id\":\"\"},{\"id\":\"pjtbmng5wpfpxkdzcrmdp6otwc\",\"create_at\":1476992885122,\"update_at\":1476992885122,\"delete_at\":0,\"team_id\":\"9nqq69f17tgkmmbwtnfkzqnhhy\",\"type\":\"O\",\"display_name\":\"Town Square\",\"name\":\"town-square\",\"header\":\"\",\"purpose\":\"\",\"last_post_at\":1479909791822,\"total_msg_count\":28,\"extra_update_at\":1483547857924,\"creator_id\":\"\"}],\"members\":{\"7ii9r7nbi7r79dcykajcipwh9c\":{\"channel_id\":\"7ii9r7nbi7r79dcykajcipwh9c\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":0,\"msg_count\":0,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1482344373787},\"kkpizii5qbd7pmhu46i35bkuuo\":{\"channel_id\":\"kkpizii5qbd7pmhu46i35bkuuo\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":1482992841847,\"msg_count\":3,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1482992841847},\"pjtbmng5wpfpxkdzcrmdp6otwc\":{\"channel_id\":\"pjtbmng5wpfpxkdzcrmdp6otwc\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":1479909791822,\"msg_count\":28,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1479909791822},\"xyckeuo743nytchaew8x3qj7fo\":{\"channel_id\":\"xyckeuo743nytchaew8x3qj7fo\",\"user_id\":\"aiqzhbz8cpyjxf8u4reqj8as1h\",\"roles\":\"\",\"last_viewed_at\":0,\"msg_count\":0,\"mention_count\":0,\"notify_props\":{\"desktop\":\"default\",\"mark_unread\":\"all\"},\"last_update_at\":1481817314362}}}"}

Any ideas?

**Comment by jtdaugherty** [comment]
Can you provide the version of your Mattermost server and git commit for your build of `matterhorn`?

**Comment by cdrage** [comment]
@jtdaugherty Version: 3.3.0 of Mattermost (this is a public Mattermost server so I have no control over it). And git commit of aed4e408e045d9cf787cf5c91ff4139e5b80f251 which is the last commit of:
```
commit aed4e408e045d9cf787cf5c91ff4139e5b80f251
Author: Getty Ritter <gdritter@galois.com>
Date:   Wed Dec 28 14:45:55 2016 -0800

    Added incomplete attachment support
```

**Comment by jtdaugherty** [comment]
Thanks! Right now `matterhorn` works only with Mattermost 3.5. Sorry!

**Comment by jtdaugherty** [comment]
(And for the time being, `matterhorn` will be tracking the latest release of the Mattermost server.)

**Comment by cdrage** [comment]
@jtdaugherty Ah poop! I'll tell em to update it. Thanks man :)

**Comment by jtdaugherty** [comment]
You're welcome. If there is nothing else you need here, please close this ticket (or let me know what else I can do).
