### ISSUE TITLE
Feature Request: Rebindable Keys

### ISSUE THREAD

**Issue by acw** [matterhorn-chat/matterhorn#155]
I didn't see a ticket for this, but this is something that I'd like to see: the ability to change the keybindings so that they work better for me.

I've had a couple ideas floating around in my head about how to implement this; what are some of the requirements people would have on such a system, if I were to take a stab at it?

**Comment by jtdaugherty** [comment]
@acw we have had several conversations about this and would like to do it at some point. If you want to do it, that'd be very welcome. Thoughts off the top of my head:

* The syntax for specifying keybindings should match the syntax we use in the Help part of the UI (which can change, but it should use the same representation, whatever it is)
* The config file should be used to store these bindings

**Comment by jtdaugherty** [comment]
It'd also be really helpful if we (at least one of {myself, @aisamanra, @dagit}) can whiteboard your ideas with you before you start coding!

**Comment by jtdaugherty** [comment]
Another thought: when this is done, let's make sure `sample-config.ini` has a complete (but commented) section on how to set all known bindings.

**Comment by aisamanra** [comment]
I should mention that I have a currently-vaporware alternate API for `config-ini` which will allow you to generate minimal default configuration files from the same monadic value used to parse configuration files. Once I finish that (which shouldn't be long; I just need to, y'know, _do_ it) we'll be able to generate `sample-config.ini` automatically.

**Comment by jtdaugherty** [comment]
Awesome! Does that let you embed explanatory comments?

**Comment by jtdaugherty** [comment]
For me most of the value in `sample-config.ini` is in the options that are not set at all but just documented.

**Comment by aisamanra** [comment]
That's the plan: you should be able to add explanatory comments to each field, as well as optionally emit commented-out versions of fields that have a known default. (This API, once it exists, should also allow us to do comment-preserving update of an existing file, so that configuration changes made within `matterhorn` could be reflected back into the config file without destroying the ordering or comments that already appear in it.)

**Comment by jtdaugherty** [comment]
Awesome!

**Comment by jtdaugherty** [comment]
Another request to consider for this feature (via @dagit) is keybinding synonyms, i.e., support for multiple keybindings for the same action.

**Comment by jtdaugherty** [comment]
Another note on this topic is that we'll need to do an audit of the drawing code for places where we've hard-coded bindings in text messages (e.g. the hint that appears under the multiline editing box, as well as the list of bindings that appear in message select mode). Those will need to show the active bindings once there is a system for customizing them.

**Comment by aisamanra** [comment]
I've begun working on this on the feature/keybindings branch. It needs some cleaning but the basic functionality is present: you can use the `[KEYBINDINGS]` section in your configuration file to overload the keybinding for a given operation, setting it to one or more key combinations.

**Comment by aisamanra** [comment]
This feature has been stable and merged as of 40600.0.0.
