### ISSUE TITLE
General User-Facing-String-Handling System

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#166]
Right now, lots of the UI messages are inlined, and it'd probably be better to keep them all in one place, maybe in a `Strings.hs` module. This would be advantageous for a few reasons:

1. Certain strings might depend on user configuration—for example, strings that reference key bindings which will become configurable—and it'd be nice to treat all strings in a uniform way, in case they might eventually depend on configuration.
2. Right now some strings can lag behind the current actual state of the project—for example, an error message still references the old aisamanra/matterhorn repo instead of the new matterhorn-chat/matterhorn repo—and having all the strings in one place would make it easier to remember to update them all together, as opposed to having to trawl the whole source tree for relevant string literals.
3. If we ever want to include internationalized messages, having messages all in one place would make that a lot easier.

**Comment by jtdaugherty** [comment]
This has been migrated to the wiki: https://github.com/matterhorn-chat/matterhorn/wiki/Feature-Backlog
