### ISSUE TITLE
Matterhorn crashes when presented with non-UTF8 characters from external editor

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#168]
If you save a file in some odd means, such as encrypting it before returning to MH, then the client will exit hard instead of telling you you're a fool.

```
 | M-k                     -- Use VIM 7.3+
 | blah                    -- non-empty text
 | :set cm=blowfish2       -- Set crypto mode
 | :X                      -- Encrypt
 | password
 | password
 | :x
Then observe with moderate probability:
 | matterhorn:
 | /var/folders/0x/hlxcgy9n5714ryp0gkn5hkmm0000gp/T/matterhorn_editor178448449274243042.tmp:
 | hGetContents: invalid argument (invalid byte sequence)
```

We should probably just issue a warning to the user or even silently drop the darn message.

**Comment by jtdaugherty** [comment]
Mentioning here for posterity: a `ByteString` read of the file followed by an attempted decode of the contents (with an error notification to the user on failure) would be a better path here.
