### ISSUE TITLE
Add support for yanking non-verbatim content

### ISSUE THREAD

**Issue by amaloz** [matterhorn-chat/matterhorn#171]
Right now error messages cannot be yanked in message selection mode. To reproduce:

1. Somehow produce an error message (e.g., ones of the form "An unexpected error has occurred! ...")
2. Try to yank the text using `C-s y`.

**Comment by jtdaugherty** [comment]
This should also be broadened to support yanking other kinds of content, i.e., full messages, client messages, etc.

**Comment by abhin4v** [comment]
Currently, it is not possible to select a client message in the message select view. Does this issue include making that possible?

**Comment by jtdaugherty** [comment]
Yes.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. The default key for yanking an entire message (including client messages) is `Y`, but can be customized under the `yank-whole-message` binding name.
