### ISSUE TITLE
capture stdout/stderr when running sub processes

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#175]
For operations that run a shell command (like `urlOpenCmd`) we don't currently capture stdout or stderr and this means that anything these commands output confuse the vty rendering. It's easy to get your terminal back to a good state with `C-r`, but I think a more ideal solution would be to capture stdout/stderr and then show that to the user ourselves (I'd advocate for a special buffer where you can check on the output of commands, but not to interrupt the user with the details).

**Comment by jtdaugherty** [comment]
I'm not sure putting the output in a separate special buffer will be valuable; if I experienced that, I'd learn never to check the special buffer, or I'd just make my opener command hide that output to cut down on the noise. I think an opener command that produces output should trigger a client message in the current channel that shows the output, and if the output is not desired, that would motivate the user to silence it.

Another thing we can do is to implement a configuration option (default `False`) that causes `matterhorn` to silently ignore all stdout/err output from opener commands. Then the above output to the channel could suggest setting that option. This combo approach takes care of three concerns I have:

* Make it easy for the user to find out if there was output, which will initially be unexpected
* Make it easy to turn off such output (and I don't think adding a wrapper is an easy or portable approach)
* Avoid adding UI elements that can users will be trained to ignore

**Comment by jtdaugherty** [comment]
Another idea that might be simpler overall is to capture the output of this command in a log file and mention the log file (in `$TMP`, say) in the chat window so the user knows where to look.

**Comment by dagit** [comment]
Yeah, maybe this is one of those things where we just implement the simplest thing and then see how it goes. In the case that motivated this for me, the output of `xdg-open` has never been useful (yet). As a temp solution I made a wrapper shell script that just dumps the output to `/dev/null`. Having a log file that I can check when this falls down would be nice.

**Comment by jtdaugherty** [comment]
This is now implemented. For example, given the URL opener script
```
#!/usr/bin/env bash

echo "stuff!"
echo "error!" >&2
```
we get
```
[19:51] Program "/Users/cygnus/.bin/opener" produced unexpected output; see
        /var/folders/9d/smp1mkdn6kldd088rm7w95600000gn/T/matterhorn1144108930470211272.log
        for details.
```
and in the log,
```
Program: /Users/cygnus/.bin/opener
Exit code: ExitSuccess
Stdout:
stuff!

Stderr:
error!
```
