### ISSUE TITLE
Add support for ad-hoc channels

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#180]
Mattermost 3.7 introduced *ad-hoc channels* for group messaging. Right now if someone using the web client adds a `matterhorn` user to such a channel, the matterhorn user will at least be able to participate in the channel. But:

* we need the ability to create such channels
* we need to render them more effectively in the sidebar
* we need a way to leave, hide, or delete them (the web browser client seems to have a heuristic for when to hide old ad-hoc channels, so we could look at that)
* and probably other workflow things I don't know about because I can't inspect the UX in the web client right now

At the very least I've found that their channel type is `G` (set to `Unknown "G"` by `mattermost-api` right now because we lack a specific constructor). More info on these can be found at

https://docs.google.com/document/d/11vpkjruX1dWtY5FF-hzGDNmYxO7Z_rsZVDQMOKxgJrc/edit#

**Comment by jtdaugherty** [comment]
More learning: type `G` channels have `channelDisplayName` values set to the list of users in the group discussion, e.g. `cygnus, gdritter, dwest`. Changing `matterhorn` to use channel display names instead of normal names everywhere makes this render as `#cygnus, gdritter, dwest` in the sidebar. The `channelName` field of these channels includes a user-unfriendly ID value (e.g. `12c35e30ff40f9b9d693561d3c29d7f538bfd795`).

**Comment by jtdaugherty** [comment]
Also: as best I can tell, the official API docs don't document how to create ad-hoc channels.

**Comment by jtdaugherty** [comment]
I think that for our internal 3.7 release, at a minimum we just need to make matterhorn render these channels reasonably in the sidebar. I've already done the prototyping for this and can get it into `server/3.7.1`.

**Comment by jtdaugherty** [comment]
`server/3.7.1` now includes a commit to:
* show group channels using their human-readable display name (this includes the users in the group)
* omit group channels from tab completion (which breaks if they are included and doesn't make sense anyway)

**Comment by jtdaugherty** [comment]
Attempts to `/leave` group channels generate the same server error as generated by attempting to `/leave` direct channels, so I've generalized our `/leave` blacklisting to include both `Group` and `Direct` channels.

**Comment by kellymclaughlin** [comment]
I hit an issue related to these channels this week where another user initiated a group message including me, but it never appeared in the channels list and I didn't notice until I restart the client for another reason.

**Comment by jtdaugherty** [comment]
@kellymclaughlin thanks for the report. That particular issue is now fixed in `develop` in bdbb99f6fcc286884e30db4b0e56a2c8349eb1c5.

**Comment by jtdaugherty** [comment]
This feature is now finished in `develop`:
* `/leave` now hides group channels. This is analogous to the web client's 'x' button to hide group channels.
* `/group-msg user1 user2 ...` creates group channels or shows preexisting ones hidden by `/leave`.
