### ISSUE TITLE
Do final review of repository and project status prior to open source announcement

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#188]
Let's make sure we've had a chance to do a final review of the code and repository before we make this officially public.

- [x] Audit `mattermost-api` for professionalism concerns

**Comment by dagit** [comment]
I did my scan over `mattermost-api` and a tiny bit of cleanup. I committed it to the `server/3.8.1` branch because I'm assuming that will get merged very soon.

**Comment by dagit** [comment]
I finished my review of the `matterhorn` sources and pushed the only minor change to `master`.

**Comment by jtdaugherty** [comment]
@dagit and I have both done our own reviews and consider this done enough.
