### ISSUE TITLE
Release mattermost-api to Hackage

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#189]
As part of the open source release, let's push an initial mattermost-api release to Hackage. Also ensure that all mattermost-api committers are able to upload mattermost-api releases to hackage.

**Comment by dagit** [comment]
We should remember to remove `-Werror` from the cabal file of mattermost-api before uploading to hackage. Optionally, find a way to only enable `-Werror` when building on travis.

**Comment by jtdaugherty** [comment]
This is now fixed in mattermost-api. (And as for Jason's comment, currently only the travis build uses `-Werror`.)

**Comment by jtdaugherty** [comment]
(I mistakenly closed this, thinking it was a different issue.)
