### ISSUE TITLE
Write up experience report for building matterhorn

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#193]
This ticket is about writing up an experience report detailing our work on this Haskell software, including how it went, what it does, and dependencies we benefitted from.

**Comment by jtdaugherty** [comment]
@aisamanra - have you had a chance to write up a draft of this?

**Comment by aisamanra** [comment]
I've started but not finished. I've got some free time today I'll use to finish up a draft.

**Comment by jtdaugherty** [comment]
This is done and the final version is scheduled for publication today.
