### ISSUE TITLE
Add FAQ entry about Gitlab authentication support

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#194]
The README needs to mention this to avoid confusion with new users who are likely to want to use Gitlab integrated authentication.

**Comment by pgdagenais** [comment]
Are you able to login using gitlab ? I have been trying to make it work and it seems that I am not able to login

**Comment by jtdaugherty** [comment]
Gitlab authentication is not supported right now; is that what you're asking about?

**Comment by pgdagenais** [comment]
Yes sorry, I thought it was. 

Thank you for the quick reply !

**Comment by jtdaugherty** [comment]
You're welcome. This ticket is a reminder for us to make it clear in the README that Gitlab authentication is not supported, although we're happy to work with anyone who wants to investigate what it would take to make it possible.
