### ISSUE TITLE
Investigate options for screencast creation

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#196]
We'd like to investigate our options for making nicer tutorial material (e.g. animated GIFs or short narrated videos).

**Comment by aisamanra** [comment]
Here is the [`asciinema`](https://asciinema.org/) tool I mentioned which might be useful for this.

**Comment by jtdaugherty** [comment]
This is still a great idea, but I'm closing it because it's going to be a ton of work to prep for this (dev server with dummy data, planning out what to demo and in what order, multi-user collaboration to demonstrate interactivity, etc.) and we don't have the resources to re-do the screencast every so often when the application changes enough to warrant it.
