### ISSUE TITLE
Set up shared OSX/Linux binary release infrastructure

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#199]
We need shared infrastructure for making binary releases for our supported platforms (OS X and Fedora currently).

**Comment by jtdaugherty** [comment]
At this point we have VMs for Fedora 25 and Ubuntu 16.04.2 LTS. OS X build support is pending.

**Comment by aisamanra** [comment]
I should remark here that I've talked to Dan about this and he's mentioned that it's in progress, but I should continue bugging him about when it's going to be completed. He indicated that it would be done "soon" the last time I talked to him, but didn't give a particular time, and that was two or so weeks ago.

**Comment by jtdaugherty** [comment]
Okay. Can you work with Dan to nail down a concrete deadline by which this can be ready?

**Comment by aisamanra** [comment]
Absolutely. I'm opening an IT ticket about this as we speak.

**Comment by jtdaugherty** [comment]
I've done a successful build on one of the new OS X hosts, so this is now complete. Thank you, @aisamanra!
