### ISSUE TITLE
Generate v4 API bindings from Swagger specifications

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#202]
To improve our API stability and avoid tedious manual labor, we need to be using the Swagger specifications developed by the Mattermost community to generate stubs for our API v4 endpoint library.

**Comment by dagit** [comment]
I looked into this a little bit. I wasn't super impressed with our options for yaml parsing. What I would like to investigate next is the possibility of translating the yaml to json and then parsing it.

**Comment by jtdaugherty** [comment]
Can you say more about what you are looking for in YAML parsers and aren't seeing?

**Comment by jtdaugherty** [comment]
Related to this, Mattermost will have all-V4 API endpoints starting in September. So in August we'll need to either get this ticket finished, or bail on the effort and code the V4 API endpoints by hand. (Judging by what I've heard about the specs and the surrounding tooling, it might not be worthwhile to bother with the specs - but that might also improve in the mean time.)

**Comment by jtdaugherty** [comment]
Context for this investigation is now captured [on the wiki](https://github.com/matterhorn-chat/matterhorn/wiki/API-V4-Code-Generation).

**Comment by nqzero** [comment]
i'm working on a mattermost-compatible server. so far i've been using manual coding based on packet sniffing but i'm considering moving to the swagger-based spec. i'm not working in haskell, but much of this work is language agnostic. is there a mailing list or equiv where this work is being discussed that i could join ?

**Comment by jtdaugherty** [comment]
@nqzero you might have best results by contacting the server developers directly; they have a Mattermost instance for this at

https://pre-release.mattermost.com/core/channels/town-square

As for our work, you can read about our investigations on the wiki page I linked above.

**Comment by dagit** [comment]
@nqzero I don't know what language you're working in, but OpenAPI (I guess swagger was renamed) does have code generation tools: https://github.com/swagger-api/swagger-codegen

You should see if it meets your needs.

**Comment by nqzero** [comment]
thanks to you both. i'm working in java so there are lots of openapi tools. however, the current mattermost yaml fails with every tool that i've tried (a problem that i think i've seen you've struggled with as well based on the wiki). and even if i can get the tooling working there's the issue of mating up the generated code with the existing implementation (again, you mention this in your wiki). i also don't see much on the websocket stuff

for now i'm leaning towards just generating a list of endpoints and message formats and using the list to verify that i've coded them all, and then for tracking changes going forward. fwiw, openapi2jsonschema is able to process some of the yaml before it dies

i'll track the wiki and this issue, and if i end up getting any automated tooling working on my end i'll post it here

**Comment by jtdaugherty** [comment]
@nqzero I suspect that until they start using their own specs, we will continue to see stability/completeness issues with them. And as @dagit has found, it's also possible the tooling and library landscape around this technology will make it a pain to work with.

**Comment by jtdaugherty** [comment]
On that note, though, it would be very helpful if you discuss your findings with the server developers so that they know people are trying to use those specs!

**Comment by jtdaugherty** [comment]
Closed in favor of #303.
