### ISSUE TITLE
Fix scrollback message duplication

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#206]
Right now we use `mmGetPosts` with an offset to fetch extra scrollback (e.g. using `C-b`). To do this we determine the fetch offset by taking the length of the relevant channel's message list. But this is wrong because that length will also include non-post entries such as local client messages. To avoid this problem we should fetch scrollback by looking at the timestamp of the oldest known message and then use `mmGetPostsBefore`. Its return type is the same as `mmGetPosts` so the change should be pretty straightforward.

**Comment by kquick** [comment]
Note that this also affects message-select cursor movement: the duplicated message represents a barrier to message selection.

**Comment by kquick** [comment]
The scroll blocking is another manifestation of Issue #224.

**Comment by jtdaugherty** [comment]
This is now fixed since the `issue_224` merge.
