### ISSUE TITLE
Add new API endpoints for pinned post support

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#215]
Creating this here instead of in the mattermost-api package so that I can keep all the 3.8 stuff in one place.

New routes (APIv3):

  * `GET` at `/channels/{channel_id}/pinned` Returns the pinned posts in a channel
  * `POST` at `/channels/{channel_id}/posts/{post_id}/pin` Pins a post to a channel
  * `POST` at `/channels/{channel_id}/posts/{post_id}/unpin` Unpins a post from a channel

**Comment by jtdaugherty** [comment]
API endpoints for pinned posts are now in `mattermost-api`, but just disabled; they can be enabled once work on the feature takes place.
