### ISSUE TITLE
writeHistory: set file mode on history files

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#218]
At present, `writeHistory` writes the history to a file but does not set its mode, so we get history files that are readable by everyone. This is insecure since the history contains messages sent to direct or private channels. The only thing preventing this from being a serious problem is the permission on the XDG config directory, but if that is relaxed, then the history can be read by anyone.

**Comment by jtdaugherty** [comment]
Would you be willing to remove the comment and instead create a ticket, perhaps with more context on what needs doing?

**Comment by dagit** [comment]
Yes, but I didn't do that because I don't know what needs doing.
