### ISSUE TITLE
Vector index Out of bounds

### ISSUE THREAD

**Issue by awfulartisan** [matterhorn-chat/matterhorn#222]
Matterhorn continually crashes on me when switching through direct message channels.

```
matterhorn: ./Data/Vector/Generic/Mutable.hs:690 (read): index out of bounds (-41,50)
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.11.0.0-BEDZb5o2QOhGbIm6ky7rl6:Data.Vector.Internal.Check
```

I am new to haskell and haven't been able to collect a full stack trace to debug the issue further.

The more I am switching channels the more prevalent this issue is.

**Comment by jtdaugherty** [comment]
Thanks for the report!

Please provide this information so we can investigate a bit further:
* GHC version
* Matterhorn version (if binary release, then release version; otherwise git revision)
* The version of the server you're trying to use the client with

Are you using a public server? If so, we'd like to try it out. If you can provide the hostname, perhaps we can create a test account and reproduce the problem. (This does not happen on any servers we've used, so it may be server-specific.)

**Comment by awfulartisan** [comment]
Thanks for the quick response to this:

- GHC: version 8.0.1
- Matterhorn: da4f4b4f099161b8916f5b83f7dd66f557faf189
- Mattermost: v3.7.5

I am running this via the docker container. The issue seems most prevalent when quickly switching between channels.

**Comment by dagit** [comment]
Is it possible to test against v3.7.3? I think you can give docker the version number as a tag when you download/start the container. Thanks!

**Comment by awfulartisan** [comment]
The instance running the server does not support docker at the moment.

**Comment by dagit** [comment]
Sorry, I thought you said you were using a docker container. I don't have a way at the moment to test against 3.7.5 (having some local docker issues), but it looks like that release was made yesterday and that our testing is mainly against 3.7.3.

**Comment by awfulartisan** [comment]
I had previously been running against 3.7.0. I only upgraded to 3.7.5 today to see if that would improve the situation. I did say I was using docker, but meant I am using docker to run matterhorn. The mattermost server is running as a daemon (no docker).

**Comment by jtdaugherty** [comment]
@awfulartisan - it would be really helpful if we could get more information on what *does* work: can you give us a narrative of how things go and what works, up to and including keystrokes you send that cause error behavior?

**Comment by awfulartisan** [comment]
Almost everything works flawlessly. It seems almost random. I have been able to reproduce it with some effectiveness by sending ctrl g, 2x before typing. But it happens under other circumstances as well.

This error comes when switching channels on an active session, maybe 5 seconds old, or maybe 2 days old.

**Comment by jtdaugherty** [comment]
If matterhorn is running in docker, how are you attaching to it in the terminal?

**Comment by awfulartisan** [comment]
My run command looks like this. It provides me an interactive session matterhorn

```sudo docker run -it --rm   -e MM_USER=email   -e MM_PASS=pass -e MM_HOST=hostname  -e MM_PORT=443   --name matterhorn matterhorn```

**Comment by jtdaugherty** [comment]
Is it possible to run matterhorn directly, without Docker at all?

**Comment by awfulartisan** [comment]
I just pulled the binary out of the docker container and it still fails under the same circumstances.

**Comment by jtdaugherty** [comment]
What terminal emulator are you using?

**Comment by awfulartisan** [comment]
The build commands being run are these:

```
cd matterhorn && \
      cabal update && \
      cabal sandbox init && \
      cabal sandbox add-source ../mattermost-api && \
      cabal install --force-reinstalls && \
      cabal build
```

I had to add the --force-reinstalls or the build wouldn't work for me.

**Comment by jtdaugherty** [comment]
What's the current revision for `mattermost-api`?

**Comment by awfulartisan** [comment]
```
For the builds above, it's using master from both repos (current up to a few minutes ago). I tried messing with it and forcing them to both compile the same release version, but that didn't change things. 

I am using iterm2 on mac to connect to a box over ssh to attach to tmux session with matterhorn running.

```

**Comment by awfulartisan** [comment]
Is there any more information I can provide to help with this?

**Comment by jtdaugherty** [comment]
You could take the approach that we'll take when we get time: find obvious uses of `Data.Vector` API calls in `matterhorn` and annotate the functions that use them with `HasCallStack` constraints so that the `error` call includes more call stack information. The only way we can fix this is to narrow down where it occurs, and there are a lot of candidates. That, combined with our limited time to look into this and the apparently random nature of the bug make this difficult to track down using any means other than call stack information.

If annotating functions with `HasCallStack` in `matterhorn` doesn't improve the traces, it may be necessary to dig into one or both of `vty` and `brick` and do the same there.

**Comment by dagit** [comment]
In addition to what @jtdaugherty suggests, you could try running with logging enabled to see if there are any obvious errors. There might be sensitive information in your log file so I would advise AGAINST sharing it directly.  To enable logging use the following command line switch:

      -l PATH  --logs=PATH    Path to the desired debug logs

**Comment by jtdaugherty** [comment]
The other thing you could do that would be helpful is to find a specific sequence of input and actions that reproduce this problem consistently for you.

**Comment by jtdaugherty** [comment]
Here are the details that will be helpful for us:
* Information about the channels you have joined: how many are there? What kind are they? (Private, direct message, group, public, etc.)
* What do you do that triggers the problem, in detail? What steps do you take and what input do you provide? Be as specific as you can. E.g. "I join a channel for the first time and switch to it with `C-g`, then the client crashes" or "I switch to a direct message channel with `/focus` and then when I switch back to the previous normal channel with `M-s`, the client crashes"

**Comment by awfulartisan** [comment]
There is only a single team at play here. There are about 150 members. 

I have narrowed down the issue to switching from a message to a user far down the list and trying to switch to a channel higher in the list.

Example:

Open matterhorn, join town-hall
C-g sally (sally is far down user list)
C-g t (as soon as I press t, matterhorn crashes with the error I provided)
note on this, I was trying to do `c-G town` and press enter to switch to `town-hall`, but it crashes as soon as t is entered, I do not get to press my enter key.

I have found that if instead of `C-g t` I press `C-g literalspace backspace t` the application does not crash. This seems to be a bug related to the list of users/channels and switching from a user toward the end of the list, and the 1st letter of the next `c-G` matches a channel/user at the top of the list.

**Comment by jtdaugherty** [comment]
Thanks for those details - we will investigate!

**Comment by jtdaugherty** [comment]
@awfulartisan - I have a question: in the error message, a tuple is shown (here `(-41, 50)`). When this error arises, can you check on whether the second number (`50`) corresponds to your terminal window height (in rows)? Or even close to that?

And if you resize your terminal window (say reduce by a row) and run `matterhorn` again, does the second number reduce by the same amount?

**Comment by awfulartisan** [comment]
yes it seems to correspond to this.
I shrunk the terminal window, and tested 3 times. Increasing window height by 1 for each test. I did not change the width.

```
(-72,31)
(-71,32)
(-70,33)
```

Thank you for all the help with this.

**Comment by jtdaugherty** [comment]
Thanks for testing; that helps narrow this down considerably.

**Comment by jtdaugherty** [comment]
@awfulartisan - is it possible for you to get the the output of `cabal sandbox hc-pkg list` from the build you're using?

**Comment by jtdaugherty** [comment]
@awfulartisan - another request for testing: can you test and determine whether the second tuple value in those errors actually *is* the height in rows? If not, what relationship does it have to the height? For example, is it always `height - 1`?

**Comment by awfulartisan** [comment]
Here's the output of the first request:

https://gist.github.com/awfulartisan/6763220d250a1eed9aa3272b9cb7c5c6

As for the second:

I was able to confirm the first tuple entry is related to the index in the list. By trying using sally1, sally2, sally3; the first tuple element decremented for each.

As for the second tuple element, it seems to be the height of the session:

```
$ echo $LINES
44
$ sudo docker run -it  --rm matterhorn
matterhorn: ./Data/Vector/Generic/Mutable.hs:690 (read): index out of bounds (-84,44)
$ echo $LINES
43
$ sudo docker run -it  --rm matterhorn
matterhorn: ./Data/Vector/Generic/Mutable.hs:690 (read): index out of bounds (-85,43)
$ echo $LINES
35
$ sudo docker run -it  --rm  matterhorn
matterhorn: ./Data/Vector/Generic/Mutable.hs:690 (read): index out of bounds (-93,35)
```

Note that for each of these tests I switched to the same user, the last user in my list. and then attempted to switch back to town-hall. 

After this second test, I also noticed that the offset of the first tuple entry changed when the height changed.

**Comment by jtdaugherty** [comment]
See also #235.

**Comment by jtdaugherty** [comment]
@awfulartisan - I've made some changes to `matterhorn` that may resolve this. Can you try a build from `master` and tell me whether the situation has improved?

**Comment by awfulartisan** [comment]
I had to upgrade my server to 3.8.2
I rebuilt the client from master and everything is working now! Even seems a bit more responsive. Well done, thank you for taking this so seriously and resolving it. Much appreciated.

**Comment by jtdaugherty** [comment]
@awfulartisan I'm glad to hear that it's working now - you're welcome!
