### ISSUE TITLE
Notifications are not reported in all cases

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#223]
I want to start off by saying, I don't know how to reproduce this, but I've run into several instances in the last week or so where I've discovered that matterhorn is not reporting channel activity. Sometimes I notice because I restart my client and other times I notice after logging into the webclient to check something.

**Comment by jtdaugherty** [comment]
I'm going to close this for now because there isn't enough information here to investigate. But if this happens again, please feel free to re-open and provide more detail!

**Comment by dagit** [comment]
I'd definitely like to leave this open as it's still happening and I have to restart my matterhorn every time my network connection bounces.

**Comment by jtdaugherty** [comment]
Okay. If it happens that frequently, would it be possible for you to provide any more detail on this? I closed it because I prefer to only have open tickets that have enough characterization to be actionable, so if we could get more info on this then someone could potentially work on it without having to see your client in action when it occurs.

**Comment by dagit** [comment]
I've put everything I currently know about it into the ticket and I haven't been able to sit down and debug it. If I had to guess, reproducing it probably requires losing network access ungracefully and also receiving specific types of web events while the network is down.

I agree that actionable issues are better, but I'd hate to lose track of this issue simply because we didn't know a reproducible test case. It's kind of annoying bug and I really wish I didn't have to restart my client every time I change networks.

**Comment by jtdaugherty** [comment]
@dagit - a lot of work went into this recently and I know for sure that some bugs were fixed. Would it be okay with you if we close this for now and consider it done, unless something else arises?

**Comment by dagit** [comment]
I'll close it for now. I just spent a few minutes trying to manually reproduce and I couldn't.
