### ISSUE TITLE
Message selection gets blocked by error messages

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#224]
Message selection cursors can't get past error messages in channel message lists.

**Comment by kquick** [comment]
To reproduce this, type a bogus command (e.g. `\bogus`), and then type a valid message, and then try to select and move the selection upward.  The error generated by the bogus command represents a select movement barrier.

**Comment by jtdaugherty** [comment]
Kevin's been working on a fix for this so I'm assigning it to him.

**Comment by jtdaugherty** [comment]
This is now fixed since the `issue_224` merge.
