### ISSUE TITLE
Binary releases is a tarball inside of a tarball

### ISSUE THREAD

**Issue by cdrage** [matterhorn-chat/matterhorn#233]
The Linux binary release is a .tar inside of a .tar.gz, which doesn't accurately reflect the installation instructions:
```
wget https://github.com/matterhorn-chat/matterhorn/releases/download/<VERSION>/matterhorn-<VERSION>-<PLATFORM>.tar.gz
tar xf matterhorn-<VERSION>-<PLATFORM>.tar.gz
cd matterhorn-<VERSION>-<PLATFORM>
./matterhorn
```

**Comment by jtdaugherty** [comment]
Yikes! I'll investigate and get a fixed release up later today. Thanks for the report.

**Comment by jtdaugherty** [comment]
Oh, I mis-read your report. The releases are structured as desired and in a standard way, and the installation instructions we provide should be adequate; in what way are they not working for you?

**Comment by cdrage** [comment]
@jtdaugherty Ah crap, you're right. 

What ended up happening was that the software I was using (xarchive) wasn't functioning correctly.

**Comment by jtdaugherty** [comment]
I see. In that case, please close this unless there's something else I can help with. Thanks!
