### ISSUE TITLE
Unable to run on Ubuntu 16.04: libtinfo.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by UlfS** [matterhorn-chat/matterhorn#240]
Trying to run the [linux binary 30802.1.0](https://github.com/matterhorn-chat/matterhorn/releases/download/30802.1.0/matterhorn-30802.1.0-Linux-x86_64.tar.gz) results in the following error message on Ubuntu 16.04.2 LTS (Xenial).
```
> ./matterhorn
./matterhorn: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

Looks like it is dynamically linked to `libtinfo6`, which it cannot find:
```
> ldd ./matterhorn 
        linux-vdso.so.1 =>  (0x00007ffdb9983000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0882773000)
        libtinfo.so.6 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f088256a000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0882367000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0882162000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0881f45000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f0881cc5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f08819bb000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f08817b3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08813ea000)
        /lib64/ld-linux-x86-64.so.2 (0x000055ff2eb0b000)
```
I can only find libtinfo5 in my sources:
```
> apt-file search libtinfo.so
lib32tinfo-dev: /usr/lib32/libtinfo.so
lib32tinfo5: /lib32/libtinfo.so.5
lib32tinfo5: /lib32/libtinfo.so.5.9
libtinfo-dev: /usr/lib/x86_64-linux-gnu/libtinfo.so
libtinfo5: /lib/x86_64-linux-gnu/libtinfo.so.5
libtinfo5: /lib/x86_64-linux-gnu/libtinfo.so.5.9
libtinfo5-dbg: /usr/lib/debug/libtinfo.so.5
libtinfo5-dbg: /usr/lib/debug/libtinfo.so.5.9
libx32tinfo-dev: /usr/libx32/libtinfo.so
libx32tinfo5: /usr/libx32/libtinfo.so.5
libx32tinfo5: /usr/libx32/libtinfo.so.5.9
```

The `libtinfo5` description says that this is a terminfo library for ncurses.

I'm not really in the mood of compiling `ncurses6` at the moment... :(
Any suggestions on what to do?

**Comment by jtdaugherty** [comment]
Thanks for the report!

Is it possible for you to build from source? (I know this may not be possible or it may be onerous.) If it isn't possible, I can look into shipping binary releases for Ubuntu, but even then it'd be a specific version of Ubuntu (probably the latest).

The binary that we provide for Linux is actually for Fedora; I'll make a ticket to improve our release archive naming so that's clearer.

**Comment by UlfS** [comment]
I build it from source, which worked fine (after installing `happy`), but was greeted with a json decode exception mentioning the server version after logging in.

After looking at the [readme](https://github.com/matterhorn-chat/matterhorn#our-versioning-scheme) I checked out the corresponding tag `30701.0.0` and built it again.
This resulted in a compilation error in `src/Types.hs `. Looking at the log I saw that it was still using the wrong `mattermost-api` dependency - so I adjusted that as well and rebuilt it.

This worked fine but after starting it, logging in and seeing the chat window for a split second it crashed again with the following message:
```
> ./.cabal-sandbox/bin/matterhorn 
Authenticating...
Loading channels for team "epages"...
matterhorn: src/Network/Mattermost/WebSocket/Types.hs:147:10-38: No instance nor default method for class operation fromDataMessage
```

**Comment by jtdaugherty** [comment]
Is it possible for you to build the 30802.1.0 tag and use a 3.8 server? There's a fix for that websocket issue in 3.8.

**Comment by UlfS** [comment]
I don't have direct access to the mattermost server, but I will try to figure something out.
Thank you for your help!

**Comment by jtdaugherty** [comment]
Okay. You're welcome - this has been helpful to raise some issues we need to work on. Thanks!

**Comment by aparcar** [comment]
On Debian Testing I have the same error message with 30802.1.0, should I open a new issue?

**Comment by jtdaugherty** [comment]
@aparcar - no, that's the same kind of problem reported here. In particular, our binaries are for Fedora 25 only, so running on any other distribution is likely to yield dynamic linking errors. Going forward we will be producing Ubuntu Xenial binary releases, so you can either run those (out soon) or build from source. Sorry!

**Comment by jtdaugherty** [comment]
@SithaJagan I think you might have reported this on the wrong project.

**Comment by armoralesr** [comment]
> Hi,
> I was trying to install Fermi software in my laptop which has OS type 64bit Ubuntu 16.04-LTS. My heasoft version is 6.24. I did not get any error while installing fermi. Then I edited my bashrc to give path to Fermi directory and did alias. After initializing heasoft, I was trying to initialize fermi, at that time I was not able to initialize Fermi from terminal. Then I tried setting environment of Fermi from the terminal itself and trying to run `gtselect`. But showed the error
> 
> > gtselect: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
> 
> I tried to locate `libtinfo.so`. Then terminal shows this:
> 
> > /lib/x86_64-linux-gnu/libtinfo.so.5
> 
> > /lib/x86_64-linux-gnu/libtinfo.so.5.9
> 
> > /usr/lib/x86_64-linux-gnu/libtinfo.so
> 
> Hence I created a soft link using this command:
> 
> > sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.5.9 /lib/x86_64-linux-gnu/libtinfo.so.6
> 
> After this, I could initialize fermi from the terminal itself. But, the above mentioned error remains still while doing `gtselect`.
> 
> > gtselect: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
> 
> Earlier, in my Ubuntu 14.04-64 OS with heasoft 6.22 version, I didn't get any error like this. Can anyone suggest a solution for this?

I had the same issue, and try this

sudo ln -s /lib/x86_64-linux-gnu/libncurses.so.5.9 /lib/x86_64-linux-gnu/libncurses.so.6

**Comment by jtdaugherty** [comment]
Since this ticket seems to get a lot of Google traffic, I wanted to just mention down here at the bottom that we do release builds for 18.04, so check out the 18.04 build if you're having this problem.
