### ISSUE TITLE
Messages prefixed with "#." always display as "1." in matterhorn

### ISSUE THREAD

**Issue by wridgers** [matterhorn-chat/matterhorn#243]
If you send or receive a message with matterhorn that started with "#." (where # is a number), it will be displayed as "1.". In the mattermost web client, the messages will display correctly.

**Comment by jtdaugherty** [comment]
Thanks for the report - can you be a bit more specific about what behavior you expected and observed? I can't reproduce what you're describing. (For example, typing a message `#. Foo` in `matterhorn` does not result in `1. Foo`.

**Comment by jtdaugherty** [comment]
@aisamanra reproduced this and is looking into a fix.

**Comment by jtdaugherty** [comment]
@wridgers - if you're running a binary release, we'll get this fix out in the next release. If you're building from source, you can just pull and rebuild to get the fix.

**Comment by wridgers** [comment]
@jtdaugherty - all fixed! Thanks @aisamanra.
