### ISSUE TITLE
ability to select channel within fast selection mode

### ISSUE THREAD

**Issue by amaloz** [matterhorn-chat/matterhorn#247]
Suppose you have channels `~abc` and `~abcd`.  If you use fast selection mode to try to jump to channel `~abc`, the mode will display both channels and it's not possible to select between the two.  It'd be nice to have some keybinding that can select channels from this list.

**Comment by jtdaugherty** [comment]
Thanks for the request! This is a duplicate of #81.

**Comment by jtdaugherty** [comment]
This is now supported in `develop` and will go out in the next release.
