### ISSUE TITLE
List URLs in a reasonable order.

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#250]
I'm seeing:

```
User1:  See LINK1 and LINK2
User2: Hey guys
LINK3
LINK4
User3: LINK5
```

What order will you see these in in `C-o` view?

```
LINK5
LINK3
LINK4
LINK1
LINK2
```

What say you to fixing this? I'm asking in part because the current behavior seems intentional, here's my fix:

```
-    in removeDuplicates $ concat $ F.toList $ F.toList <$> Seq.reverse <$> msgURLs <$> msgs
+    in removeDuplicates $ concat $ F.toList $ F.toList <$> msgURLs <$> msgs
```

**Comment by TomMD** [comment]
Actually I think we should not bother fixing this.  Now I'm thinking it should behave more like vimpernator's `o`.  The first two letters of every link are overwritten (text extended if needed) with a unique index (00,01.. a0..zz, AA..ZZ) which if typed will cause the link to open.  Same with attachments.  Special handling of small or no-text links needed.

**Comment by jtdaugherty** [comment]
@TomMD - I'm not sure what to make of your follow-up comment. There is definitely an *intended* order to the URLs, and I think this was working up until some recent refactoring changed how messages are stored internally, thus flipping the order. I think your change is the right one.

**Comment by jtdaugherty** [comment]
Okay, wait a second. :) What version are you running? I cannot reproduce this behavior. I see the expected ordering (most recent URL at the bottom).

**Comment by TomMD** [comment]
This main issue is the order of URLs found in a single message:

```
me: URL1 URL2
you: URL3
```

Results in:

```
URL3
URL1
URL2
```

I think it should be visually ordered, and thus be:

```
URL3
URL2
URL1
```

**Comment by jtdaugherty** [comment]
I don't think the order you gave is visual order. I'd expect that to be
```
URL1
URL2
URL3
```
Do you agree?

**Comment by jtdaugherty** [comment]
(For posterity: there was confusion on this ticket but the core issue was that although the global URL list was in the right order, multiple URLs *in the same message* were out of order with respect to their original message.)
