### ISSUE TITLE
Error when switching channels after going to a private message.

### ISSUE THREAD

**Issue by cdrage** [matterhorn-chat/matterhorn#251]
```
matterhorn: ./Data/Vector/Generic/Mutable.hs:690 (read): index out of bounds (-38,17)
```

Literally the only error I get, but essentially:

1. I'm in a normal channel
2. I switch to a private message (Ctrl + G)
3. I press Ctrl+G again to switch back to the normal channel (begin typing in the name).
4. I get the above error

I'm running version:
```
matterhorn 30802.0.0 (master@32b3ec8) 
```

**Comment by cdrage** [comment]
Welp, changing to the newest release: `30802.1.0` seems to have fixed it. Closing.

**Comment by jtdaugherty** [comment]
Yes, that bug was indeed fixed - I'm glad you found a newer release that works for you!
