### ISSUE TITLE
HTTP error represented as tuple on login screen

### ISSUE THREAD

**Issue by bernerha** [matterhorn-chat/matterhorn#254]
If theres an error on the login e.g. HTTP 400 the user gets the message 

> Error: (4,0,0)

What we need is a better represantion of common errors e.g. "HTTP 400 Bad Request blablabla" or something like "Oh there is a error please try again or file a bug report. Errormessage: HTTP 400 Bad Request"

**Comment by jtdaugherty** [comment]
Thanks for the report! That is indeed worth improving.

**Comment by jtdaugherty** [comment]
This has been improved by https://github.com/matterhorn-chat/mattermost-api/commit/6bf9137dade335b497cd245fa63f681a1e423cf9.
