### ISSUE TITLE
New Message indication not updated for deleted messages

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#256]
When a new message arrives in a channel not currently being viewed, the channel is highlighted in the search bar, and when the channel is selected, a "New Messages" barrier is provided in the output.

If the new message is deleted before the channel is viewed:
1. The "New Messages" barrier should not be shown if there are no non-deleted messages following it.
2. The channel list highlighting can be removed if there are no new non-deleted messages to show.

**Comment by jtdaugherty** [comment]
https://github.com/matterhorn-chat/matterhorn/commit/3fd8790a2172c06a69e37f9a25bbd86f46190fc6 fixed (1).
