### ISSUE TITLE
Deleting your own reply to an already deleted message raises an error

### ISSUE THREAD

**Issue by benjaminfjones** [matterhorn-chat/matterhorn#257]
Bob posts a message, Dormamu replies. Bob deletes his message. Then, Dormamu tries to delete his reply and matterhorn raises an error:

```
[16:20]  ┌▸bob: @joe, the full list is available b...
        dormamu: delete me
[16:21] An unexpected error has occurred! The exception
        encountered was:
        MattermostServerError "Error requesting
        /api/v3/teams/5k97pnsfjpbrbenrceggq49g8h/channels/
        You do not have the appropriate permissions"
        Please report this error at
        https://github.com/matterhorn-chat/matterhorn/issu
```

The reply and the error message disappear after a restart.

**Comment by jtdaugherty** [comment]
Upon investigation it turns out that this is because deleting a message *also deletes all replies to it*, but matterhorn doesn't know this and leaves the replies around.
