### ISSUE TITLE
Channel join messages can be faked

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#259]
Since we do a simple string match to determine whether a message is a server-generated channel-join message, any user can fake one of these in matterhorn by typing a message that contains the substring "has joined the channel." This ticket is for looking at whether there is some metadata we can use to determine this instead of (or in addition to) looking at the message content. This is one of a class of hacks we've had to implement when the server predetermines presentation rather than letting the client take care of it using metadata.

**Comment by jtdaugherty** [comment]
Same goes for "has left the channel."

**Comment by aisamanra** [comment]
This has been fixed by 5b78e66, as this data is indicated by the `"type"` field of posts, which is now encoded in a `PostType` type from `mattermost-api`. There are several other post types we don't use yet, but we should start paying attention to those, too.

**Comment by jtdaugherty** [comment]
Fantastic. Thanks!
