### ISSUE TITLE
Support connecting to servers that use self-signed SSL certificates

### ISSUE THREAD

**Issue by arudat** [matterhorn-chat/matterhorn#263]
If I try to connect I get the error 
 Error: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)

is there a typical "option hack" to ignore that? ;)

**Comment by jtdaugherty** [comment]
@arudat - not yet, but we can investigate. Thanks!

**Comment by MartinDelille** [comment]
I'm having this issue too. Any update?

**Comment by jtdaugherty** [comment]
@MartinDelille we have not spent any time on this, as evidenced by the lack of commentary and commits on this issue. If someone wanted to work on a patch, here's what would need to happen:

* A new command-line option, `--disable-certificate-validation`, would need to be added to Matterhorn. The option should *not* have a short form; this ensures that the option cannot be typed by accident.
* A new configuration file setting, `validateServerCertificate`, should be added to the config file parser.
* The new setting should also get added to `sample-config.ini` with very clear cautionary documentation stating that it should only be set to `False` when the user is willing to give up security.
* The `Config` type in Matterhorn should get a new field, `validateServerCertificate`, whose default should be `True` and whose value should be set by the config file parser when parsing the field mentioned above.
* The `connection` library's `TLSSettings` type exposes a field, `settingDisableCertificateValidation`, that appears to do what we'd need to make this work. That field needs to be set in the TLS settings for the `connection` library. To make that possible, the `mattermost-api` package's `Network.Mattermost.Util.mkConnection` function should be passed a `TLSSettings` *instead* of a `Bool` for `useTLS` to allow customized control over the TLS setup. That's going to impact a few other places that make connections.

We're available for questions if someone starts on this and runs into issues, but this should be enough to get someone started.

**Comment by MartinDelille** [comment]
Thank you for these informations! Unfortunately I don't code in Haskell and have little time to dedicate to this (maybe fixing the certificate would be more appropriate 😅).

**Comment by daveman1010221** [comment]
Just built this on Mac OS High Sierra and ran into this issue. If I have some spare cycles, I'll look into fixing this. Any chance that trusting the self-signed certificate somewhere will just fix this issue?

**Comment by jtdaugherty** [comment]
Under the hood, Matterhorn uses the `connection` library, which in turn uses the `x509-system` library, to load the set of trusted certificates. That code is [here](http://hackage.haskell.org/package/x509-system-1.6.6/docs/src/System-X509-Unix.html#getSystemCertificateStore) and it just loads a PEM-encoded certificate store from `/etc/ssl/cert.pem` on OS X. As far as I know, trusting a cert via the OS X Keychain utility -- the typical way to trust one, anyway -- won't have any impact on that file so that probably isn't a viable path.

**Comment by daveman1010221** [comment]
Is there any way to get some verbose logs out of the client?

**Comment by daveman1010221** [comment]
A simple solution could involve adding a user-configured certificate store.

**Comment by jtdaugherty** [comment]
As for logging, you can enable that with logging commands (type `/log` to see the options) or with a command-line option (`-l`).

**Comment by daveman1010221** [comment]
In case anyone else runs into this, you can add the root certificate for your mattermost server to your system keychain on Mac OS. This solves the problem perfectly.

**Comment by jtdaugherty** [comment]
Awesome, thanks @daveman1010221!

**Comment by lazamar** [comment]
I was able to use an unsafe ssh certificates in a machine where I did not have sudo access to change the accepted certificates by disabling certificate validation in the `mattermost-api` code and recompiling matterhorn.

More precisely, changing the first `False` to true here did the trick.

https://github.com/matterhorn-chat/mattermost-api/blob/ad1f816a12708c44bd4c2a144fb9af114e7f7449/src/Network/Mattermost/Util.hs#L86

**Comment by jtdaugherty** [comment]
This is now implemented in `develop` via the config setting `validateServerCertificate`.
