### ISSUE TITLE
Spawn a thread when invoking URL-opening command

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#270]
Right now we assume that the URL-opening command will exit more or less immediately, i.e., by instructing the OS to start the browser (usually an asynchronous operation). But users may use the *actual browser* as the URL-opening command, and if the first invocation is also the first instance of the running browser, it will not exit immediately. If this is the case, our async worker thread will block on waiting for that subprocess to exit, thus causing incoming websocket events and other async work to pile up until the user quits the browser (which might never happen).

So this ticket is to make a simple change to spawn the URL-opening subprocess in a new thread to protect the async worker thread from getting stuck.

**Comment by jtdaugherty** [comment]
We also need to ensure that the subprocess is spawned so that it is not terminated when `matterhorn` quits.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`; @kquick - you mentioned you'd be happy to test on your setup where you've seen this routinely.

**Comment by jtdaugherty** [comment]
@kquick - have you been able to test this?

**Comment by kquick** [comment]
Yes, sorry for forgetting to followup here.  The latest code works perfectly, so I vote for including it in the next release.

**Comment by jtdaugherty** [comment]
Okay. Thank you!
