### ISSUE TITLE
Compose message in external editor (e.g. Vi)

### ISSUE THREAD

**Issue by tgy** [matterhorn-chat/matterhorn#271]
One nice thing about Mattermost is that it supports multi-line Markdown messages. 

From my point of view, what is really missing from `matterhorn` and prevents me from switching to a `matterhorn`-only setup is that it is not possible to compose multi-line Markdown messages.

The perfect way I see for handling this issue, instead of trying to re-create a very complicated multi-line editor inside of `matterhorn` itself, would be to delegate the message composition task to the user's own editor (defined by the environment variable `$EDITOR`).

This is exactly how it is done in other CLI programs such as the mail client `mutt`.

What do you guys think?

**Comment by jtdaugherty** [comment]
Did you check the feature list and "Using the Client" sections of the README? :)
```
To send a message, type it into the editor and press Enter to send. To send a
multi-line message, toggle multi-line mode with the default binding M-e.
Markdown syntax is accepted.

To edit your current message in an external editor ($EDITOR), use the default
binding of M-k.
```

**Comment by jtdaugherty** [comment]
These features are both also documented in the in-program help (accessible via `F1` or `/help`).

**Comment by tgy** [comment]
@jtdaugherty My bad, should have read that. :) That's perfect!
