### ISSUE TITLE
Support jump-to-post in post list overlay mode

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#272]
The post list overlay is currently used for displaying flagged posts, and eventually will be used for search results and pinned posts as well. One operation that would be nice is jump-to-post, where the user can select a post and jump to it in the scrollback. This is going to require some thought about how to manage the internals of `matterhorn` and how we represent lists of posts, so I'm making this its own issue.

**Comment by jtdaugherty** [comment]
@kquick this is done, but I can't tell (in the changelog) when it actually got introduced. Do you recall?

**Comment by kquick** [comment]
It was part of the message-select/scrollback changes in 50200.2.0 (but alas, not documented in the Changelog).

**Comment by jtdaugherty** [comment]
Okay, thanks! I'll add it.
