### ISSUE TITLE
Support editing previous message

### ISSUE THREAD

**Issue by tgy** [matterhorn-chat/matterhorn#276]
**User story**
After sending a message and realizing he made a typo, Bob wants to modify his already sent message. Bob would like to be able to edit this message in his `$EDITOR` (because he's a Vim baghead) the same way he can compose a new message in his `$EDITOR` by pressing `M-k`.

**Comment by jtdaugherty** [comment]
Then Bob need only do the following:
* Press `C-s` to enter message selection mode.
* Select his previous message with the cursor.
* Press `e` to edit.
* Press `M-k` to open the old message in `$EDITOR`.
* Modify, save, and exit.
* Press `Enter` to send the edited version of the message.

**Comment by tgy** [comment]
Great! Thanks
