### ISSUE TITLE
Add debounce for channel selection movement

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#280]
Currently, Matterhorn will respond immediately to any channel selection activity (where the response includes fetching channel contents, updating the server's current and previous viewed markers, and other bookkeeping).

However, one possible use case is that the user rapidly moves the channel selection (e.g., via C-n and C-p) from the current channel to a new channel that is several channels away from the starting point.  Performing all of the updates for the intervening channels is unnecessary work and the side effects of clearing new message indicators are potentially undesireable.

It's recommended that these events be "debounced" by delaying the response to them for a small period of time and only enacting the last event after the events stop occurring.  The delay period would be very small, but large enough to eliminate unneeded background activity.

**Comment by kquick** [comment]
While this debounce functionality must be controlled by the application itself, it may be that the actual implementation of the functionality better belongs in brick (or vty).  Conceptually, implementing this type of debounce for potentially expensive movement or selection actions may be a relatively common need, and since brick is managing the core Event loop it would alleviate the need for the client to create additional thread timers with extra communications events that would need to be channeled through brick anyhow.

As an example implementation proposal:

  * Add a new "VtyEvents` to Brick, which is a `[VtyEvent]`
  * Whenever Brick delivers an event to the application, the application can chose to respond by giving brick a DiffTime.
   * Brick then does not deliver events to the application, but begins building a VtyEvents list with that element
      * Each time a new event occurs, brick adds it to the tail of the VtyEvents.
      * If the new event is different than the previous tail, brick calls the application's event handler with the VtyEvents list.
      * If no event is received for the DiffTime period from the previous event, brick calls the application's event handler with the VtyEvents list.
   * The application can then choose to process the events, or it can decide that the expensive process is still underway and respond with the DiffTime, which instructs brick to continue building the VtyEvents.  If the application does not respond with a new DiffTime, brick drops the VtyEvents list and the DiffTime and goes back to normal event delivery mode.

The above is only a starting point for a discussion regarding consideration of the proper location of debounce functionality and ways to handle it.

**Comment by jtdaugherty** [comment]
FYI, I am strongly opposed to doing anything about this in Vty or Brick; I don't think it is general enough to justify the machinery, and I don't think it's necessary or appropriate to get the UI frameworks involved in dealing with this behavior. I'm happy to discuss other approaches.

**Comment by kquick** [comment]
Understood, but I have now wanted this debounce on 2 of my 3 brick projects, which does suggest it's potentially a more general need.  I do think the functionality I describe above could be done as a layer between brick and the application code, which would allow a better assessment of its general need without premature and unnecessary over-complication brick.

**Comment by jtdaugherty** [comment]
I agree that there's a general need and an abstraction would help. I just think it should live entirely outside the UI framework packages.

**Comment by jtdaugherty** [comment]
This ticket has been labeled `shelved` due to lack of time and/or urgency to work on this, although it may still be worthwhile to address in the long run. Anyone wanting to contribute by working on this ticket can re-open.
