### ISSUE TITLE
Missing message management

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#281]
Currently Matterhorn is optimistically fetching a certain number of messages (100) each time a channel is selected.  The number fetched is frequently much larger than the displayable amount, which ensures that the display is full, but it is inefficient, especially when channels are being scrolled over.

More significantly, this same fetch is performed on a WebSocket reconnect event.  There is currently no logic to handle the case where the disconnect may have been for a "period" of greater than the preset number of messages, which will result in the user missing messages.  For example, if Bob closes his laptop when he leaves work on Friday and the latest message in the current channel is #32, and then he resumes his laptop Monday morning and the latest message in the current channel is #232, Matterhorn will fetch messages #133-#232, but will not fetch #33-#132, and it will not have any trigger to subsequently fetch those messages, nor an indication to Bob that those messages are missing.

A naive solution to this would be to continue fetching messages until Matterhorn starts seeing duplicates, at which point it knows it has fetched the entire history.  However, this could be problematic in the case where Bob was gone for a week instead and there were several thousand messages in many channels.

There should be a better way for Matterhorn to identify where it is possibly missing messages without the overhead of actually fetching all of those messages.

**Comment by jtdaugherty** [comment]
Another naive solution would be to discard all of our scrollback and start over, i.e., emulate startup. That would certainly avoid a lot of these problems.

**Comment by kquick** [comment]
But that would make Alice unhappy because she's on a slow/flaky internet connection with frequent WebSocket reconnects, and each time it would clear the entire channel contents and fetch 100 messages over her slow connection, even thought there were few or even no new messages.  That might also interfere with NewMessage/hasUnread management.

**Comment by jtdaugherty** [comment]
I'm not convinced it would be worse, since to handle this properly we'd probably make more than one request anyway, and often establishing connections will take longer than transmitting small payloads (and here I would classify 100 messages as a small payload). Either way we have to deal with new message book-keeping, and under this approach I suspect it would be significantly simpler.

**Comment by aisamanra** [comment]
What about a combination between the two approaches? Fetch up to some medium-to-large amount of messages, but iff there are more than `$MAX` new messages in that channel, then throw away the older scrollback. That way, if we're only grabbing a few new messages, we can use the existing scrollback, but if it's so many that we'd need to do multiple requests to fetch the new ones, then we just punt and get rid of the old ones.

**Comment by kquick** [comment]
jtdaugherty: I may be misunderstanding but if we discarded all the scrollback I was thinking that would result in clearing the message screen until we'd fetched new messages, which would be visual interruptions.  I agree it probably would be similar background actions though, but it would be nice if we didn't have to fetch 100 messages if there weren't actually any new ones.  I wonder if we can ask matterhorn-api to fetch "the most recent messages, limit=100 or message_id=MMM"...

aisamanra: interesting... maybe a little perturbing to have the stuff you previously saw disappear, but if there have been a lot then maybe that old history isn't the primary concern.

We may also need to think about the effect if the user has an in-progress reply (typed, but not submitted).

**Comment by jtdaugherty** [comment]
> I may be misunderstanding but if we discarded all the scrollback I was thinking that would result in clearing the message screen until we'd fetched new messages, which would be visual interruptions.

I assume that's possible to do in one shot: asynchronously fetch new scrollback, drop it in as a replacement in one go, rather than remove, queue, fetch, replace.

**Comment by jtdaugherty** [comment]
Still, this is going to be much easier to discuss in person rather than through a ticket, with a full enumeration of the relevant concerns.

**Comment by jtdaugherty** [comment]
The result of our design discussions has been captured on the wiki: https://github.com/matterhorn-chat/matterhorn/wiki/Message-Management

**Comment by kquick** [comment]
This issue is now addressed on the `develop`.  There are some additional tweaks, but this is useable and ready for testing; the functionality is a superset of the previous functionality.

**Comment by kquick** [comment]
The main functionality has been released.  There is still some ancillary work regarding message navigation and filling of gaps, but that is captured on the wiki and already pending work.  Closing this issue.
