### ISSUE TITLE
Limit background user status requests

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#282]
Matterhorn will periodically query for user status updates by issing a users/status to the server.

Last night there was some sort of issue (HTTPResponseExectipon "mmRequest: expected 200 response, got (5,0,3)").  Upon re-connection this morning, there are 454 queued async background requests, and watching the logs they appear to be user status requests.

The user status update should probably use `asPending` or something similar to ensure that only one is outstanding at any single time.

**Comment by jtdaugherty** [comment]
I find it odd that we'd have that many queued; I'd expect them to all run and eventually fail due to, say, timeouts. Presumably the one at the head of the queue was blocked?

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
