### ISSUE TITLE
Anchor doesn't respect line breaks

### ISSUE THREAD

**Issue by bernerha** [matterhorn-chat/matterhorn#286]
An anchor doesn't break if the window isn't wide enough.
If such a anchor get clicked the browser opens only the visible part of it.

Example:

original: https://imasuperanchor.whatever/blub/bla
visible: https://imasuperanchor.whatever/bl
browser: https://imasuperanchor.whatever/bl

**Comment by jtdaugherty** [comment]
This sounds like a problem with how your terminal emulator handles hyperlinks in the terminal text. Have you taken a look at Matterhorn's URL-opening capabilities? In particular, see the `urlOpenCommand` configuration setting and the `C-o` and `C-s` keybindings.

**Comment by jtdaugherty** [comment]
If that helps, please close this issue; otherwise let me know what else is going on.

**Comment by bernerha** [comment]
I will check this after #289 and #288 are fixed :)

**Comment by jtdaugherty** [comment]
Are you running a 4.0 server?

**Comment by bernerha** [comment]
yup.

**Comment by jtdaugherty** [comment]
Then you have me wondering how you reported this issue in the first place; were you originally testing on an older server?

**Comment by bernerha** [comment]
Yeah, we updated yesterday :)

**Comment by jtdaugherty** [comment]
Okay, thanks - that explains it. :)

**Comment by jtdaugherty** [comment]
We currently tentatively plan on having a 4.0-compatible release out next Wednesday, so you'll be able to try it then.

**Comment by towolf** [comment]
Just FYI, this guy is on a quest to add support for real hyperlinks to terminal emulators:

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#viewers-editors

That would also cover scenarios covered in this bug:

```╔═ file1 ════╗
║          ╔═ file2 ═══╗
║http://exa║Lorem ipsum║
║le.com    ║ dolor sit ║
║          ║amet, conse║
╚══════════║ctetur adip║
           ╚═══════════╝```

**Comment by jtdaugherty** [comment]
Interesting, thanks @towolf. It's hard for me to assess the stability and support status of that proposal, so I'm not comfortable going ahead with an implementation, but if it matures enough and support becomes sufficiently widespread, I'be be happy to add support for that to `vty` (which is what Matterhorn uses for terminal I/O).

**Comment by bernerha** [comment]
mh, fetch, rebase, install.sh -> matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event: Unknown websocket message: \"channel_viewed\"", jsonDecodeExceptionJSON = "{\"event\":\"channel_viewed\",\"data\":{\"channel_id\":\"n1qjsjhqwfbedesc7xgtenm5ch\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"gisusgt7k7d69csrymhrs5tgic\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":2}"}

Did I forgot something?

**Comment by jtdaugherty** [comment]
How are you running the `matterhorn` binary? Are you sure it's the most recently-build version? What do you get when you run `matterhorn --version`?

**Comment by bernerha** [comment]
Ahhhh mhhhh ohhhh, yeah i see. mattermost-api 30802.1.0 (master@3c1c4e0)
What do i have to run to get the latest bin?

**Comment by jtdaugherty** [comment]
```
$ ./install.sh
$ ./run.sh
```

**Comment by jtdaugherty** [comment]
This is only true for source builds. You might consider a binary install from the Releases section of the repo here.

**Comment by bernerha** [comment]
Na, I stick with the source build. Master is the correct branch for the 40000.0.0?
Maybe i forgot something else. I'm going to reclone the repo and try it again.

**Comment by jtdaugherty** [comment]
Yes, `master` - in particular, then `40000.0.0` tag.

**Comment by bernerha** [comment]
Currently i have another problem with my ghc environment and static/dynamic linking under archlinux.
First I have to fix this :)

**Comment by jtdaugherty** [comment]
Okay. At this point I'm going to close this ticket because there is no evidence this is clearly a Matterhorn bug; please feel free to open issues if you run into problems once you get your setup working again. Thanks!

**Comment by dagit** [comment]
@bernerha You may need to install the `ghc-static` package as per this thread: https://www.reddit.com/r/haskell/comments/6nleqc/arch_haskell/dkagahv/
