### ISSUE TITLE
Crash on startup with 4.0

### ISSUE THREAD

**Issue by towolf** [matterhorn-chat/matterhorn#287]
`matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event: Unknown websocket message: \"channel_viewed\"", jsonDecodeExceptionJSON = "{\"event\":\"channel_viewed\",\"data\":{\"channel_id\":\"4j54fnnsf8wpyzwfs7p8b7y1w\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"cbzd35i7rpn69dnag5t8h711a\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":1}"}
`

**Comment by jtdaugherty** [comment]
Thanks for the report!

Matterhorn does not support Mattermost 4 yet, but when it does, you'll be able to tell by the Matterhorn version number. It'll be something like `matterhorn-40000.0.0`. For more information, see the README's section on our versioning scheme.

**Comment by towolf** [comment]
Ah, thanks. Sorry, I skipped this bit in the README.

**Comment by jtdaugherty** [comment]
No problem. The report is still useful, and I've filed it away so that we're aware of it when we begin updating for 4.0.

**Comment by jtdaugherty** [comment]
Closing in favor of #288; you can track the progress there.
