### ISSUE TITLE
Support channel_viewed websocket event

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#288]
See also: https://docs.mattermost.com/administration/changelog.html

**Comment by Ilya-Kuchaev** [comment]
It's still an issue in 31000.0.0

**Comment by jtdaugherty** [comment]
@Ilya-Kuchaev that's right, Matterhorn 31000.0.0 is not compatible with 4.0 servers so will exhibit problems with this websocket event. You can expect Matterhorn 40000.0.0 to resolve this.

**Comment by aisamanra** [comment]
I should have been clearer that my comment was about the current state of our API package and the current state of our develop branch; we haven't backported those fixes into a release yet.

**Comment by jtdaugherty** [comment]
This is now complete as of https://github.com/matterhorn-chat/matterhorn/commit/2aae28467c06a2468bc6e57aaa4ef23d1c8c4a27 and will be released in version `40000.0.0`.
