### ISSUE TITLE
Support channel_updated websocket event

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#289]
See also: https://docs.mattermost.com/administration/changelog.html

**Comment by aisamanra** [comment]
We currently have this event in mattermost-api and don't crash when it arises, but we don't do anything with it.

**Comment by jtdaugherty** [comment]
This is now complete as of https://github.com/matterhorn-chat/matterhorn/commit/2aae28467c06a2468bc6e57aaa4ef23d1c8c4a27.
