### ISSUE TITLE
Implement more text-editing keybindings

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#29]
Such as:
- `M-Backspace`: delete word backward
- `M-d`: delete word forward
- `M-{Left,Right}`: move by word
- `C-k`, `C-y`: kill and yank

**Comment by dagit** [comment]
For the first one, I wrote a simplified version of delete word backwards when I implemented tab completion. We should find away to reuse that code.

**Comment by elliottt** [comment]
I'd like to add `C-w` for kill-backward.

**Comment by jtdaugherty** [comment]
Note to self: I factored out `killWordBackward` already. It just needs to be used in an event handler for the relevant key combinations.

**Comment by jtdaugherty** [comment]
I'd also like `C-t`.

**Comment by jtdaugherty** [comment]
`C-t` is now implemented.

**Comment by travitch** [comment]
C-f (forward-char) and C-b (backward-char) would be nice for consistency with shells, but are obviously not essential

**Comment by travitch** [comment]
Thanks!

**Comment by aisamanra** [comment]
Every keybinding mentioned here is currerntly implemented in HEAD, so I'm going to close this issue.
