### ISSUE TITLE
/focus of self error

### ISSUE THREAD

**Issue by towolf** [matterhorn-chat/matterhorn#294]
Just for kicks I used `/join tobias.wolf` (i.e. myself) and got this error:

```[12:04] An unexpected error has occurred! The exception encountered was:                                                       
        MattermostServerError "Error requesting /api/v3/teams/sg5harc4ibybtfzd1pqmabaxgr/channels/create_direct: Unable to add 
        direct channel members"                                                                                                
        Please report this error at https://github.com/matterhorn-chat/matterhorn/issues                                       
```

Not sure if this is so unexpected and perhaps another message could me shown.

**Comment by jtdaugherty** [comment]
Thanks for the report. Can you be more specific about the conditions when you did this? For example, our `/join` command does not accept arguments. Did you mean `/add-user`?

**Comment by jtdaugherty** [comment]
Also, which version of Matterhorn are you using?

**Comment by towolf** [comment]
Sorry, that was `/focus tobias.wolf` not `/join`.

**Comment by jtdaugherty** [comment]
Thanks! I've reproduced this bug and we'll see about putting out a fix in the release tomorrow.
