### ISSUE TITLE
Built binaries are with wrong extension

### ISSUE THREAD

**Issue by XANi** [matterhorn-chat/matterhorn#295]
File have gzip extension but is bzip2 archive:

    $ file matterhorn-40000.0.0-Ubuntu-x86_64.tar.gz
    matterhorn-40000.0.0-Ubuntu-x86_64.tar.gz: bzip2 compressed data, block size = 900k

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
I've also uploaded files with correct extension to the latest release tag on GitHub.
