### ISSUE TITLE
Report unknown websocket messages rather than crashing

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#297]
Proposal to show an error in the current channel (similar to how a browser error is shown on C-o) instead of completely halting matterhorn when an unknown websocket message is received.

Justification: full crash of matterhorn is a very jarring user experience.  The nature of JSON allows for extension of the messages, but the core set of messages should already have been verified before being released, so the likelihood of an unknown message causing aberrant matterhorn behavior is improbable and of lower severity than a full exit.

**Comment by jtdaugherty** [comment]
Yeah, it should also mention the issue report URL so we're sure to hear from users about it.

**Comment by jtdaugherty** [comment]
Also, I'm in favor of this approach.
