### ISSUE TITLE
The ChannelViewed webmessage can have a null channel_id

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#298]
matterhorn-4.0.0.0-2107-07-27: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.data['channel_id']: Empty ID", jsonDecodeExceptionJSON = "{\"event\":\"channel_viewed\",\"data\":{\"channel_id\":\"\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"REDACTED\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":15}"}

Current code expects to find a non-null channel ID and should be extended to handle this case.

**Comment by jtdaugherty** [comment]
From @jwilander: "That would be possible when the user clicks off the app, signifying that no channel is being actively viewed." I'll push a fix shortly.

**Comment by jtdaugherty** [comment]
This has been fixed in https://github.com/matterhorn-chat/mattermost-api/commit/a1caa2dacff9c0a5701dd27f253b3786649bb414.

**Comment by jtdaugherty** [comment]
This has been determined to be a bug upstream and was reported at https://mattermost.atlassian.net/browse/PLT-7252
