### ISSUE TITLE
Improve presentation/UX for emoji reactions

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#301]
Right now, all emoji reactions are displayed as `[name]` underneath the post in question, and we don't display who supplied the reaction, and that information would be nice to have. I would assert that we don't want to include this information in the UI directly: it could easily get cluttered with only two or three reactions. My current thought is that we add a new piece of functionality within message select mode to show that information in a dedicated pop-up window, but I'd be open to bikeshedding here.

**Comment by jtdaugherty** [comment]
I'm in agreement that showing it in the UI won't scale. I'm okay with a message-select-mode binding to show the reaction details. @kquick floated an idea that I liked, which was to show an overlay with the message including that detail, and call the binding something like "show info" (bound to "i"?) so we can stash other information there as it becomes necessary.

**Comment by jtdaugherty** [comment]
This is now somewhat superseded by #330 (which I should have marked as a dupe but didn't).

**Comment by jtdaugherty** [comment]
(Which is to say, let's move the work involved here into the #330 workflow.)
