### ISSUE TITLE
delete channel error

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#304]
Steps to reproduce:
1. Create a new channel (not a user DM channel)
2. /delete-channel

Error:
`An unexpected error has occurred!  The exception encountered was:
MattermostServerError "Error requesting /api/v3/teams/5k97..../channels/3bkot.../leave: You're the only member left, try removing the Private Channel instead of leaving."`

Since this was an attempt to remove the channel, it appears that Matterhorn should have issued a remove instead of a leave command.

The above is followed by:

`kquick: kquick has archived the channel`

The channel still appears in the Channels list, however.  Should the channel information be removed from the local client?

Trying to add a new message to this channel results in:

`An unexpected error has occurred! The exception encountered was:
MattermostServerError "Error requesting /api/v3/teams/5k97.../channels/3bkot.../posts/create: You do not have the appropriate permissions"`

If the channel were actually locally removed, this last issue would not occur.

**Comment by jtdaugherty** [comment]
Matterhorn issues a `leave` command, *then* a `delete` command. Leaving removes the channel from the UI once it completes, but the `leave` failed. It was followed by the "archive" message because the deletion succeeded.

If we know the server will behave this way, we can just remove the channel without issuing a `leave` command at all, and just do the delete.

**Comment by kquick** [comment]
Noted by amaloz: cannot leave a channel that has been archived by another user.  The error is "MattermostServerError: "Error requesting /api/v3/teams/5k97.../channels/owje...../leave: The channel has been archived or deleted".

On the webui, the channel simply isn't shown.  Restarting Matterhorn also achieves the same.

**Comment by jtdaugherty** [comment]
In that case, it seems like the only option we have is to detect that a channel has been archived (I don't know at present whether that can be done cleanly) and then auto-leave the channel in the client. How does that sound?

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
