### ISSUE TITLE
Custom slash commands not supported in client

### ISSUE THREAD

**Issue by nicholasswierczek** [matterhorn-chat/matterhorn#306]
I've created a few custom slash commands that I find very helpful, but the client doesn't seem to know how to execute them.

For example, if I have a simple custom slash command called /weather that just gets the local weather forecast, and I type  /weather in the client, it says "error running command /weather: no such command"

The client should .... let that happen. :)

**Comment by jtdaugherty** [comment]
By "created custom commands", do you mean server-side?

**Comment by aisamanra** [comment]
I've fixed this in the develop branch as of commit bc2dab3: we first check to find out whether the client has a client-specific command to intercept, and if it doesn't, we pass that command directly on to the server. Custom commands on the server should work transparently.

I'm going to leave this issue open for documentation until we merge the fix back into master and cut a new release, at which point it will automatically be closed.

**Comment by nicholasswierczek** [comment]
Awesome. Thank you.
