### ISSUE TITLE
code mode indication

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#308]
The following enhancements would be useful for code handling:

1. In normal rendering mode, show the language, because it may not be obvious.  Something like
       | [lang]
       | code

2. Input mode: have better indication of whether the language is supported, and possibly provide auto-completion.  The intent is to assist the user in creating a valid input specification by guiding them to useful specifications without them having to remember the syntax and nomenclature.

**Comment by jtdaugherty** [comment]
The first part of this ticket is done in 1f65246c69f56f22327fadd3b401a50a4f92d54d.

**Comment by jtdaugherty** [comment]
For the second part, there are two sub-parts:

 * It seems to be the best way to deal with this is to turn on preview mode and see what it does with your input. You probably want that anyway, just to see syntax errors in your code block.
 * We can definitely add the list of available languages to the tab completion set.

**Comment by jtdaugherty** [comment]
I'm going to open a new ticket for the part of this that isn't yet done so it's more specific.
