### ISSUE TITLE
Honor per-channel notification settings for activity bell

### ISSUE THREAD

**Issue by Azenet** [matterhorn-chat/matterhorn#309]
Hi,

I am having an issue with the activity bell. Currently (40000.0.2) the activity bell will ring on all messages even on channels that have had their notifications set to "Mentions only" through the web client, is it intended behavior? Is Matterhorn expected to follow the notification settings from the web client?

Thanks.

**Comment by dagit** [comment]
> is it intended behavior?

It is the way it currently works, but it's not ideal and we'd like to honor the user's settings. It's just something we haven't gotten to yet.

**Comment by jtdaugherty** [comment]
@Azenet We definitely intend to improve our support for notifications over time. As @dagit mentioned, the current behavior is intended at least in the sense that it's as far as we have gone to implement granular control over notifications. We'd be happy to work with contributors who want to make this better, and barring that, we'll get to it later.

**Comment by jtdaugherty** [comment]
@Azenet In general we aim to make `matterhorn` mimic the web client in as many ways as possible, including respecting server-side configuration. So we're aware that this is missing.

**Comment by jtdaugherty** [comment]
This is now under done on the `feature/honor-server-notify-settings` branch. The server-side user preference for desktop notifications, as well as per-channel settings for notifications, are honored (with the latter defaulting to the former). Note that this *only* applies to bell rings; unread message settings are not yet honored.

**Comment by jtdaugherty** [comment]
This feature is now merged to `develop`.
