### ISSUE TITLE
Unclosed triple-backquotes

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#312]
Typing a matterhorn message that starts with three backquotes but has no closing triple backquotes causes the output to be blank (both in preview and when the message is posted and displayed.  The web client ignores the triple-backquotes and simply displays this as a normal message.

Matterhorn should be fixed to display non-closed triple-backquote messages as normal text.

**Comment by jtdaugherty** [comment]
If we're going to do this, it seems like the best place for it is in `cheapskate`, not `matterhorn`.

**Comment by kquick** [comment]
There are some other behavioral differences as well.  All of these are related to the differences between `cheapskate` and the mattermost web client handling of Markdown.  I'll just leave this and issue 313 instead of trying to exhaustively detail the differences since the resolution for all of these is address via `cheapskate` (or possibly https://github.com/matterhorn-chat/matterhorn/issues/184).

**Comment by jtdaugherty** [comment]
@kquick would you be willing to follow up on this on the cheapskate repository issue tracker?

**Comment by jtdaugherty** [comment]
This is dormant so I've moved it to https://github.com/matterhorn-chat/matterhorn/wiki/Improved-Markdown-Handling
