### ISSUE TITLE
Lost text after closing triple-quotes

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#313]
A code block using triple-backquotes followed by code lines followed by closing triple backquotes.

In preview mode and message display mode, the starting and closing lines containing the triple backquotes are completely suppressed.

The web client will display any text on the line following either of the triple backquotes (in the mode set by the backquotes).

Matterhorn should be fixed to show this information as well.

**Comment by jtdaugherty** [comment]
Like #312, I propose this be taken up in `cheapskate`.

**Comment by jtdaugherty** [comment]
@kquick would you be willing to follow up on this on the cheapskate repository issue tracker?

**Comment by jtdaugherty** [comment]
This is dormant so I've moved it to https://github.com/matterhorn-chat/matterhorn/wiki/Improved-Markdown-Handling
