### ISSUE TITLE
Replying to messages that start on the next line doesn't show any of the original message

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#318]
If you reply to a message that starts with a linebreak you get something like this:

```
[HH:NN] user1:
          My message starts here because I did some multiline stuff or a codeblock.
[HH:NN] ->user1:                                              ...
        |user2: This is my reply.
```

I think it would be nicer if the abridged text in the reply ignored any leading whitespace.  Like this:

```
[HH:NN] user1:
          My message starts here because I did some multiline stuff or a codeblock.
[HH:NN] ->user1: My message starts here because I did some multiline stuff or a codeblock. ...
        |user2: This is my reply.
```

At any rate, it would be nice if the reply had more context than it currently gets.

**Comment by jtdaugherty** [comment]
Ah yes, this is a consequence of a contributed patch we got recently. I can fix this soon.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.

**Comment by dagit** [comment]
Thanks!
