### ISSUE TITLE
Activity Bell for only mentions and private messages

### ISSUE THREAD

**Issue by wridgers** [matterhorn-chat/matterhorn#321]
I have enabled the `activityBell = True` setting in `config.ini`.

It works, but I'm getting activity bells for everything. I think it would be good if there was an option to make the bell ring only when you receive a private message or are hilighted with <at>username - in fact, this should probably be the default behaviour.

**Comment by jtdaugherty** [comment]
Thanks for the ticket! This is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/309.

**Comment by wridgers** [comment]
No problem. Thanks for your prompt reply and continued work on Matterhorn!

**Comment by jtdaugherty** [comment]
You're welcome. (Also, note that I just implemented and closed #309 yesterday. So if you build `develop` from source, you can try it out.)
