### ISSUE TITLE
Can't enter M-... key bindings

### ISSUE THREAD

**Issue by cabo** [matterhorn-chat/matterhorn#323]
There is no documentation on how to enter M-... key bindings, and I also can't find a way to do this from reading the code.

**Comment by jtdaugherty** [comment]
The `M-` convention indicates a `Meta` key, which on most platforms and in most terminal emulators will be equivalent to `Alt`. On OS X it might be equivalent to `Option`, but depending on the terminal emulator, some configuration may be necessary.

**Comment by jtdaugherty** [comment]
I'm happy to add a note about this to the README to make that clear; please close this ticket if that works for you, or let me know what else you need. Thanks!

**Comment by cabo** [comment]
Editorially, yes, there should be a brief mention of what C-... and M-... are supposed to mean (not everyone has been an Emacs user for 30 years).

Technically, while control characters are a traditional part of terminal input, meta characters aren't.
On macOS, the option key is not available for meta, as it is used to enter —, °C, Ω, or language-specific characters such as ß and é.  The traditional way to invoke a meta combination by prefixing a character with ESC also does not work as ESC already is used for other functions.  I'm honestly at a loss how this is meant to work.

**Comment by cabo** [comment]
Well, iterm2 can be configured to send ESC+ for the right option key, leaving the left option key for entering characters that happen not to be on the basic plane of my keyboard.  The stock Terminal does not allow that (you can disable the normal meaning of option for both or for none of the option keys).  So you probably want to recommend iterm2 for macOS users (and/or provide a way to enter M-... combinations that does not rely on configuring terminal programs).

**Comment by jtdaugherty** [comment]
I've updated the README in https://github.com/matterhorn-chat/matterhorn/commit/743485aebe742f24ce26a13146e7ab441cfefa01. Thanks!
