### ISSUE TITLE
Support searching posts

### ISSUE THREAD

**Issue by abhin4v** [matterhorn-chat/matterhorn#328]
Mattermost web client supports searching for posts by search terms. There is an [API endpoint](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1teams~1%7Bteam_id%7D~1posts~1search%2Fpost) available for the same. Please support it in matterhorn. The popup used for showing the flagged posts may be reused for showing search result posts.

**Comment by abhin4v** [comment]
FYI, I am working on a PR for this issue.

**Comment by jtdaugherty** [comment]
That's great news! We'll be happy to review it when it's ready. If you haven't already seen it, please read the Contributing section of the README: https://github.com/matterhorn-chat/matterhorn#contributing

**Comment by abhin4v** [comment]
I have created one PR in the `mattermost-api` repo and one in this repo to fix this issue. I have tried to follow all the contribution guidelines. Please let me know if anything else needs to be done.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks, @abhin4v!

**Comment by jtdaugherty** [comment]
This feature is included in the upcoming 40400.0.0 release (being put together now).
