### ISSUE TITLE
Select the previously selected channel on restart

### ISSUE THREAD

**Issue by abhin4v** [matterhorn-chat/matterhorn#331]
When the matterhorn client restarts (quit and start again), it always selects the "town-square" channel. The mattermost web client remembers the last selected channel for the user and selects that channel on restarts (close the tab, reopen it). 

This feature should be implemented for feature parity and for user convenience.

**Comment by abhin4v** [comment]
FYI, I'm willing to work on this.

**Comment by jtdaugherty** [comment]
Thanks, that's great! There are some moving parts to this that we need to get nailed down, such as:

* How will the last channel state be stored? My preference: use the XDG data directory for Matterhorn to store a data file containing "last run state" that includes the channel ID of the last-visited channel.

* When a user runs Matterhorn but no such state file is present, Town Square is selected.

* When the user is not a member of the last-viewed channel, Town Square is selected.

* When the last-viewed channel has been archived, Town Square is selected.

* Matterhorn writes the last run state to disk on clean shutdown only.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
