### ISSUE TITLE
New `/join` display has unfortunate line wraps

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#349]
When I `/join` I see:

```
|room-name-1 (Some
description of room 1)
|room-name-2 (room-name-2)
...
```

That is, the description is line wrapped as though the text box is really small (plenty of space in reality) and the line wrap is not indented, which would make large room descriptions group nicely without making it hard to distinguish which line is the next room vs just a description.

This version is just built with 1981524da163b32a471788d19268a520dace7f6b (Jan16)

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks!
