### ISSUE TITLE
channel select (^G) no longer prefers an exact match?

### ISSUE THREAD

**Issue by jclulow** [matterhorn-chat/matterhorn#356]
Hi folks,

I was using `40000.1.0` until recently when I updated to `40600.1.0`, and there has been a somewhat inconvenient change to the channel select (Ctrl-G) matching rules.  I am joined to two channels, `manta` and `alarms-manta`.  I used to be able to get to `manta` by typing that exact string and pressing enter.  Since the upgrade, an exact match no longer seems to be preferred -- instead, `alarms-manta`, which is first in the sorted list, remains selected unless I type `^manta$`.

Is it possible to get the original behaviour back?

Thanks.

**Comment by jtdaugherty** [comment]
In addition to the anchor metacharacters `^` and `$`, `C-g` mode supports a cursor (highlighted in yellow) and `C-n` and `C-p` change the selection if the default selection is not desirable. You can switch the selected channel with those keys and press `Enter` to switch to the selected one. Does that help?

**Comment by jtdaugherty** [comment]
With that said, we can look at making it so that the cursor gravitates toward the item whose name exactly matches the input, if one exists.

**Comment by jclulow** [comment]
Ah, I didn't realise C-n/C-p worked for next/previous in that list.  That's a great workaround for now, thanks.

I think it would still be vastly preferable for an exact match to take precedence.  If an exact match works, I can press `C-g`, then type the full name of the channel and press enter, all without really needing to read the screen.  If I have to read the screen, it makes the process of switching quickly between a handful of channels much slower and probably more error prone.

**Comment by jtdaugherty** [comment]
Yeah, I agree - that makes sense and I'll definitely investigate. `C-g` mode is deliberately supposed to make this as easy and as fast as possible, and as you pointed out, it *did* used to behave that way, but the fact that it doesn't now is accidental.

**Comment by jclulow** [comment]
Thanks.  I really appreciate it!

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.

**Comment by jtdaugherty** [comment]
See also https://github.com/matterhorn-chat/matterhorn/commit/1827daddd2aa84ff34de6505c1de16499bc86648.

**Comment by jclulow** [comment]
I have applied the fix locally and it works just as I would expect.  Thanks again!

**Comment by jtdaugherty** [comment]
Great! You're welcome.
