### ISSUE TITLE
Incorrect link in Readme.md 

### ISSUE THREAD

**Issue by strowk** [matterhorn-chat/matterhorn#362]
Recommended installation is incorrect 
``` bash
wget https://github.com/matterhorn-chat/matterhorn/releases/download/<VERSION>/matterhorn-<VERSION>-<PLATFORM>.tar.gz
```
This wont work for latest release. 
https://github.com/matterhorn-chat/matterhorn/releases/tag/40700.0.0
For example Ubuntu link according to the doc should be 
https://github.com/matterhorn-chat/matterhorn/releases/download/40700.0.0/matterhorn-40700.0.0-Ubuntu.tar.gz
and it shows 404. 
Correct link would be 
https://github.com/matterhorn-chat/matterhorn/releases/download/40700.0.0/matterhorn-40700.0.0-Ubuntu.tar.gz

**Comment by jtdaugherty** [comment]
Thanks!
