### ISSUE TITLE
Create a ring buffer of InternalEvents

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#370]
This ticket is to create a fixed-size internal buffer of `InternalEvent`s. This buffer would be used for various purposes (logging, reporting to the user). This buffer would be LIFO buffer containing a sequence of events with most recent first, in order of occurrence/insertion (i.e. not ordered by any specific metadata such as server time associated with the event). This ticket is not about presenting that buffer, which we can address separately, but to:

 * Determine what data structure to use
 * Create a `ChatState` or `ChatResources` field for the buffer
 * Determine appropriate call sites for inserting into the buffer
 * Ensure the buffer size is constrained by a configurable setting

**Comment by jtdaugherty** [comment]
@kquick I think this might be subsumed by the recent logging work. Thoughts?

**Comment by kquick** [comment]
I agree.  We should close this out and if the logging doesn't suffice, we should determine at that point if logging should be enhanced or what makes this different than logging.

**Comment by jtdaugherty** [comment]
Okay, thanks!
