### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by buxx** [matterhorn-chat/matterhorn#374]
I got this screen when run `40700.0.0`:

![capture du 2018-03-20 08-53-41](https://user-images.githubusercontent.com/1104637/37642305-e8bf35ea-2c1c-11e8-8b35-892431d7764b.png)

Ubuntu 16.04, 

    $ uname -a
    Linux courgette 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Wat can i do ? If you need more informations, ask it.

**Comment by jtdaugherty** [comment]
That garbled output is caused because you'e running a terminal emulator that does not support terminal hyperlinking mode. Is it possible for you to use another terminal emulator than the one you are using?

**Comment by jtdaugherty** [comment]
To help with this, the next release will include a new configuration setting to disable this behavior so that you don't have to find a terminal emulator that supports it (see be55a8744de53879c9a5111589163bfe3217661e).

**Comment by buxx** [comment]
Hello,

It is working with xterm :)

Thank's.

**Comment by jtdaugherty** [comment]
Great!
