### ISSUE TITLE
tab complete people by usage

### ISSUE THREAD

**Issue by bcantrill** [matterhorn-chat/matterhorn#375]
I love Matterhorn! In fact, I love it so much (and use it so much) that I can't help but making a feature request:  I absolutely love tab-completion of names.  In our company, we have two people named "Brittany."  They're both great, but one of them is in marketing and one of them is on my team in engineering.  As one can imagine, I mention the latter much, much more in chat -- but because she's after the former in the sort order, I have to type "brit-tab-backspace-backspace-backspace-backspace-backspace-w-tab" to get to her.  (As one might infer, the Brittany in marketing has a five character last name.)  So my request for enhancement: I would love if the sort order were determined by my mention order, even if only in the same session.  I would have to do this once per session, but then the intended Brittany would be tab-completed from there on out.  (And in fact, even just biasing the result to the most-recently mentioned would be a huge win.)

Regardless, thank you for Matterhorn.  I know that open source projects can feel thankless or worse (in part because people don't stop often enough to acknowledge the software that they love), but know that Matterhorn makes a real difference for me and for the people I work with. Thank you!

**Comment by jtdaugherty** [comment]
Thanks for the praise, and for the request. We're glad Matterhorn is so useful to you!

I'm curious whether it changes anything if you can just hit `TAB` twice. Right now, if Matterhorn has multiple alternatives for a completion, it does fill in the first one (in this case, the "wrong Brittany"), but repeatedly hitting `TAB` cycles through the available options. Does that help?

**Comment by bcantrill** [comment]
Oh, wow -- yes, that's great!  Sorry for not having figured that out myself; that definitely helps!  Thank you!

**Comment by jtdaugherty** [comment]
Great!
