### ISSUE TITLE
Code blocks that exceed terminal width get truncated

### ISSUE THREAD

**Issue by al626** [matterhorn-chat/matterhorn#377]
Similar to #307, but for code blocks (things wrapped in ` or ```).

I don't think that wrapping is a good solution however, as it can often make code / logs / things generally displayed in code blocks more unreadable.

Something like the behaviour in `less -S` would be a good solution; where code is not wrapped but bits that are cut off can be viewed by scrolling with the arrow keys (or vim bindings for the arrow keys).

I'm using 40400.0.0

**Comment by jtdaugherty** [comment]
Thanks for the report - we'll give this some thought.

**Comment by jtdaugherty** [comment]
This is now implemented in `develop`. The details are in the commit message for 
https://github.com/matterhorn-chat/matterhorn/commit/434e1049623483d050d380174b16210c58fb8f05 and this will go out in the next release. Thanks!
