### ISSUE TITLE
unsafeUseUnauthenticatedConnection does not work with connection pooling

### ISSUE THREAD

**Issue by kellymclaughlin** [matterhorn-chat/matterhorn#381]
Setting `unsafeUseUnauthenticatedConnection` to `False` no longer works because the connection pool hard codes the `useTLS` argument to `True` [here](https://github.com/matterhorn-chat/mattermost-api/blob/master/src/Network/Mattermost/Types.hs#L85).

**Comment by jtdaugherty** [comment]
This is now fixed in https://github.com/matterhorn-chat/mattermost-api/commit/febc4fbbaa3dc4aad72b836480528b33486b1d1f.
