### ISSUE TITLE
Nickname tab completion does not work in matterhorn-40800.0.1

### ISSUE THREAD

**Issue by kellymclaughlin** [matterhorn-chat/matterhorn#382]
It looks like this is intended to still work, but only completion for normal user names works.

**Comment by jtdaugherty** [comment]
Can you provide more details on what you expect the behavior to be, and what you see instead?

**Comment by kellymclaughlin** [comment]
Sure thing. My model for it is just based on how the default mattermost client works for this. If you hit `@` and start typing a nickname and then hit tab it'll show you completions for user names that match the associated nicknames.

For example, say we have a user name of `UncleFester` with a nickname of `fester`. If I type `@f` and hit tab the client will show me a list of completions that includes `UncleFester - (fester)`.  So basically you can tab complete based on the user name or the nickname, but it ends up that only the user name is used in the message display. So it's strictly for the completion.

**Comment by jtdaugherty** [comment]
With the exception of how the alternatives are rendered (`UncleFester - (fester)`), your description matches Matterhorn's behavior (or, at least, the intended behavior). Is the presentation difference what you're commenting on here? Or is there a bigger behavioral difference that you're seeing?

**Comment by kellymclaughlin** [comment]
What I see is that when i try a nickname tab completion I do not get a completion list at all, but trying a tab completion for a username does give me a completion list. I can probably dig into this more and get more info about it if that's helpful, I just haven't had a chance to do so yet. Thanks.

**Comment by jtdaugherty** [comment]
Interesting. Can you verify that the server is configured to display nicknames, and can you also verify that the client has them, e.g., by looking at the `/members` window? Here's what I see on my development server where nicknames are enabled:
 * The test user accounts `jtd5`, `jtd6`, and `jtd8` have nicknames `nickname`, `nickname2`, and `nickname3`, respectively.
 * If I enter `n<TAB>`, the completion list appears with the alternatives `nickname`, `nickname2`, and `nickname3`, but the `n` input I entered is immediately replaced by the username of the first alternative, `jtd5`.
 * Subsequent `TAB` keypresses replace the `jtd5` editor input with the username of each successive alternative, while the alternative list cycles through the corresponding nicknames.

**Comment by kellymclaughlin** [comment]
Ok, I understand now. I was trying to use `@` for the nickname completion which doesn't do anything, but the completion using the bare nickname prefix does work. Sorry for the confusion and thanks for looking into it!

**Comment by jtdaugherty** [comment]
I've just updated the completion logic to support the kind of completion you were attempting: https://github.com/matterhorn-chat/matterhorn/commit/610ca84b06141b6d0e5662afb43401f36c02bb2a

**Comment by jtdaugherty** [comment]
Thanks!
