### ISSUE TITLE
Channel switching to user channels with nicknames not working in 40800.0.2

### ISSUE THREAD

**Issue by kellymclaughlin** [matterhorn-chat/matterhorn#384]
I updated from 40800.0.0 to 40800.0.2 and channel switching to DM channels for users with nicknames no longer works. The user's nickname shows when completing the name in the channel switching dialog, but when you select the channel the error `No such user "@Bob"` results. If I downgrade back to 40800.0.0 it works again.

**Comment by kellymclaughlin** [comment]
Yep, the channel selection mode with `C-g` is what I meant. And a fix is not urgent for me, 40800.0.0 works fine for me so I'm not in a hurry for a fix or anything. Thanks!!

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks for the report!
