### ISSUE TITLE
Improve WebSocket error/exception handling

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#385]
Need to add logging for WebSocket errors/exceptions. It may also be advisable to have more specific handling of exceptions.

Specifically regarding `handleError` in src/Connection.hs, but possibly elsewhere as well.

**Comment by jtdaugherty** [comment]
In https://github.com/matterhorn-chat/matterhorn/commit/f55e62a5e57e787d936e74f03ded2f55d301277a I've added logging of websocket exceptions and timeouts using the new logging infrastructure. I'm not sure what more specific exceptions we can log, so I'm going to consider this done and we can re-open if we determine what specific exceptions should be called out.
