### ISSUE TITLE
Some double-width characters cause rendering problems

### ISSUE THREAD

**Issue by jclulow** [matterhorn-chat/matterhorn#389]
We have a user who insists on having a double wide character in his nickname.  Now that Matterhorn is able to render nicknames (which is awesome!) I'm having a rendering issue in both `xterm` and `gnome-terminal`:

![displace](https://user-images.githubusercontent.com/304070/39274518-0f84093a-4897-11e8-8cb2-8e8d2e6954a1.png)

![displace2](https://user-images.githubusercontent.com/304070/39274571-454d40cc-4897-11e8-8a9a-95d4b753ee29.png)

I think this might be related to the issues discussed in #125?

**Comment by jtdaugherty** [comment]
Yes, it's definitely related to #125. Unfortunately supporting this is not possible right now, for a whole host of reasons (some of which are detailed at https://github.com/jtdaugherty/vty/issues/115). This is also a problem for various smiley emoji, many of which are two-column characters.

At best I can imagine Matterhorn *replacing* such characters with a placeholder that we can render (such as `?`) but I'm not sure we can do much more than that, at least not soon.

**Comment by jclulow** [comment]
I suspect replacing the characters with a `?` or `*` (or similar) would be a welcome stopgap solution!

**Comment by jtdaugherty** [comment]
@kquick let's chat about this in the next day or two when you have time.

**Comment by jtdaugherty** [comment]
I wanted to leave this open as an indication that we have acknowledged the problem, but since there is not a solution in sight, I'm going to close it. In the mean time there is at least an FAQ entry about this.
