### ISSUE TITLE
Gaps get rendered

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#392]
If I go to any channel and scroll up until there are no more messages, I see:
```
[16:01] Additional messages???
```
I'm making this ticket as a reminder to finish implementing gap handling in this case, where IIRC we were going to use this gap entry as the place to render what we currently display, `<< Press C-b to load more messages >>`.

**Comment by jtdaugherty** [comment]
@kquick I think this is resolved, isn't it? I don't see that behavior anymore due to the work you did late last year.

**Comment by kquick** [comment]
Not sure why I removed my assignment without closing this, but no, I don't see this happening in recent Matterhorn and there don't seem to be any remaining gap TODO's at this point.
