### ISSUE TITLE
View Message reply indefinite loading of previous messages

### ISSUE THREAD

**Issue by SamuelLongchamps** [matterhorn-chat/matterhorn#395]
When I view a message that is a reply to a previous message, I expect to see the conversation in the View Message modal view, only the message I selected is printed and there is a `[loading...]` on top that remains there.

I cannot say if this is not yet implemented or a bug.

**Comment by jtdaugherty** [comment]
Thanks for the report! There are two things going on here:
* the `[loading...]` is not expected and is a bug, and will be fixed. I'll close this ticket in favor of a more specific issue for this misbehavior.
* message view mode is intended to only show the specified message to allow viewing messages that get truncated when they have code blocks. I'll create another ticket for implementing a "view conversation" mode; we don't have one yet.

**Comment by SamuelLongchamps** [comment]
Great stuff! A conversation mode will definitely help reading long conversations, it can get confusing when many are taking place in one channel.

Thank you!

**Comment by jtdaugherty** [comment]
Yeah, we definitely want this to get done at some point. In general our goal with Matterhorn is to match the web client in terms of functionality as often as possible, and as closely as possible, within the confines of good terminal application design. :)
