### ISSUE TITLE
Support conversations

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#396]
We need a UI to show the entire history of a message reply tree. As per other discussions on the wiki, it would be great if this were more than just viewing conversations; if participation was supported, that would be at least as good as the feature provided by the web client. (Was: #395)

**Comment by EugenMayer** [comment]
I just wanted to add my 5 cents to it - this is one of the very critical features and to be honest it seems like this "thread view" devides a lot of

**Comment by jtdaugherty** [comment]
> Considering that matterhorn already has a "message view" i cannot really understand:
>
> why there is anything complex to decide
> or anything big to implement

The answer is: it totally depends on how far you want to go with the idea of adding some kind of threading support.

If all you want to do is *view* threads, yes, that's easy. We could add that in short order.

Why haven't we done that? Because we anticipate that as soon as you can view a thread, you will want to do all kinds of other things like reply to the messages, select them, etc. We think that only being able to view a thread would be a disappointing feature, and we think it would be likely to generate a lot of user requests to us *for things that we already know you're going to want*. So, with that in mind, we set out to think about ways to add a better threading feature than the web client provides.

As for the question of why that's a complicated thing to add, well, this is software engineering, after all. If you want to hack something in, it's simple today but gets complicated in the future when you have to pay for the hack. If you want to do it "right" today, it takes time and thought. We've put in dozens of hours of programming and design and discussion on this issue so far. Some of that effort won't be visible to users outside the development team. The wiki page I linked to is the result of the design discussions, and the prototype branch is the result of the programming effort.

I completely agree with you that this is an important thing to support, and we want to do a good job at supporting it without making the codebase a mess or without implementing half-baked features that we tear out later because we didn't think things through. We have limited resources on the development team so I hope you'll understand that some patience is needed.

**Comment by EugenMayer** [comment]
Thank you very much for your reply - very valuable! I can relate to your POV entirely - and about my patience. I payed not a single cent for using your great implementation. My patience is either "infinite" or ... i help implementing it - nothing else :)

**Comment by jtdaugherty** [comment]
This ticket has been labeled `shelved` due to lack of time and/or urgency to work on this, although it may still be worthwhile to address in the long run. Anyone wanting to contribute by working on this ticket can re-open.

**Comment by 3v1n0** [comment]
No update here?

It would be very nice that when you do `view` on a single message part of a conversation you would find in such popup the whole conversation as well...

**Comment by jtdaugherty** [comment]
@3v1n0 Please see my slightly long comment above from Oct 2019 for some context on why we haven't implemented conversation view support. In short: we spent a lot of time prototyping a way to support conversations, but the work required a lot of hacks that we couldn't support long-term, so rather than put them in, we decided to move on to other things. At present I am the only person with time to maintain the codebase and that time is very limited, so any changes requiring extensive overhauls are difficult for me to get to. Supporting conversation viewing would not be a ton of effort, but it would be a short leap from viewing them to wanting to also participate in them, and that latter bit will take a lot more work.

**Comment by codevion** [comment]
@jtdaugherty that's valid but just in my use of the app, interspersed threads are pretty hard to understand without any sort of view thing so even a thread view function would be valuable to some of us. We can select and reply o the messages outside of the thread view.

**Comment by jtdaugherty** [comment]
Thanks @codevion, that's helpful to know!

**Comment by jtdaugherty** [comment]
I've gotten a working thread window implemented on the `experimental/thread-window` branch for anyone who is interested to try it out while it's in testing.
