### ISSUE TITLE
Using emacs eshell to start matterhorn

### ISSUE THREAD

**Issue by nils-schween** [matterhorn-chat/matterhorn#398]
risking a rather dump question: does anyone know how start matterhorn from within emacs using eshell. I always get the following error: 
matterhorn: user error (Terminal does not define required capability "cup")

thanks for any hints,
nils

**Comment by jtdaugherty** [comment]
You could try forcing TERM to “xterm”, but in general the terminal modes in Emacs are incomplete enough that running applications like Matterhorn will not be possible. You’re going to have better results with full-blown emulators like rxvt, xterm, iTerm2, Konsole, gnome-terminal, etc.
