### ISSUE TITLE
Support for  5.0.0 of Mattermost?

### ISSUE THREAD

**Issue by cdrage** [matterhorn-chat/matterhorn#403]
Seems like I'm getting a "Unable to connect to the network" error.

I'm not too how to diagnose this. The public channel is http://chat.openshift.io if you wish to test against it!

I'm unable to get any logs (is there a command within the GUI to output the logs or something?

**Comment by cdrage** [comment]
Nevermind! I see it only supports 4.0 so far (I read the versioning scheme)

**Comment by jtdaugherty** [comment]
I was able to connect to your server using Matterhorn `40901.0.0`. (The version number doesn't necessarily mean it won't support newer versions of the server - just that it likely won't support older ones.) Which version are you running? When do you get the error message? At startup, or later, after the client has connected?

**Comment by jtdaugherty** [comment]
On the topic of logging, as of version `40901.0.0` there are some logging commands that might be useful in your situation:
* `/log-snapshot`
* `/log-start`

See `/help` for more details.

**Comment by cdrage** [comment]
@jtdaugherty Only problem is that I can't actually do `/log-snapshot` and the other command since it's stuck on the log-in screen :(

**Comment by jtdaugherty** [comment]
Can you provide your configuration, sanitized of sensitive information?

**Comment by cdrage** [comment]
@jtdaugherty Fixed! Looks like (for some reason!) I had to install ca-certificates. Did you happen to have a recent change / commit that verified certs?

**Comment by jtdaugherty** [comment]
Matterhorn has always verified the server's certificate.

**Comment by jtdaugherty** [comment]
I'm glad you got it figured out!
