### ISSUE TITLE
Investigate showing direct reply parent messages

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#404]
When a message B replies to A, and C replies to B, the message C is displayed as being in reply to A. This is a consequence of internal book-keeping of reply relationships, but I don't think it's necessary. Unless you understand the internals (which you shouldn't have to), this is a confusing behavior because replying to a message may not actually result in the *appearance* of having replied to it.

This ticket is about looking into the technical details of changing which message we display in reply situations, since (IIRC) we have the data but just don't use it this way. If we do make this change, we need to also be clear about it in the release notes.

One consideration -- and IIRC this is why we did it the current way -- is that changing this display convention means that it will no longer be possible to see at a glance that both B and C are part of the same conversation. This could be ameliorated by a "conversation" viewing feature similar to the web client, but we don't have that yet.

CC @david-christiansen

**Comment by david-christiansen** [comment]
What if there were a keybinding to jump to the message that I'm replying to? Repeated use of this would make it fairly straightforward to discover the root of a reply chain, which might be less work to implement than the conversation view.

**Comment by jtdaugherty** [comment]
We could do that, but I would still want to implement the conversation view for feature parity with the web client, also because participating in conversations is easier when your input box is scoped to implicitly reply to the conversation's latest message, as is the case in the web client's UI.

**Comment by jtdaugherty** [comment]
Update from the server developers: due to the fact that 1) the post creation API does not allow us to set a parent post ID and 2) the parent ID field is a deprecated field and is effectively always equal to the root post ID, we cannot improve this behavior. Instead, I'm going to leave it as-is and add an FAQ entry about it and close this in favor of #396.
