### ISSUE TITLE
Force disconnect/connect

### ISSUE THREAD

**Issue by acw** [matterhorn-chat/matterhorn#405]
There have been occasions in which I sleep my laptop, or change networks, in which I know all of my network connections have been hosed. In those situations, waiting for matterhorn to timeout (or tricking it into discovering that everything is hooped) is a bit of a pain.

What would be lovely would be if I could manually force matterhorn to disconnect and destroy all its current connections, and then manually get it to try to reconnect. This would also help me in diagnosing where my error is when I'm having trouble connecting matterhorn to the server.

**Comment by jtdaugherty** [comment]
Fixed in `develop`.
