### ISSUE TITLE
Mark private channels as such in the channel list

### ISSUE THREAD

**Issue by rightfold** [matterhorn-chat/matterhorn#411]
In the channel list, all channels are prefixed with a tilde. But when opening a private channel, in the channel header the channel is prefixed with a question mark. Would it make sense to also put this question mark in front of private channels in the channel list? Or perhaps make a separate list with private channels.

**Comment by jtdaugherty** [comment]
Thanks for the report! As of 4ab8914c152cfda287425cc2db8db5f2c4feb656:

* Private channels still appear in the main channel list with the normal sigil (`~`)
* Private channel headers no longer have any sigil at all
* Private channels are marked with "(Private)" in their channel headers
* Private channels are no longer included in tab-completion (to match the web client behavior)
