### ISSUE TITLE
Matterhorn doesn't deal well with verbatim text in hyperlinks

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#418]
This:
```
[`test`](http://www.google.com)
```
does not hyperlink when terminal hyperlinking is enabled.

CC @david-christiansen

**Comment by jtdaugherty** [comment]
Note: Matterhorn still does the best it can with the coloring, e.g.,
```
[this is `verbatim`](...)
```
will still color the "verbatim" portion as one would expect and similarly for the rest of the link text. However, when "verbatim" is all there is, there is no visual evidence of a link (if hyperlinking is *not* enabled).

**Comment by david-christiansen** [comment]
This seems to also be an issue with any formatting, like bold.

**Comment by jtdaugherty** [comment]
This turns out to be because the link processing in the Markdown code only knows how to handle links with label nodes containing only a single string (whereas this one has a more complex structure).

**Comment by jtdaugherty** [comment]
Latest development: this boils down to Brick's `withDefAttr` not quite behaving as we would expect in this situation where a style (like the hyperlinking) is in effect.

**Comment by jtdaugherty** [comment]
The solution was to use Brick's `hyperlink` combinator, together with letting our `Fragment` type carry around nontrivial hyperlink label ASTs so we can preserve formatting information even when something is hyperlinked.
