### ISSUE TITLE
Binary packaging for RHEL 

### ISSUE THREAD

**Issue by chrysophylax** [matterhorn-chat/matterhorn#444]
Hi everyone,

I'd like to make aware the interest in a version of matterhorn-chat that works on RHEL/Centos 7.x.

I tried to build the whole thing myself a while ago but spent a long time just getting a haskell environment running as I've little to nil experience in this ecosystem.

**Comment by jtdaugherty** [comment]
Upon further investigation I found that it's possible to make CentOS 7 releases by using a particular build of GHC, so I've reopened this.

**Comment by jtdaugherty** [comment]
@chrysophylax would you be willing to try out this release?

https://github.com/matterhorn-chat/matterhorn/releases/download/50200.0.0/matterhorn-50200.0.0-CentOS-x86_64.tar.bz2

**Comment by chrysophylax** [comment]
Sure. I can try it out in a few hours! Thanks.

**Comment by chrysophylax** [comment]
![image](https://user-images.githubusercontent.com/10576351/49478618-90654d00-f820-11e8-9e93-95fadb9f8e1a.png)

It works fine so far on RHEL 7.6 Maipo! (It should work fine on any CentOS-derived equivalent as well then)

Thanks a lot!

**Comment by jtdaugherty** [comment]
Thanks for trying it out! That's great news. I'll add CentOS to our release builds going forward.

**Comment by jtdaugherty** [comment]
Since it's relevant to this ticket, I thought I'd mention that today's big release has a CentOS binary:

https://twitter.com/matterhorn_chat/status/1070390741828943872
