### ISSUE TITLE
Factor per-channel state out of global state

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#445]
The editing state (e.g. multi-line or single-line) should be maintained per-channel.

Current behavior: the edit mode is global.  This means that selecting multi-line edit mode in a channel, then switching to another channel without completing the message and sending it will result in multi-line mode in the new channel, and correspondingly submitting the message in that channel and returning to the first channel will be in the single-line "submit?" status.

Desired behavior: each channel has an independently maintained editing state that remains unchanged if a different channel(s) is visited and then this channel is re-selected during the editing process.

**Comment by jtdaugherty** [comment]
Other things that need to be moved into channel state having to do with the editor:
* Input history (now a global map)
* Input history position (now a global map)
* Most recent unsubmitted input (now a global map)

**Comment by jtdaugherty** [comment]
Multi/single-line editor state is now per-channel as per the aforementioned commit. That change provides a home for other per-channel state.

**Comment by jtdaugherty** [comment]
This ticket should also cover attachment state (relevant to #485).

**Comment by jtdaugherty** [comment]
Both the input history position and the "last input" global maps have now been moved into the per-channel state. The only other thing mentioned in this ticket, the input history itself, could be moved also, but I'm not sure it's worth the trouble. Right now it is all managed under one structure called `InputHistory`, and the main benefit of that is that that structure has a file storage implementation that we use at startup/shutdown. If we still used that but moved the per-channel history into the channel state, we'd just have to rebuild the `InputHistory` at shutdown (and decompose it at startup) which would be messy for very little benefit.

(Next step: review with @kquick)

**Comment by jtdaugherty** [comment]
This is now reviewed with @kquick and merged to `develop`.
