### ISSUE TITLE
Disconnection messages do not always get cleaned up

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#459]
To reproduce:
* Get on the VPN.
* Start matterhorn.
* Disconnect the VPN.
* After the websocket ping times out, the current channel gets a message saying `Disconnected. Will refresh when connected.`
* After a short time Matterhorn successfully reconnects its websocket but the aforementioned message remains.

**Comment by jtdaugherty** [comment]
A related change that might be enough to resolve this: d653ad5e051c3e305f6d421bf3dcaaeaac7b16e6

**Comment by jtdaugherty** [comment]
A related change that might be enough to resolve this: d653ad5e051c3e305f6d421bf3dcaaeaac7b16e6

**Comment by kquick** [comment]
Recent testing fails to reproduce this issue, so I'm closing it as fixed by subsequent development.  Please re-open with additional reproduction details if this re-occurs.
