### ISSUE TITLE
Feature request: text logging

### ISSUE THREAD

**Issue by collegenetjacob** [matterhorn-chat/matterhorn#469]
Coming from an IRC background one of the things I miss most when using Mattermost is client side logging.  Actually there would be many more things but Matterhorn really helps a huge amount.  However, it would be great if Matterhorn could be configured to log all the conversations to which I am party into a directory with one text file per conversation like many IRC clients can.

Ideally it would not go back and modify the past, either.  (This should make the feature easier to implement, too.)  When a user edits or deletes a message, a new log line marked edit or delete should be written instead.  Many of our users find it convenient to have edit and delete enabled, so we have allowed it.  But we also need to know f.e. passwords a user accidentally typed into a MM conversation (so we can add them to our cracking dictionary to force the user not to use that password anymore).  Just because they deleted it later after 12 others saw it doesn't change the situation.  It is inconvenient for us to have to query the MM database to get this kind of information.

Again, thanks (from about four blocks away in Portland) for such an incredibly useful tool.  I didn't see a feature requests for logging yet and I'm not sure if/when I might have time to try and do it so for now I'll hope one of you might.

**Comment by jtdaugherty** [comment]
For what it's worth: https://forum.mattermost.org/t/conversation-logs/358

**Comment by collegenetjacob** [comment]
Yes; I think their intent is to keep configurable logging in the E20 product (or whatever they're calling it these days); we are using E10 (same parenthetical).  I think they would see this as an Enterprise feature if written at the server level.  Dumping the database is unpleasant (and a silly answer).  As for responsiveness of the Mattermost team, I would not call it great.  They respond quickly but they don't necessarily provide a resolution quickly.  We may simply not be a large enough customer.

To an extent I agree with your comment about client logging being sub-par for many use cases, but on the other hand many of us are quite accustomed to it historically.  I have never seen a complaint before that IRC servers should make global transcripts available to users or administrators, probably because most people found client logging to be just fine for their needs.  Combined with fallback to dumping the database, it would be a fine solution from our perspective.

Otherwise I suppose I will end up having one of our developers write some quick hack to connect to Mattermost, subscribe to a bunch of channels, and dump text logs that way.  Which is part of why it seems to me to be silly not to just have the client do it.  If we take this route, I doubt it'll get submitted anywhere, and then we will have to maintain it indefinitely ourselves.

**Comment by jtdaugherty** [comment]
Having thought about this some more, we must decline.

I'm sorry to hear that some of the other available approaches aren't a good fit for you, and I definitely understand that allocating developer time to take care of this can be costly and raises maintenance questions. For what it's worth, if any of your developers know Haskell, they can use our `mattermost-api` package to take care of connecting to Mattermost and getting notified of events, posts, etc. If that happens, we would be very interested to see how that goes and to get feedback or patches to improve that library.

**Comment by jtdaugherty** [comment]
No, since I don’t think Matterhorn is a good place for the functionality. However, I would be very interested in changes to the API library that make it easier to use to write bots, and I would also be interested in bot infrastructure in general.
