### ISSUE TITLE
Old-school /msg variant

### ISSUE THREAD

**Issue by acw** [matterhorn-chat/matterhorn#471]
So, I spent more time than I care to admit figuring out how `/msg` worked, because I had been overtrained by IRC to expect it to work differently. In particular, my brain is trained to believe that the command is going to be either:
```
/msg acw Hello, me!
```
or, possibly, given other matterhorn standards:
```
/msg @acw Hello, me!
```
But instead, I got a bunch of errors that were not tremendously informative:
```
error running command /msg: Unexpected arguments '...`
```
The current implementation makes sense for a no-argument, "open an empty / pre-existing window with another user" option, but I'd love one that just took everything on the command line. Even better, three variants:

 1. `/msg`: Current behavior
 1. `/msg [user]`: Switch to a new/existing channel with `[user]`
 1. `/msg [user] [msg]`: As above, but also send the given message as the next message.

**Comment by jtdaugherty** [comment]
Variant (2) is now implemented in `develop`.

**Comment by acw** [comment]
Awesome, thanks!

**Comment by jtdaugherty** [comment]
Variant (3) is now supported. Please test!
