### ISSUE TITLE
Support for SAML authentication

### ISSUE THREAD

**Issue by thatarchguy** [matterhorn-chat/matterhorn#473]
When signing into a server that requires SAML as the sign-in method, I am faced with this error:
```
Error: MattermostError {
  mattermostErrorId = "api.user.login.use_auth_service.app_error",
  mattermostErrorMessage = "Please sign in using SAML",
  mattermostErrorRequestId = "[...]",
  mattermostErrorStatusCode = 400,
  mattermostErrorIsOAuth = False} 
```
It seems signing in with SSO providers is not supported. It would be greatly appreciated if this could be prioritized.

**Comment by jtdaugherty** [comment]
That's right - SAML authentication is not supported at the moment.

SAML support isn't our roadmap, but we'd be willing to work with contributors who are interested in helping add support for it.

**Comment by jtdaugherty** [comment]
Since this ticket is not on our roadmap and needs more investigation and discussion before any concrete approach can be considered, I'm closing this. If anyone is interested in pursuing it, please do so according to the guidelines at

https://github.com/matterhorn-chat/matterhorn/blob/master/PRACTICES.md#design

Thanks!

**Comment by dpb1** [comment]
For others that stumble onto this issue, I'd suggest also following #515 for a possible workaround for you depending on your needs.

**Comment by jtdaugherty** [comment]
Thanks, @dpb1!

**Comment by thatarchguy** [comment]
This is working for me. Thank you @dpb1

**Comment by felipemullen** [comment]
> For others that stumble onto this issue, I'd suggest also following #515 for a possible workaround for you depending on your needs.

For anyone else who doesn't want to read through the other issue, it's now in the documentation [right here](https://github.com/matterhorn-chat/matterhorn#token-cookie-authentication)
