### ISSUE TITLE
Allow changing the URL name of a channel

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#475]
A channel has both a "name" and a "displayName".  The `/rename` command (provided by the server) changes the latter.  The web client (and the API) allow either to be changed, so Matterhorn should provide this as well (either via a server command or a local command that makes an API call).

**Comment by jtdaugherty** [comment]
This is done as of 984fa20c737191c1ea20f1467b647147a583c886 but we just didn't get around to closing it.
