### ISSUE TITLE
Group channel creation failure

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#477]
Attempting to create a group channel (via `/group-msg @user1 @user2 ...`) runs but appears to do nothing.  The channel does not show up in Matterhorn.  Running the same command again appears to work the second time, showing the new group channel.  The logs seem to indicate that the channel is created by the first command but that the actions taken after the server response are incomplete and don't correctly setup and display the channel locally.  The second command causes those actions to be taken and the channel is displayed.

Verify that this fix does not re-introduce the bugs fixed in #327 or #434.

Also note that the channel does not show up for the other members until a message is posted to that channel.

**Comment by jtdaugherty** [comment]
I'm having trouble reproducing this. I tried two different tests:
* Run `/group-msg` for users that I *have* chatted with in the past. The behavior is as expected: the preexisting DM channel appears in the sidebar and I move to it.
* Run `/group-msg` for users that I have *not* chatted with in the past. The behavior here is also as expected.

Maybe I'm not testing the same conditions as the ones that were in effect for this report?

**Comment by kquick** [comment]
Verified that this is reproducible:

*  Entering `/group-msg user ...` for a set of users that there does not already exist a group channel will create the channel in the background, but there will be no visible change.  
* Re-entering the same command will switch to the group channel because it now exists.
* Entering the above for a group channel that already exists switches to that group as expected.

**Comment by kquick** [comment]
Fixed (currently on develop) via PR #523
