### ISSUE TITLE
Show the direct link to an uploaded image

### ISSUE THREAD

**Issue by brodycas3** [matterhorn-chat/matterhorn#480]
Do you think that you could show the direct link to an uploaded image? Currently there is no way to view images uploaded directly to mattermost.

**Comment by jtdaugherty** [comment]
Is your concern that you want to view the actual link itself, or you want to view the image and don't care necessarily about its URL?

**Comment by brodycas3** [comment]
My concern is the URL as images only show up like this, 
![image](https://user-images.githubusercontent.com/19770864/51054416-c679b780-15aa-11e9-9ec4-b38cf38931cd.png)

**Comment by jtdaugherty** [comment]
Have you tried `C-o` or `C-s`, then `o`, to open attachments? Have you configured a URL opening command?

**Comment by brodycas3** [comment]
well that's usefull to know
I have not configured an URL opening vommand

**Comment by jtdaugherty** [comment]
Okay, maybe give that a try. For attachments, that will download the attachment and then use the URL opening command to open it locally, which might e.g. open it in an image preview program. On Linux `xdg-open` might be a good choice and will usually do the right thing. On OS X, `open` is the thing to use.

**Comment by brodycas3** [comment]
Well thanks for the help

**Comment by jtdaugherty** [comment]
You're welcome!
