### ISSUE TITLE
Add UI hint for attachment removal binding

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#485]
There is no obvious way to remove an attachment (e.g. via Ctrl-X) if the user changes their mind.  We should add documentation on how to remove them to the "Attachments: N" message.

In addition, the attachments appear to be associated with the message editing line and not with the current channel.  This can result in unintended consequences:
   * Start typing a message in a direct channel
   * Add an attachment
   * Use ctrl-n or ctrl-p to move to a different channel

Note that the edit text is cleared (and restored when returning to the original channel) but the attachments indication is always present, making it possible to send the attachment with the wrong message and to the wrong channel.

**Comment by jtdaugherty** [comment]
The second part of this is now covered in #445.

**Comment by jtdaugherty** [comment]
The `Attachments: N` message should just mention the binding to re-open the attachment management UI, since that's where the attachments are removed from.

**Comment by jtdaugherty** [comment]
@kquick take a look at the patch I pushed for this. If that works for you, and if you're okay with covering the second part of this issue in #445, then I think we can close this.

**Comment by jtdaugherty** [comment]
@kquick looks like we might still be waiting on your thoughts on the latest change on this ticket. If I recall, I think I remember you saying recently that you were going to take a look. Did you have a chance?

**Comment by kquick** [comment]
Yes I had looked at it but had forgotten to update this ticket.  I like the hint change and so we can close this and address the remainder in #445..
