### ISSUE TITLE
HTTPResponseException "Server returned unexpected (4,2,9) response"

### ISSUE THREAD

**Issue by rruizt** [matterhorn-chat/matterhorn#486]
Mattermost version: 5.7.1
Matterhorn version:  50200.1.2

While switching between different conversations I get this error in the conversation itself

```
An unexpected error has occurred! The exception encountered was:
HTTPResponseException "Server returned unexpected (4,2,9) response"
Please report this error at https://github.com/matterhorn-chat/matterhorn/issues
```

Everything works fine after that, but sometimes this error is shown 5 or 6 times in a row hiding the previous conversation.

Thank you for your work!

**Comment by jtdaugherty** [comment]
HTTP 429 is the response that Mattermost returns when too many API requests are submitted. So perhaps I'll take a guess: you're on a fast connection to your server and you switched conversations very rapidly long enough to trigger this. Is that right?

**Comment by rruizt** [comment]
Yes, you're right.

I just tested keeping pressed CTRL+P to navigate between conversations faster and this error shows way more often in the conversations. I don't have to do it long enough though, maybe a couple of seconds is enough to start getting the errors.

I do have a fast connection but the server is not in the same LAN.

**Comment by jtdaugherty** [comment]
Unfortunately this is not something Matterhorn can have much control over, and it is possible to trigger this problem with other clients, too. However, you might consider talking to your server administrator to consider changing your API request rate limit settings:

https://docs.mattermost.com/administration/config-settings.html#rate-limiting

**Comment by rruizt** [comment]
I see, I will talk to the server admin then.

Thank you for the information!

**Comment by jtdaugherty** [comment]
You're welcome. Thanks for the report!

**Comment by rruizt** [comment]
I can confirm that the suggested solution works. No more exceptions around :+1:

**Comment by jtdaugherty** [comment]
Great!
