### ISSUE TITLE
Improve keyboard shortcut documentation

### ISSUE THREAD

**Issue by renestalder** [matterhorn-chat/matterhorn#489]
Add a list to the readme with all the shortcuts listed in a table or list. Makes it easier to get used to them than searching inside the readme text.

Example:  
https://github.com/erroneousboat/slack-term#default-key-mapping

**Comment by jtdaugherty** [comment]
Thanks for the suggestion. Have you seen the keybinding list within the program obtained with `/help keybindings`?

**Comment by jtdaugherty** [comment]
Okay, thanks for the feedback!

**Comment by jtdaugherty** [comment]
On the `develop` branch (soon to be released) we now have command-line arguments `-k` and `-K` to dump plaintext and Markdown keybinding tables, respectively. @kquick will also make the `README` link to a stored version of that information so the content is comprehensive. That content may replace what's in the `README` currently.

https://github.com/matterhorn-chat/matterhorn/commit/e242059d2de9a862c2125554548a4ac86d6d1e5f

**Comment by jtdaugherty** [comment]
Another update: this is now available at

https://github.com/matterhorn-chat/matterhorn/blob/develop/keybindings.md

and will be available on `master` once the current release work is done.

Thanks again for the request!

**Comment by renestalder** [comment]
@jtdaugherty This is perfect. Thank you so much! Give me that link to a donation feature and I support you guys when I can.

**Comment by jtdaugherty** [comment]
That's very kind. Right now, [Galois, Inc.](https://galois.com), our employer, funds the development of Matterhorn, and various contributors from the community have provided fixes, implemented new features, and performed testing. Submitting patches and filing issues are the best ways you can help us out!
