### ISSUE TITLE
/msg sometimes refuses to work

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#497]
Behavior:
* Run `/msg @...` for some user with whom you've never chatted
* Observed behavior: Matterhorn reports "No such channel: @..."
* Expected behavior: Matterhorn creates and switches to a DM channel.

**Comment by kquick** [comment]
Possibly similar to #477 ?
It has been working for me though, which is the inverse of #477, which I observed but worked for you.

**Comment by jtdaugherty** [comment]
It works for me sometimes, though - that's the weird thing. On `mh-dev` I just found it to work for one new DM channel but not another. I think I've found the issue, but I need to confirm.

**Comment by jtdaugherty** [comment]
The issue here turns out to be that the server API does *not* permit a username sigil (`@`), and we are passing that to it anyway. The reason this appears to "sometimes" not work is because in the cases where it works, it's because it never made an API call at all; it hit the local application data and found the user, thus skipping the API call. Only when it makes the API call will it fail, and it will *always* fail.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
