### ISSUE TITLE
New DM channels show "Fetching messages" indefinitely

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#498]
To reproduce:
* Run `/msg @...` for a user with whom you have never chatted (i.e. for which no DM channel already exists)
* Matterhorn creates the channel and switches to it.
* Observed behavior: the channel shows "--Fetching messages--" indefinitely, even after new messages are posted to the channel. The fetching indicator can only be banished by switching to some other channel and then returning to the DM channel.
* Expected behavior: the channel might show the fetching indicator briefly and then remove it.

**Comment by kquick** [comment]
Fixed in https://github.com/matterhorn-chat/matterhorn/pull/521
