### ISSUE TITLE
Error: HTTPResponseException "Server returned unexpected (4,0,4) response"

### ISSUE THREAD

**Issue by hawaiik** [matterhorn-chat/matterhorn#502]

**Comment by hawaiik** [comment]
I get this error on darwin binary release https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.3.1 server version is 5.9.0. Found an earlier issue https://github.com/matterhorn-chat/matterhorn/issues/399 which says its a problem of client  not matching the server version, but as this is already the latest release?

**Comment by hawaiik** [comment]
Just wanted to try matterhorn for the first time and this happens when I try to login to the server. Will try to provide the log as quick as possible.

**Comment by jtdaugherty** [comment]
If it happens that early, logging might not reveal much, but we'll see. Does your server support username/password authentication?

**Comment by hawaiik** [comment]
Yep.

**Comment by jtdaugherty** [comment]
Is your server public, so that we could try to see how the client interacts with it?

**Comment by jtdaugherty** [comment]
Also, are you using Matterhorn with a server that does not support HTTPS?

**Comment by jtdaugherty** [comment]
Another question: on what screen do you see this error? The login screen?

**Comment by hawaiik** [comment]
Nevermind, after some days we found a network issue.....closed

**Comment by jtdaugherty** [comment]
Okay, thanks for following up!
