### ISSUE TITLE
error logged when viewing link

### ISSUE THREAD

**Issue by sstark** [matterhorn-chat/matterhorn#503]
I am getting an error message each time I open a link using Ctrl-o<enter>. The error is:

`An error occurred when running "xdg-open"; see "/tmp/matterhorn-subprocess1957747793424238335.log" for details.`

The log output is:

```
Program: xdg-open
Arguments: ["https://thumbs.gfycat.com/HelplessResponsibleLark-size_restricted.gif"]
Exit code: ExitSuccess
Stdout:
Opening in existing browser session.

Stderr:


```
Despite that, the command works just fine and opens the browser as desired. My config.ini:

```
[mattermost]
urlOpenCommand = xdg-open
host = xxx.xxx.xxx
team = xxx
user = stark
passcmd = gopass show -o MPI/stark 
activityNotifyCommand = ~/.config/matterhorn/notify
themeCustomizationFile = theme.ini
```
If I run this command directly "xdg-open https://thumbs.gfycat.com/HelplessResponsibleLark-size_restricted.gif", it will return 0 and will not write anything to stderr.

I am using matterhorn-50200.3.1-ubuntu-18.04-bionic-x86_64.

**Comment by jtdaugherty** [comment]
Thank you for the report!

This is because the program emits to `stdout` despite exiting successfully. Matterhorn conservatively considers this an error because URL opening commands are not expected to produce any output and silencing that output on successful exit could lead to confusion.

The way to deal with this is to write an opener script that silences the `stdout` output as you see fit, and then use that script as your opener command.

**Comment by jtdaugherty** [comment]
In the commit mentioned above I also improved the log output somewhat so that this behavior is more evident.

**Comment by sstark** [comment]
I would never have thought of this. Thanks a lot for the clarification and improvement of the log output!

**Comment by sstark** [comment]
Sorry for re-opening this issue, but I can not get this to work. I have this in my config.ini now:

` urlOpenCommand = ~/.config/matterhorn/urlopen`

while urlopen looks like this:

```
 #!/bin/bash
 exec xdg-open "$@" >/dev/null
```

Now I get this error:

```
Program: ~/.config/matterhorn/urlopen
Arguments: ["https://atlas.is.localnet/jira/browse/ID-5583"]
Exit code: ExitFailure 1
Stdout:

Stderr:
~/.config/matterhorn/urlopen: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

I can call and use urlopen from the terminal just fine.

**Comment by jtdaugherty** [comment]
You probably have no /bin/bash. The solution to that is to use “/usr/bin/env bash” instead.

**Comment by jtdaugherty** [comment]
Oh - and the other issue may be the use of the tilde in the opener path. That will not get expanded.

**Comment by sstark** [comment]
The tilde was the problem. Also explains why notifications didn't work for me. Thanks again! The documentation suggests that the tilde expansion is an option in the config file. E. g. README.md tells us the default location for emojis is `~/.config/matterhorn/emoji.json`. I understand now that this expansion is simply not available in the config file and I drew a wrong conclusion.

**Comment by jtdaugherty** [comment]
Thanks - it's fair that if the README uses that notation, one would think to use it in the configuration file. (And we don't explicitly say you can't, either.) I'll make a ticket about supporting `~`.
