### ISSUE TITLE
Throttling errors (429) are not handled

### ISSUE THREAD

**Issue by cdevienne** [matterhorn-chat/matterhorn#504]
This morning I had these messages displayed in matterhorn, after playing with the /search command:
```
An unexpected error has occurred! The exception encountered was:
  HTTPResponseException "Server returned unexpected (4,2,9) response"
Please report this error at https://github.com/matterhorn-chat/matterhorn/issues
```

A quick look at the server logs showed this:
```
2019-06-04T09:49:56.515516625Z {"level":"error","ts":1559641796.5152774,"caller":"app/ratelimit.go:85","msg":"Denied due to throttling settings code=429 key=10.255.0.2"}
```

In such a case, I suggest that matterhorn waits for a second or so then reattempt, as the throttling setting on the server is a number of request per second.

**Comment by cdevienne** [comment]
I almost forgot: *Thank you* for doing matterhorn, it's amazing!

**Comment by jtdaugherty** [comment]
My conversation with Harrison:
```
  [12:28] jtdaugherty: @harrison for HTTP 429 rate limiting error
  responses from the server, what would you recommend for a retry
  strategy? I'm considering an approach where we make a series of retries
  waiting an increasing amount of time between each, up to some fixed
  number of retries, before giving up.

  [13:56] jtdaugherty: Another question is, what's the server's
  rate-limiting approach? Is it based on the frequency of the incoming
  requests, or the total count over a time interval?

  [13:56] jtdaugherty: And is it possible to get metadata about the
  server's rate-limiting configuration via the API?

  [14:20] harrison: I don't think we have a recommended retry strategy.                                                                             I think the rate limiting only covers a short period of time, so an
  increasing delay may not even be necessary

  [14:21] harrison: Based on the settings here, there's some limit for
  requests sent per second with additional allowance for a burst of
  requests, but I don't know how often a burst of requests is allowed to
  happen https://docs.mattermost.com/administration/config-settings.html#rate-limiting

  [14:23] harrison: It looks like we provide X-RateLimit-Limit,
  X-RateLimit-Remaining, and X-RateLimit-Reset headers with information
  about the rate limiting when it's enabled. Those must only be set when
  rate limiting is enabled since I'm not getting those headers on this
  server
```

**Comment by jtdaugherty** [comment]
At the time this was originally reported, @kquick and I had a pretty involved discussion in person about how to deal with this. But it looks like as long as we honor the headers mentioned above, the solution to dealing with this is trivial:

https://www.fullcontact.com/blog/2017/11/26/rate-limits/

**Comment by jtdaugherty** [comment]
(None of the approaches that Kevin and I discussed were straightforward.)

**Comment by jtdaugherty** [comment]
The approach I'll suggest is a simplification of the one in the post I linked to above:
* Make a request.
* Capture the rate limit headers in the response.
* If and only if the remaining call count is zero, block until the reset window ends.

Note that this does not bother to *throttle* requests in a rate limit window except for the last request. While it's true that smoother throttling would prevent bursty behavior, I don't think it will matter with Matterhorn in practice because so few users run into this. (Meaning, so few users have fast enough connections to their servers *and* use Matterhorn so heavily that they routinely or even occasionally run into rate limit violations.) Throttling before you need it just degrades service unnecessarily, which may be fine in that blog post's API user case but I don't think is okay in the case of Matterhorn.

**Comment by jtdaugherty** [comment]
This work is now underway. The initial change to merely raise rate limit exceptions from the API package is at

https://github.com/matterhorn-chat/mattermost-api/commit/ce7986dd6bbd7f4bc75b603985a190690aaf097d

**Comment by jtdaugherty** [comment]
Matterhorn's `feature/server-rate-limiting` branch now has basic support for rate limit exceptions. The new behavior is described in d40ab2fb3c0e1b58f09fe5d7157bde9b2d1778bf.

**Comment by jtdaugherty** [comment]
This work is now merged to `develop`.
