### ISSUE TITLE
Support 'j' and 'l' for up and down in 'Attach File' modal

### ISSUE THREAD

**Issue by cdevienne** [matterhorn-chat/matterhorn#506]
Going up and down in the Attach File can only be done with up and down keys, which is inconsistent with most of the matterhorn UI, where J and L can be used too.

**Comment by jtdaugherty** [comment]
Thanks for the report! This is now fixed in `develop`. The change adds support for the `select-down` and `select-up` key events in the attachment list, which by default have various bindings such as `j` and `k` respectively.
