### ISSUE TITLE
Follow symlinks in attachment browser

### ISSUE THREAD

**Issue by maxjoehnk** [matterhorn-chat/matterhorn#507]
I've symlinked my downloads folder to /tmp.
When I try to attach downloaded files the attachment browser just closes when selecting the downloads folder.
Either the default should be to follow symlinks or there should be a way to configure how symlinks get handled.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by maxjoehnk** [comment]
Looks like this could be fixed with a custom implementation of selectNonDirectories in `src/State/Attachments.hs`. I can create a PR if you want, not sure whether I know how to handle a symbolic link for a file.

**Comment by jtdaugherty** [comment]
We'd be delighted to review a patch if you're willing to write one. Thank you!

**Comment by jtdaugherty** [comment]
For what it's worth, if symlink browsing is going to work here, it *might* require changes to the `brick` file browser. But see what you can do, and if you run into issues just trying to make this work by modifying `matterhorn` alone, you/we can investigate what might need to be done there.

I suspect that the trick with navigating a symlink path is that any path components that are symlinks need to be tracked alongside the underlying physical path to make the navigation work the way the user will expect.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
