### ISSUE TITLE
Support creation of private channels

### ISSUE THREAD

**Issue by immindich** [matterhorn-chat/matterhorn#512]
There are two ways to create a private channel in the web client, both of which are currently unsupported in Matterhorn:

- Creating a new private channel

- Converting an existing public channel to a private channel

The [endpoint](https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1convert%2Fpost) for the second method does not seem to be in `mattermost-api`.

**Comment by jtdaugherty** [comment]
It appears that the second bullet you mentioned above is only possible if you're a team or system admin:

https://docs.mattermost.com/help/getting-started/organizing-conversations.html

Matterhorn doesn't support any features of that type and we don't have any plans to do so, so I think for the purposes of this ticket the first bullet is the most important thing to support.

**Comment by jtdaugherty** [comment]
This is now done on the `develop` branch.
