### ISSUE TITLE
Support authentication via Personal Access Token

### ISSUE THREAD

**Issue by setpill** [matterhorn-chat/matterhorn#515]
This would allow users to use matterhorn on mattermost instances where the only allowed auth method is gitlab auth by extracting the `MMAUTHTOKEN` from their mattermost instance cookie after logging in through the webinterface.

**Comment by setpill** [comment]
See also https://github.com/42wim/matterircd/issues/29

**Comment by Atlantic777** [comment]
I'm also interested in this feature and would like to contribute. I'll have a closer look at this. I need either the tokens or something more to properly support OAuth.

**Comment by jtdaugherty** [comment]
From my conversation today with Harrison Healey, one of the Mattermost developers:
```
[10:49] jtdaugherty: @harrison if we wanted to support Oauth Personal Access Tokens in Matterhorn, what's the user experience for getting those?
                     Is there a browser in the loop? Is it possible to get those from the user without a browser in the loop during
                     authentication?
[11:03] │ harrison: That's a good question. I'll have to look to see how you get those
[11:04] │ harrison: As long as they're enabled on the server, I assume it's just a simple API call to create one
[11:06] │ harrison: Yeah, there's just a simple API to create them as long as they're enabled on the server. Like here's the API to create one:
        │           https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1tokens%2Fpost
[11:07] │ harrison: Normally, the user can create them from the Security > Personal Access Tokens section of the account settings section of the
        │           web app when they're enabled and the user has permission to be able to do it
[11:52] │ jtdaugherty: Oh, well if there's a UI for it, then that's all we need - we'd just direct the user to that UI, and then they'd provide
        │              the access token to Matterhorn in an auth UI or configuration file.
[11:53] │ jtdaugherty: My main concern was whether we'd have to modify Matterhorn to participate in any OAuth protocol flow.
[11:53] │ jtdaugherty: But if it just amounts to a password we include in an auth request, then that's easy.
```

**Comment by jtdaugherty** [comment]
Also, thanks to all who are willing to help out with this! If you decide to contribute, please take a look at this and keep it in mind:

https://github.com/matterhorn-chat/matterhorn/blob/master/PRACTICES.md

In particular, before supporting this feature we need to work out (in the comments on this issue or on the wiki) the user experience that will be provided. For example, a starting-point proposal (assuming the above conversation about access tokens is right) is:

* Add an optional configuration setting, `personalAccessTokenFile`, whose value is the path to a text file containing the access token. When validating the configuration and loading the token, refuse to load the token unless the file pointed to by `personalAccessTokenFile` has any other mode than `0600`.
* Make the existing login credentials interface provide an additional field for a personal access token value using a password-style input field. When a token is provided (in the interface or via the configuration file), prefer that value over username/password when doing authentication.

**Comment by jtdaugherty** [comment]
I've updated the conversation quoting above as it has progressed. The key result is that personal access tokens can be used without any support for OAuth.

**Comment by setpill** [comment]
Personal Access Tokens and OAuth tokens (e.g. gitlab auth token) are identical in use to the session token received after user/pass login (at least as far as the API is concerned). See https://api.mattermost.com/#tag/authentication.

**Comment by setpill** [comment]
> When validating the configuration and loading the token, refuse to load the token unless the file pointed to by `personalAccessTokenFile` has any other mode than `0600`.

Screwed yaself with a double negative here @jtdaugherty. Probably you meant either

> When validating the configuration and loading the token, refuse to load the token **if** the file pointed to by `personalAccessTokenFile` has any other mode than `0600`.

XOR

> When validating the configuration and loading the token, refuse to load the token unless the file pointed to by `personalAccessTokenFile` has mode `0600`.

**Comment by setpill** [comment]
But I disagree with storing the token in a file; it should be treated as a password and not stored plaintext at all. Would be preferable to allow people to enter it at matterhorn start (just like their password) and let them store it in their password manager.

**Comment by Atlantic777** [comment]
I would say that the token can be passed to the `Network.Mattermost.WebSocket` coming from `matterhorn/mattermost-api` and just use the secret token instead of the regular token, for instance [here](https://github.com/matterhorn-chat/mattermost-api/blob/master/src/Network/Mattermost/Connection.hs#L110).

Regarding the question of storing the token in a text file, I don't see any problem with that assuming the file permissions are correct. IMHO, I believe that it's better to start with the config file approach. Later we can extend it with features such as inserting the token through the interface, remembering tokens, managing multiple tokens and similar.

**Comment by setpill** [comment]
Assuming the config files are stored somewhere under the user's homedir, default mode of `700` on `$HOME` already prevents reading of the file. The bigger threat is from other applications running as the same user, which mode `600` does not protect against either.

**Comment by Atlantic777** [comment]
The same goes for unencrypted SSH keys and many other things but we still use them. I would say the users should make that choice and accept the risk if they want. Myself, I would be happy to use the tokens stored in a file while a more advanced and more secure solution is being developed.

As an alternative that is perhaps more secure the environment variables should maybe be considered. Getting the token from environment is most probably on the same level as getting it from the config file.

**Comment by setpill** [comment]
> The same goes for unencrypted SSH keys

That's why you encrypt your {SSH,GPG,whatever} keys...

> but we still use them

It's bad practice and preferable to not be implemented/supported, especially not with a fake sense of security redundant file mode enforcement, *especially* not as the only option (no matter how temporarily).

**Comment by setpill** [comment]
Actually it seems like the default permissions on homedir differ per distro - `700` is not universal. My mistake. Still, the point about not storing passwords/tokens/private keys unencrypted stands.

**Comment by jtdaugherty** [comment]
@setpill You're right, I meant "refuse to load *if*." Thanks!

> But I disagree with storing the token in a file; it should be treated as a password and not stored plaintext at all. Would be preferable to allow people to enter it at matterhorn start (just like their password) and let them store it in their password manager.

This is why my proposal also includes the other bullet item, which would allow the user to *omit* this on disk entirely and provide it in the login user interface.

As for storing the access token in plaintext, I'd be happy to extend the proposal with another bullet to help in cases where users do not want to take that approach:

* Add a new configuration option, `personalAccessTokenCommand`, which has the same semantics as the password command. This way the user can store the access token in their system keychain and use an interactive process to obtain the access token securely.

**Comment by jtdaugherty** [comment]
@kquick and I talked this over in person and also concluded that if the configuration specifies more than one authentication method, the application should exit and complain. The motivation for that is to be conservative and not do any automatic fallback from one authentication method to another, since we cannot assume we know what the user wants (and getting that wrong could lead to security issues).

So, another bullet for the proposed approach:

* On startup, check the configuration's specification of authentication. If the configuration file specifies more than one option (out of: password, password command, access token file, access token file command) then exit and complain that the config can only specify one method.

**Comment by setpill** [comment]
`personalAccessTokenCommand` seems like a very sensible way to allow smooth and secure integration with keychain applications. Personally I am of the opinion that plaintext keyfiles should be strongly discouraged if implemented at all (preferably not implemented since that leads to less proliferation of bad security practices/people who don't understand why it's a bad idea incorporating plaintext keyfiles into their workflow), but I am already very happy that this is getting some traction so will refrain from further comment on that particular point from now on.

**Comment by jtdaugherty** [comment]
> Personally I am of the opinion that plaintext keyfiles should be strongly discouraged if implemented at all

I completely agree with this sentiment, and having talked to @kquick about it, I know he does, too. The reason I proposed it (with a file mode check) is to provide a middle-ground option to people without a good "keychain command" option. So let's add another bullet. How about this:

* When documenting the settings, explicitly recommend using the `personalAccessTokenCommand` option and indicate that `personalAccessTokenFile` is only provided as a convenience. Indicate that while it does do a file mode check, the user is still responsible for the security of said file.

**Comment by jtdaugherty** [comment]
Also, @setpill, thanks for your comments - I appreciate the hot-button nature of these security questions, and this is precisely why I said early on in this ticket that we'd need to hash out an approach before someone starts working on a patch. I agree that it's important to limit the spread of undesirable practices and features that perpetuate those practices. And I agree that if we're going to provide a less-than-amazingly-secure option (out of pragmatism in this case), then we absolutely need to put a big red sign on it that says "we provide this only in case you absolutely need it and know what you're doing, but you probably don't want this."

**Comment by jtdaugherty** [comment]
After working out the details on @ftilde's [recent pull request](https://github.com/matterhorn-chat/matterhorn/pull/581), I wrote up a new patch based on that work on the `feature/access-tokens` branch.

**Comment by jtdaugherty** [comment]
This is now merged to `develop`. Thanks, everyone!

**Comment by ftilde** [comment]
For anyone else who is stuck with using gitlab authentication for their mattermost instance: I have created a [script](https://github.com/ftilde/mattermost-session-cookie-firefox) that is intended to be used as a `tokencmd`, automatically fetches the session token from the firefox cookie and requests the user to log into the web client if the cookie is invalid/not found.

**Comment by jtdaugherty** [comment]
@ftilde nice!

**Comment by jtdaugherty** [comment]
@ftilde do you mind if I link to that from the README?

**Comment by jtdaugherty** [comment]
(Assuming that's fine, I went ahead and [did so](https://github.com/matterhorn-chat/matterhorn#token-cookie-authentication))

**Comment by ftilde** [comment]
I don't mind at all. Excellent!
