### ISSUE TITLE
Configuration validation/warning mode

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#516]
We'd like Matterhorn to support configuration validation as an independent operation. The idea here is that the configuration may have serious problems (that would be fatal to `matterhorn` anyway) or merely questionable practices (like use of some security settings) that we'd like to either warn about or emit errors. Ordinarily the fatal settings would cause `matterhorn` to shut down, but it would be nice if there was a way for us to provide warnings to the user in an independent mode that was friendly to shell-scripting. So the task here is to:

* Add a startup argument, e.g. `--check-config`, that causes Matterhorn to load the configuration and check it.
* The configuration check should generate warnings and errors, and if any of either of those are generated, they should be printed to `stderr` and the exit status should be non-zero. Otherwise the exit status should be zero and no output to `stdout` or `stderr` should be provided.

Also, as part of this, @kquick and I figured this would be a good opportunity to sanity-check other aspects of the config that we currently don't check, such as the existence and file mode of ostensibly executable programs such as the password command.

Lastly, this process should be triggered as part of normal Matterhorn startup, with the console output silenced. So this would require refactoring the startup code to always run this check.

**Comment by glguy** [comment]
One of the validations I'd like matterhorn to do is to detect configuration settings that are unused (these can be typos where the user expected something to happen)

**Comment by jtdaugherty** [comment]
That would be great! I think right now [config-ini](https://github.com/aisamanra/config-ini) will silently ignore those, so it might need to be patched to help with this.

**Comment by jtdaugherty** [comment]
This is now implemented in `develop`.
