### ISSUE TITLE
Paste doesn't work on the login screen

### ISSUE THREAD

**Issue by rruizt** [matterhorn-chat/matterhorn#518]
I cannot paste my password on the password field from the version 5200.3.0-ubuntu to latest. 

It works as expected up to 5200.2.0

Thank you for your work.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
For @immindich and @kquick: thinking about this, I think the best solution is to just add `EvPaste` event support to Brick's built-in editor. That would be an improvement anyway, and it would give us a fix for this for free.

**Comment by jtdaugherty** [comment]
This is now fixed as of https://github.com/matterhorn-chat/matterhorn/commit/5b6d9dfb3d6c7cfb13d61efd924d8d89051b6871 (see also https://github.com/jtdaugherty/brick/commit/df89a58eecb2bb3d598e20862973e7e7efb1f8fd).
