### ISSUE TITLE
A full BChan will lock Matterhorn

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#528]
The MH monad callbacks from async processes may write additional events into the BChan.  If the BChan becomes full during this process, a deadlock occurs: the async callback event is blocked on writeBChan but it never completes this event to allow the event handler to remove another event from the BChan.

This can be demonstrated by typing `/group-msg badname1 badname2 ... badname26`, where none of the names exist.  The async MH callback will try to loop to add an error event to the channel for each bad name, but the current channel limit is 25 so the write of the 26th entry blocks.

This deadlock is also unfortunate because the entire Matterhorn application freezes and must be externally killed.

The suggested solution is:
* Allow the BChan to indicate "full" condition (brick)
* Detect the "full" condition in Matterhorn and throw an exception (uncaught, crashing the application, but leaving a message/log behind).
* Increase the Matterhorn BChan limit: this value should protect against things like runaway infinite loops but it should not be small enough that normal operations hit it.  A reasonably extreme value (e.g. 2500) provides this protection while causing crashes in a failure scenario that should be detected, reported, and fixed.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
