### ISSUE TITLE
is it possible to switch between teams?

### ISSUE THREAD

**Issue by dirtbag** [matterhorn-chat/matterhorn#533]
When you initially sign into matterhorn, you have to pick a "team".
In the gui mattermost client, you can switch between these easily. I cant seem to find that option in matterhorn without starting up another instance of it?

-db

**Comment by jtdaugherty** [comment]
Sorry, but no - Matterhorn does not support team switching. You'll have to run an instance of Matterhorn for each team that you're in.

**Comment by jtdaugherty** [comment]
Just to follow up: support for multiple teams is now in `develop` and will be included in the next release.
