### ISSUE TITLE
Build according to readme needs github login for submodule loading

### ISSUE THREAD

**Issue by Deaddy** [matterhorn-chat/matterhorn#536]
Following the readme, the build should happen via:
```
$ git pull
$ git submodule update --init
$ ./build.sh
```

However, on a machine without active ssh-key for github we get errors after `git submodule update --init` for not being able to authenticate as git@github.com, i.e. the following (sorry, error messages are in German, but they say exactly that):

```
Klone nach '/home/m_wund01/tmp/matterhorn/submodules/aspell-pipe' ...
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: Klonen von 'git@github.com:matterhorn-chat/aspell-pipe.git' in Submodul-Pfad '/home/m_wund01/tmp/matterhorn/submodules/aspell-pipe' fehlgeschlagen
Fehler beim Klonen von 'submodules/aspell-pipe'. Weiterer Versuch geplant
Klone nach '/home/m_wund01/tmp/matterhorn/submodules/mattermost-api' ...
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: Klonen von 'git@github.com:matterhorn-chat/mattermost-api.git' in Submodul-Pfad '/home/m_wund01/tmp/matterhorn/submodules/mattermost-api' fehlgeschlagen
Fehler beim Klonen von 'submodules/mattermost-api'. Weiterer Versuch geplant
Klone nach '/home/m_wund01/tmp/matterhorn/submodules/mattermost-api-qc' ...
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
fatal: Klonen von 'git@github.com:matterhorn-chat/mattermost-api-qc.git' in Submodul-Pfad '/home/m_wund01/tmp/matterhorn/submodules/mattermost-api-qc' fehlgeschlagen
Fehler beim Klonen von 'submodules/mattermost-api-qc'. Weiterer Versuch geplant
Klone nach '/home/m_wund01/tmp/matterhorn/submodules/aspell-pipe' ...
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.
```

**Comment by jtdaugherty** [comment]
Thanks for the report! In the mean time, are you able to run a binary release?

**Comment by Deaddy** [comment]
Oh I missed the notification. Well, I don't have to roll it out in production so I can just use my github acc, but of course that's somewhat prohibitive in automated built environments.

**Comment by jtdaugherty** [comment]
You can find binary releases in the Releases section of this repository, and if you want notifications about when they get published, you can follow our [Twitter account](https://twitter.com/matterhorn_chat).

**Comment by Deaddy** [comment]
Well, the correct thing to do is to change the .gitmodules, but at least it's documented now.

**Comment by jtdaugherty** [comment]
Yes, my intention is to document the current behavior. Despite your unhelpful assertion, there are definitely downsides to using `https` submodule URLs. They are basically the same downsides to using SSH submodule URIs, but in reverse. Many git-based projects have this problem and as far as I can tell a common workaround is to `sed`-hack the `.gitmodules` file to cope with the issue in local clones, which I would rather not do.

Thanks for bringing this to our attention!
