### ISSUE TITLE
Make it clear that the config file needs a NL at the end

### ISSUE THREAD

**Issue by EugenMayer** [matterhorn-chat/matterhorn#540]
If not, one gets parsing issues, e.g. put the `activityNotifyCommand = ` definition at the most bottom and it will fail.

Just a little hint

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
I wanted to clarify: are you saying that you put `activityNotifyCommand =` in your configuration file without assigning a value to the setting?

**Comment by EugenMayer** [comment]
No lets say you haved 

```
activityNotifyCommand = /foo/bar
```

But you have no NL at the file, it will fail to parse the file. I think this has nothing to do with the setting `activityNotifyCommand` itself, but rather that the parser expects the config file to end with a blank line

**Comment by jtdaugherty** [comment]
Thanks, that makes sense; I took your earlier comment literally, but wanted to be sure I understood. I've filed a bug with the maintainer of the library that we use to parse our configs. If they don't respond promptly, we'll compensate for this in Matterhorn.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. (Attn @aisamanra)

**Comment by EugenMayer** [comment]
Gj
