### ISSUE TITLE
[ArchLinux] /etc/localtime: invalid timezone file: no timezone found in OlsonData

### ISSUE THREAD

**Issue by oblitum** [matterhorn-chat/matterhorn#542]
Getting error `matterhorn: /etc/localtime: invalid timezone file: no timezone found in OlsonData` on latest release on ArchLinux. First time I trying to use it. It's for chat.mycroft.ai:

```
Mattermost Enterprise Edition

Modern communication from behind your firewall.
Mattermost Version: 5.11.0
Database Schema Version: 5.11.0
Database: postgres
Licensed to: Mycroft AI, Inc. - NP
```

**Comment by jtdaugherty** [comment]
Thanks for the report!

We've actually had a report from another user on Arch Linux about this same problem. That was back in August. We tracked the problem down to something to do with the library that we use to parse `/etc/localtime`, and it seems that something about the timezone file format is different on Arch that what the library expects. I reported the problem to the maintainer via e-mail (their repository isn't on a public issue tracker) but I haven't heard back from them. I just e-mailed them again to see if they'll respond.

The user that reported this was using the Sao Paolo time zone file, as shown by looking at the symbolic link target of `/etc/localtime`: `/usr/share/zoneinfo/America/Sao_Paulo`. What does your `localtime` link to? It might be helpful to send that zone info file to the library maintainer as another test case.

**Comment by oblitum** [comment]
I'm on same timezone as that user.

[Sao_Paulo.zip](https://github.com/matterhorn-chat/matterhorn/files/3784211/Sao_Paulo.zip)

**Comment by oblitum** [comment]
If maintainer won't respond you on that, never mind about it, feel free to close the issue.

**Comment by jtdaugherty** [comment]
As much as I would like to avoid forking the timezone library, if the maintainer doesn't respond then we will probably need to fix this ourselves. I wouldn't want this preventing people from using Matterhorn. Thanks for taking the time to report this!

**Comment by pulpo** [comment]
Same problem here:
```
$ ls -ltr /etc/localtime 
lrwxrwxrwx 1 root root 37 nov 25 11:19 /etc/localtime -> ../usr/share/zoneinfo/America/Cordoba
```

**Comment by jtdaugherty** [comment]
As an update, I have not yet heard from the timezone library maintainer yet.

**Comment by ahmedbilal** [comment]
```
[meow@meow-pc ~]$ ls /etc/localtime -l
lrwxrwxrwx 1 root root 32 Oct  5 12:13 /etc/localtime -> /usr/share/zoneinfo/Asia/Karachi
```

**Comment by jtdaugherty** [comment]
It appears that the maintainer for the timezone library recently migrated to GitHub, so I have just reported a bug there (linked above).

**Comment by abdallah** [comment]
same issue from Manjaro (Arch)
```
ls -ltr /etc/localtime
lrwxrwxrwx 1 root root 31 Feb 24 21:43 /etc/localtime -> /usr/share/zoneinfo/Asia/Beirut
```

**Comment by jtdaugherty** [comment]
The maintainer of `timezone-olson` got around to fixing this issue. I've upgraded to the fixed version of that library in our `develop` branch, and this will be resolved for `matterhorn` users in the next release. Thanks, everyone!
