### ISSUE TITLE
[SOLVED] Display corrupt

### ISSUE THREAD

**Issue by morsedl** [matterhorn-chat/matterhorn#544]
Hi,

After installing (binary), matterhorn seems to be working fine: I can connect to our server, select a team, and then see the main matterhorn channels screen. The login and team-selection screens are displayed fine. However, I cannot use the program because the main channels screen is being corrupted by a particular ansi escape sequence (I presume):

![screenshot](https://user-images.githubusercontent.com/761567/70746739-b6240c80-1d26-11ea-9c00-ba98d90da60e.png)

By default I use TERM=xterm-265color. I've also tried xterm, ansi, linux, vt100 (not usable), and vt220. Regardless of which TERM setting I use, the same sequence of characters corrupts the main channels screen in exactly the same way and exactly the same locations. Given where it's happening, it seems to me that the sequence is some sort of terminating or resetting sequence (e.g., switch back from alt charset, reset to base color, etc.). But the sequence is the same regardless of what TERM type I select, which makes me wonder if perhaps this escape sequence is hardcoded somewhere? When I copy and paste the errant sequence, it returns as: ]8;; Copying and pasting as a string in Python REPL yields '\x1b]8;;'. So it seems pretty definitive that this is an escape sequence, namely:
```
ESC ] 8 ; ;
```

The problem is identical whether under Gnome Terminal or Terminator.

In google around for the escape sequence in various formats (e.g., ^[]8; -- here, \e]8; specifically) I ran across [DomTerm's Wire Protocol](https://domterm.org/Wire-byte-protocol.html) page, and there they define this escape sequence (minus the second semi-colon, which makes me wonder if it has to do with the problem) as such:

> "\e]8;" options ";" url "\a" text "\e]8;;\a"
> Create a link with the given url and display text (which can contain other escape sequences for styling). The options are ignored. The link has class="plain". See this link.

Other than that, I've not found anything regarding this specific escape sequence (they're not easy to google for). Given DomTerm's definition, I of course seached my config.ini for "url", saw the following settings commented out, uncommented it, but still no joy:

```
urlOpenCommandIsInteractive = False
hyperlinkURLs = False
```

Or saw I thought. And then I noticed that from sample-config.ini (the basis for my .local/matterhorn/config.ini) has hyperlinkURLs as True (the default). So in fact I had:

```
urlOpenCommandIsInteractive = False
hyperlinkURLs = True
```

As soon as I set hyperlinkURLs to False (as I thought I had), the problem was resolved.

I'm still posting this issue for two reasons. First, in case someone else has this problem, perhaps this will be helpful to them. Second is to request that you discuss this in the main README.

And now I see you have, blast it. ;-)

Maybe then just add the terms "corrupt", "corruption", "display problems", "cannot read", "]e;;" etc. to that section? I would have never thought to search within page for "malformed", and there are no other terms in that final paragraph about the hyperlinkURLs setting that I would think would lead people needing it to that section (i.e., the very people having the problem).

Gratitude for the software! Now that I can use, I expect it will be a big time saver for short and simple posts and replies.

**Comment by jtdaugherty** [comment]
We can definitely add a few terms to the README to make this a bit easier to catch. Thank you for the report!

**Comment by jtdaugherty** [comment]
Okay, this is now done in the above mentioned commit. Thanks!

**Comment by morsedl** [comment]
:+1:  Great, thanks! Glad to be of (some small amount) of help. ;-)
