### ISSUE TITLE
Cannot exit multi-line editor on MacOS

### ISSUE THREAD

**Issue by ReagentX** [matterhorn-chat/matterhorn#545]
From the readme:

> To send a multi-line message, toggle multi-line mode with the default binding M-e.

On MacOS, `alt-e` is bound to the ´ character, so it is impossible to exit the multi-line editor. `esc-e` does not work either.

Setting `alt` to send `meta` in iTerm 2 sends � instead of sending ´, but still does not work.

**Comment by jtdaugherty** [comment]
Thanks for the report! On OS X, `alt` is not `meta`; for Meta you'll need to adjust your terminal emulator settings. (iTerm2 calls this `Esc+`, I believe.) I personally use iTerm2 and bind the left Command button to `Esc+`, and that works well for me.

I'm curious, though - if you can't exit the mode with `M-e`, how did you get into it in the first place?

**Comment by ReagentX** [comment]
Typing ``` activates milti-line input. Setting either `option` key to `Esc+` in iTerm 2 still types the ´ character when I use M-e.

**Comment by jtdaugherty** [comment]
Oh, thanks - I forgot about the backtick mode switch. I’m sorry to hear that M-e is still not working; in the mean time, you might consider remapping that binding to something that works better for your setup using the custom keybindings support.

**Comment by jtdaugherty** [comment]
@ReagentX were you able to make any progress with specifying a custom keybinding?

**Comment by jtdaugherty** [comment]
@ReagentX I'm going to close this on the assumption that you've been able to find a workaround. Please re-open if you need more help. Thanks!
