### ISSUE TITLE
Solution for macOS notification

### ISSUE THREAD

**Issue by jesseXu** [matterhorn-chat/matterhorn#546]
Would be nice to have native notification support when running on macOS terminal.

**Comment by jtdaugherty** [comment]
Hi @jesseXu. This is possible on macOS by using the `activityNotifyCommand` configuration setting. See [the sample config](https://github.com/matterhorn-chat/matterhorn/blob/master/docs/sample-config.ini) for an example of the setting and see [the bundled Linux notify script](https://github.com/matterhorn-chat/matterhorn/blob/master/notification-scripts/notify) as a starting point.

**Comment by jtdaugherty** [comment]
@jesseXu Please let me know if that information helps by closing this ticket, or posting further questions so we can assist. Thanks!

**Comment by jesseXu** [comment]
@jtdaugherty Thanks a lot! That works for me.

**Comment by jtdaugherty** [comment]
Great!
