### ISSUE TITLE
Can't connect to server: JSONDecodeException

### ISSUE THREAD

**Issue by little-arhat** [matterhorn-chat/matterhorn#550]
Hi, 

Thank you for great app!

Yesterday, after computer restart my matterhorn stopped working: it can't connect to server:

```
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $[0]['invite_id']: Empty ID", jsonDecodeExceptionJSON = "[{\"id\":\"sty...\",\"create_at\":1456291776261,\"update_at\":1534924873050,\"delete_at\":0,\"display_name\":\"<redacted>\",\"name\":\"<redacted>\",\"description\":\"\",\"email\":\"\",\"type\":\"O\",\"company_name\":\"\",\"allowed_domains\":\"\",\"invite_id\":\"\",\"allow_open_invite\":true,\"last_team_icon_update\":1534924873050,\"scheme_id\":null,\"group_constrained\":null}]"}
```

```
>>= matterhorn --version
matterhorn 50200.5.0 (master@931db50)
 using mattermost-api 50200.2.0 (HEAD@b197ced)
```

We're using enterprise edition:

```
Mattermost Version: 5.18.1
Database Schema Version: 5.18.0
```

**Comment by jtdaugherty** [comment]
Thanks for the report! When was the last time your server restarted? Did its configuration change recently? (I ask because if you have not been having issues with that server version until now, something could have changed that wasn't given to clients until now. This sort of thing has happened before when our JSON parser is stricter than it should be.)

**Comment by little-arhat** [comment]
Looks like it was upgraded to 5.18.1 this Sunday, but I haven't restarted my client till yesterday.

Also, it fails only if I enter correct password; with wrong one matterhorn properly displays error.

**Comment by jtdaugherty** [comment]
Okay, thanks. I'm working on a fix now and I expect to have a release out today. I'll update here when it's done.

**Comment by jtdaugherty** [comment]
This is now fixed in 50200.6.0: https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.6.0

Please give that a try. If it resolves your issue, please close this ticket or let me know what else we can do.

**Comment by little-arhat** [comment]
@jtdaugherty New version indeed does resolve my issue, amazing! 

Thanks!

**Comment by jtdaugherty** [comment]
Great!
