### ISSUE TITLE
The futex facility returned an unexpected error code.Aborted (core dumped)

### ISSUE THREAD

**Issue by O5ten** [matterhorn-chat/matterhorn#551]
I attempted to use this from WSL (Windows Subsystem Linux) and i get spontaneous crashes with this error message. Sometimes at login, sometimes after successful login. 

```
> The futex facility returned an unexpected error code.Aborted (core dumped)
```

Running latest and greatest mattermost server and the latest release from this repos releases.

**Comment by kquick** [comment]
Thanks for the report, @O5ten, but I'm not sure there's much we can do about this.  That error is related to the WSL itself, and it looks like you might be able to upgrade your Windows installation to fix it: https://github.com/Microsoft/WSL/issues/3618.

**Comment by riverar** [comment]
@kquick I think this was closed too early; could be a regression. @O5ten can you verify the version of Windows 10 you're seeing this on?
