### ISSUE TITLE
Switching to another channel shows error

### ISSUE THREAD

**Issue by misery** [matterhorn-chat/matterhorn#557]
If I quickly switch the channel with C-n or C-p it will throw this error for each switch.

[log.txt](https://github.com/matterhorn-chat/matterhorn/files/4184862/log.txt)

![Screenshot_20200211_102732](https://user-images.githubusercontent.com/50925/74224554-5e1f6d00-4cb9-11ea-8c54-d70f174eca38.png)

**Comment by misery** [comment]
See #561 ?

**Comment by jtdaugherty** [comment]
Thanks! This is a duplicate of #504. You may be switching channels so quickly that you are hitting your server's API request limit (hence the 429 responses). We have not yet fixed this in Matterhorn, but in the mean time, if you can, you may consider raising your server's request limits.
