### ISSUE TITLE
Command mode

### ISSUE THREAD

**Issue by misery** [matterhorn-chat/matterhorn#560]
Most times the last chat is opened on my screen but there is no conversation. Sometimes I want type a command and did no press the right button... write the command and send the half command to the user. That's a little bit annoying.

So maybe it would be nice if there is an option to switch to a "command" mode like in ```vim``` that won't write any messages to user. So I can press ```ESC``` on my conversations to switch to that mode.

**Comment by jtdaugherty** [comment]
I can appreciate that this would be an unpleasant experience. I'm afraid we aren't going to implement a command mode like the one you describe. In the mean time, you can delete messages that you didn't mean to send by pressing `C-s`, selecting the message you sent by mistake, and pressing `d`.
