### ISSUE TITLE
Add ability to save message verbatim portions

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#563]
Matterhorn currently supports the ability to "yank" the verbatim portion of a message to the clipboard, although this requires `xsel` or `xclip` to be installed, which are ironically part of a windowing system while Matterhorn is a TUI utility.

It would be nice to also add the ability to "save" the verbatim portion of a message to a file.

The implementation should observe parallels with the save attachment functionality to maintain a consistent user experience.

**Comment by jtdaugherty** [comment]
It seems to me that if we're going to allow saving, we might as well allow saving the Markdown source of the post rather than just the verbatim bits.

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
