### ISSUE TITLE
Integrate support for Vty Unicode width tables

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#569]
Now that Vty 5.28 is out, it supports [custom Unicode character width tables](https://github.com/jtdaugherty/vty#multi-column-character-support). That means Matterhorn is now in a position to improve its support for emojis, Asian characters, and anything else that typically needs more than a column to be drawn.

To take advantage of Vty's improved support for these characters, Matterhorn needs Vty to use a custom width table. But for that to exist, it needs to be created somehow: either programmatically  or by using Vty's new `vty-build-width-table` command-line tool.

This ticket is to discuss how do to that. My starting-point proposal is:

- [x] Upgrade to Vty 5.28
- [ ] Add a command-line option (`-b`/`--build-unicode-table`) to Matterhorn to trigger a table build for the current terminal type (`TERM`)
- [ ] Have the Matterhorn `-b` behavior write the generated table to `~/.config/matterhorn/unicode-tables/<TERM>_width_table.dat`.
- [ ] Add a new Matterhorn configuration option, `useCustomUnicodeWidthTables`, with a default value of `True`.
- [ ] If `useCustomUnicodeWidthTables = True`, have Matterhorn use the value of `TERM` to attempt a table load at startup by looking for a matching table file in `~/.config/matterhorn/unicode-tables/`.
- [ ] Make Matterhorn turn off automatic table loading in Vty (via Vty's `Config` field) to ensure that it doesn't clash with Matterhorn's behavior.
- [ ] Log the result of the table load and installation to the Matterhorn logging infrastructure.
- [ ] Add a UI indicator of the current table status, such as at the top of the help screen.

Another issue to consider that @kquick mentioned is how best to manage the default behavior for new Matterhorn users (or users that upgrade to the version with this functionality). Initially there will be no custom table in place, so Matterhorn is likely to suffer from rendering issues in the presence of multi-column characters. Matterhorn will clearly be able to tell whether a custom table is present and can recommend that the user make one. There are a variety of ways this could be done, but I think it would be good to ensure that the behavior is unobtrusive.

An example approach to dealing with this would be:
* At startup, look for the presence of a custom table.
  * If one is present, use it and continue.
  * Otherwise:
     * If `~/.config/matterhorn/skip_unicode_question` exists, start the application.
     * If not: tell the user on the console: "There is no table present. We strongly recommend you let me make one. Can I do that now? (y/n)"
       * If the user says `y`, generate one, save it, install it, and then start the application.
       * Regardless of the user's response, write `~/.config/matterhorn/skip_table_question`

The above approach could also be augmented with a third option to allow the user to use the Vty config instead of using Matterhorn for this at all. For that, it might be best for the `useCustomUnicodeWidthTables` configuration setting to take one of `no`, `vty`, `matterhorn`, with a default of `matterhorn`.

**Comment by jtdaugherty** [comment]
There is a counter-argument that is worth outlining here, too:

Vty's built-in behavior is to look at `~/.vty/config` for configured width tables based on `TERM`. One response to my proposal could be: "Why not use that?" My response is: while Matterhorn is a Vty-based application, that isn't necessarily something I think we ought to expose to the user. I would prefer to keep all user-configurable Matterhorn assets (configuration, input files) in one place.

Another question that could arise: "But if Vty looks in `~/.vty/config`, then isn't that a good thing? Doesn't it defeat the purpose of that config to put our tables elsewhere?" The response: yes, sadly, it does defeat that. And if a user *knew* they were running multiple Vty-based applications then it would be surprising that Matterhorn didn't honor the configured Vty table. But my response to that is: in general, a user has no way to tell whether an application is Vty-based. The application developer has to go to trouble to indicate that. So it won't even be evident when the Vty config *ought* to have an effect anyway. (I happen to hold the view that the Vty configuration file is a mis-feature.)

**Comment by kquick** [comment]
One other feature to consider is to display whether a unicode table is in place or not, and (especially following the convention that it is a matterhorn configuration) which TERM/table is being used.  Places this could be displayed:
  * The logfile
  * On the login page
  * On the help screens

[Minor note: the initial description above uses two separate names for the skip file.]

Would another option (and marker file) be "use the Vty package configuration" to defer to `~/.vty/config`?  This would require active user selection, but would allow vty conformance for people aware of an desiring that.

**Comment by jtdaugherty** [comment]
Ah yes, we could definitely support a "use the Vty config" option, both in the interactive process I described above as well as in the Matterhorn config. That way users could at least do that if they wanted, regardless of the my own view on the matter. 😊

**Comment by jtdaugherty** [comment]
@kquick I added a bullet above about the help screen.

**Comment by jtdaugherty** [comment]
@kquick I also added some text about the "use Vty config" option.

**Comment by glguy** [comment]
What if applications like matterhorn and glirc simply checked if a table was loaded and if not helped automate the process of configuring vty by generating the table and appending the configuration entry into `~/.vty/config` This isn't a setting that anyone will want to change across any vty app, and even though the tools would be creating `~/.vty` entries, that shouldn't need to be visible to the user. Encouraging application developers store duplicate unicode tables doesn't seem to provide any user or developer benefit.

**Comment by jtdaugherty** [comment]
> What if applications like matterhorn and glirc simply checked if a table was loaded and if not helped automate the process of configuring vty by generating the table and appending the configuration entry into ~/.vty/config

We could definitely do that. I think the only way that will be okay is if Matterhorn manages that process fully and smoothly. Having Matterhorn's configuration effectively be stored in two separate places isn't ideal to me from a design perspective, so I'd definitely want to make sure the user never has to know about `~/.vty/`.

**Comment by jtdaugherty** [comment]
Just to capture some context on this since it has been idle for a while: the Vty width table approach only works well for measuring the widths of single characters when no additional combining characters are involved. Unfortunately, a lot of Unicode characters are obtained by using combining characters or modifiers, so the width measurements that Vty does are wrong because those modifiers are not taken into account. Until the Vty width table computations become multi-character aware, and until Brick's string width computations can do lookahead in strings to check for sequences of multiple code points that belong together, this ticket can't be completed.

**Comment by jtdaugherty** [comment]
I'm going to close this as basically unworkable for now. While I'd really like to see this situation improve long-term, there are a lot of barriers in our way that are not under our control, so leaving this open doesn't make sense. If the situation improves, we can revisit this.
