### ISSUE TITLE
Consider consolidated server URL input in login form

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#574]
From a comment by @glguy:

An alternative design [to the current login form's individual inputs for URL components] would be to not separate the host and path portion but to allow the user to specify them all in one go. This has the advantage that the user can basically paste what he sees in a web browser into matterhorn. I'm imagining this UI:

```
          ┌──────────────────────────────────────────────────────────┐          
          │Please enter your Mattermost credentials to log in.       │          
          │                                                          │          
          │Server:           mattermost.example.com:443/path/part    │          
          │                                                          │
          │Username:         emertens                                │          
          │                                                          │          
          │Password:                                                 │          
          │                                                          │          
          │          Press Enter to log in or Esc to exit.           │          
          └──────────────────────────────────────────────────────────┘
```

In the most common case where we use the defaults a user might only enter

```
          │Server:           mattermost.example.com                  │          
```

**Comment by kquick** [comment]
I think we might still need to separate the elements (via urlparse) to establish websocket as well as direct server access (just a hunch, I haven't looked specifically).  It would be worth spending some archaeological effort determining why this approach wasn't taken when the login process was initially designed.

If we were to try to use urlparse, we would probably need to either synthesize the protocol specification prefix (e.g. `https://`) or require the user to input that part as well. 

Alternatively we could internally parse a subset like the above, but we would want to have either or both of (a) good documentation about what is expected (probably right there on the login screen) and (b) resiliency in the parser for the user providing extra elements like the protocol.

**Comment by jtdaugherty** [comment]
To review the listed advantages above:
* A single field makes entry easier when only the server's hostname is known.
* A single field makes entry easier even for the full URL case, scheme and path and all.

Some things we need to consider:
* A URL entered with no scheme, port, or path should default to `https`, `443`, and `/` respectively.
* If the scheme and/or port are provided explicitly, they should be honored: so `https://foo:123/` or `http://foo:443/` should be taken literally.
* Schemes other than `http` and `https` should be rejected.
* To be safe, the input handling should trim anything after the URL path (query string, fragment, etc.).

To @kquick's comment, there is probably not going to be any evidence anywhere as to why this was not the original approach. (It was not documented or even discussed explicitly, IIRC.)

Another consideration is how this interacts with the configuration file. Right now the fields are filled in from the individual configuration settings (which we need to keep). So for this new feature to work, a URL will need to be built from the config file's values where available. That's going to need to consider things like the defaults, and omit those from the URL if the config file settings match the defaults.

Probably the thing that I'm most concerned about with this feature is that while it makes login easier, it will have no corresponding single configuration setting. The configuration will still need to support the individual settings as it does now, so I'm concerned about the user needing to deal with that mismatch at some point.

**Comment by glguy** [comment]
I think we can handle the configuration file by using the same parsing behavior in the server field but still support separate configuration fields for UrlPart and Port. We could report an error if the port was specified both in the server configuration field and also in a port configuration field. This would ensure that existing configuration files continue to work and that new users will have access to the simpler interface where they copy and paste their web URL into the configuration.

**Comment by jtdaugherty** [comment]
That's what I was thinking and also why I didn't propose it: I want to avoid two different valid but potentially conflicting configuration approaches.

**Comment by glguy** [comment]
@jtdaugherty 's list of defaults makes sense. Instead of trimming I would suggest we reject unsupported URL portions and tell the user what happened to reduce surprise.

Possible errors:

- "Only http and https are supported"
- "Query fragment in server URL not support"

**Comment by jtdaugherty** [comment]
Ah yes, that would be better!

**Comment by jtdaugherty** [comment]
Since one sticking point with this feature is its relationship to the configuration, it might help to just reframe this as "make the login form nicer to use as a veneer only; don't worry about making a configuration option that exactly matches the UI's behavior."

Which is to say, if you want to configure with the file, you'll have to break up the requisite URL components. And there is a super-old ticket relevant to this that is still work doing: make the login UI ask whether the user would like the configuration saved. That would also alleviate the mismatch issue to some extent.

**Comment by kquick** [comment]
Optionally we could display (underneath the entry form) the current parsed results, applying defaults and dynamically updating as the user types.  Rough idea:

             ┌──────────────────────────────────────────────────────────┐          
          │Please enter your Mattermost credentials to log in.       │          
          │                                                          │          
          │Server:           mattermost.example.com/path/part    │
            |
            |                   * Scheme: https://                   |
            |                   * Server: mattermost.example.com     |
            |                   * Port:   443                        |
            |                   * Path:   ________                   |          
          │                                                          │
          │Username:         emertens                                │          
          │                                                          │          
          │Password:                                                 │          
          │                                                          │          
          │          Press Enter to log in or Esc to exit.           │          
          └──────────────────────────────────────────────────────────┘

**Comment by glguy** [comment]
Fixed on `develop`
