### ISSUE TITLE
Support setting connection status

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#575]
The web client allows the user to set their status to one of {Online, Away, Do Not Disturb, Offline}. Matterhorn should support that as well.

**Comment by jtdaugherty** [comment]
```
dlamkins: It'd be cool, I think, to have a "do not disturb" switch. This'd set the
appropriate status and also ensure that activityBell=false.
```

**Comment by glguy** [comment]
Matterhorn should also indicate the user's own current status alongside the username field in the top-left. This could be done using the `+-x` sigils used in matterhorn in other places

**Comment by thlc** [comment]
+1 on this one, especially @glguy's comment.
However, I have just noticed that you could change your status using the following commands:

/away: Set your status away
/offline: Set your status offline
/online: Set your status online 
/dnd: Set your status to Do Not Disturb

As stated in the Mattermost docs: https://docs.mattermost.com/developer/slash-commands.html#built-in-commands

**Comment by 3v1n0** [comment]
Could be possible to also include here support for auto-away based on the recent activity?

**Comment by jtdaugherty** [comment]
@3v1n0 that already happens, because the server automatically sets Away status based on inactivity.

**Comment by jtdaugherty** [comment]
Also, the latest release of Mattehorn shows the current user's status as @glguy described above.

**Comment by jtdaugherty** [comment]
Since this is already supported via running server-provided commands, I'm going to close this.
