### ISSUE TITLE
Error "certificate has unknown CA" - with valid LetsEncrypt certificate

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [matterhorn-chat/matterhorn#576]
We have MatterMost setup on a subdomain of our website, everything on the subdomains is on a different local IP, with a wildcard Let's Encrypt certificate.

MatterMost works fine in the web browser and is trusted, works fine in the other apps, etc. But when I try to start MatterHorn for the first time I get:

    Error: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))

I've tried running as root, but that doesn't help. matterhorn -v gives:

    matterhorn 50200.6.0 (master@a2e55f7)
     using mattermost-api 50200.3.0 (master@a2e55f7)

**Comment by kquick** [comment]
Browsers will typically have their own CA cert management that is independent of the system.  I suspect you have already installed the CA cert for the Let's Encrypt into your browser, but for Matterhorn to see it it will need a system-level installation.  

The method for installing a CA cert differs somewhat for different OS's and distributions; for example, under debian, you would place the cert in `/usr/share/ca-certificates/local` and run `sudo dpkg-reconfigure ca-certificates`.  You will need to check the certificate installation instructions for your setup.

**Comment by CaerphillyMediaLtd** [comment]
> Browsers will typically have their own CA cert management that is independent of the system. I suspect you have already installed the CA cert for the Let's Encrypt into your browser, but for Matterhorn to see it it will need a system-level installation.
> 
> The method for installing a CA cert differs somewhat for different OS's and distributions; for example, under debian, you would place the cert in `/usr/share/ca-certificates/local` and run `sudo dpkg-reconfigure ca-certificates`. You will need to check the certificate installation instructions for your setup.

Thank you, sorry I thought they were the same.

**Comment by jtdaugherty** [comment]
@CaerphillyMediaLtd no problem - please let us know if you need anything else, or close this ticket if your issue has been resolved.

**Comment by jtdaugherty** [comment]
@CaerphillyMediaLtd on the assumption that you have what you need, I'm going to close this. Please re-open if there is more that you need!
