### ISSUE TITLE
Add UI or commands to view and control per-channel notification settings

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#582]
Right now Matterhorn respects per-channel notifications (as configured in the web client) but provides no UI or commands of its own to change or view those settings, requiring users to open the browser client to change or view them.

**Comment by jtdaugherty** [comment]
This ticket also needs to consider and address #585.

**Comment by immindich** [comment]
The per-channel notification settings are:
- Mute the channel
- Ignore mentions for `@channel`, `@here`, `@all`.
- Enable/disable email, desktop, and mobile notifications. Oddly enough I can't seem to find the option to change per-channel email notifications in the web client UI.

There is already a `/mute` server command, although Matterhorn does not know it exists. As mentioned in #585, we need to actually implement muting channels in the client. There should also be some visual indicator that a channel is muted. The web client does this by graying out the channel name and moving it to the bottom of the list. 

While it certainly would be possible to make the other preferences configurable through commands, I think that doing it through a UI might be a better choice. This would make it easier to see what the current preferences are. I'm imagining something like the "view message" window, which could also show other info that doesn't appear in the regular channel UI.

**Comment by jtdaugherty** [comment]
> There should also be some visual indicator that a channel is muted. The web client does this by graying out the channel name and moving it to the bottom of the list.

I think this could work nicely if we move the muted channels to a "Muted Channels" sidebar channel group. That way they're out of the way, as they are in the web client, but they're easily identifiable as muted just at a glance. That will be straightforward to do in the sidebar-building code.

> While it certainly would be possible to make the other preferences configurable through commands, I think that doing it through a UI might be a better choice.

I agree that having a UI would be the best approach, and we can continue to pass the `/mute` command through as we do now. As for the UI itself, a lot of stuff in `Brick.Forms` will make that easy to implement.

**Comment by immindich** [comment]
>I think this could work nicely if we move the muted channels to a "Muted Channels" sidebar channel group. That way they're out of the way, as they are in the web client, but they're easily identifiable as muted just at a glance. That will be straightforward to do in the sidebar-building code.

It's possible to mute DM channels as well as regular channels and it might look a bit strange to put them all together in one channel group. One other possible approach might be to have a subsection of each channel group for muted channels. But that would require more changes to the sidebar code and might make the UI too cluttered, since we already have three different channel groups.

**Comment by jtdaugherty** [comment]
Okay, that's good to know - in that case, how about just grouping them together at the bottom of their section but with a heading? That would require no sidebar changes, at least at a high level, to add subgroups. Combined with attributes or sigils to indicate muted channels, that might be something like
```
-Public Channels-
foo
bar
abc (m)
def (m)
-Direct Messages -
user1
user3
user2 (m)
```
(I'm not suggesting a `(m)` sigil - but something low-profile like that, similar to `<` and `~`, might be good. Not sure.)

**Comment by jtdaugherty** [comment]
Maybe something like
```
| channel 1              |
| channel 2            m |
| channel 3            m |
```
with a muted attribute (such as gray text) for the muted channels.

**Comment by dhenrich** [comment]
Even if there was no UI, if we could get the branch merged that respects muted channels, that would very very helpful for those of us that need to idle in a number of channels.

**Comment by jtdaugherty** [comment]
@immindich I recall you saying recently that you had only a bit more to do on this before it can be ready. Do you have any thoughts on a timeline for completing this?

**Comment by immindich** [comment]
@jtdaugherty I could probably block out some time tomorrow afternoon. If that isn't enough time to complete the UI, I should at least be able to test what I currently have get it into a state that can be merged.

**Comment by jtdaugherty** [comment]
As of b5f428f9ff6315b6ad6e3a2182b131f334136619 muting settings are now respected and displayed in the channel list.

**Comment by immindich** [comment]
@jtdaugherty That's from right before my PR, a5b91c2 should be the right commit.

**Comment by jtdaugherty** [comment]
Whoops, thanks!

**Comment by jtdaugherty** [comment]
This work is now nearly complete on @immindich's `feature/notify-prefs` branch.

**Comment by jtdaugherty** [comment]
Hey @immindich - @kquick and I were thinking it would be nice to make a release soon and we were hoping this could be included. Do you have an idea at this point of when you will be ready for us to review this branch?

**Comment by immindich** [comment]
@jtdaugherty I've been on the road for the past few days and haven't had as much time as I thought I might. I think I only need to add some help text and do a bit of testing, so I imagine I could have everything ready by Monday afternoon.

**Comment by jtdaugherty** [comment]
Okay, thanks @immindich - have a good trip!

**Comment by immindich** [comment]
Just opened #650 which I believe should resolve this.

**Comment by jtdaugherty** [comment]
Thank you, @immindich - we'll take a look!

**Comment by jtdaugherty** [comment]
@immindich's work is now merged to `develop` so this is done!
