### ISSUE TITLE
Support for logging incoming messages

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#583]
Other terminal-based chat clients tend to support logging of incoming user messages to support offline message searching. Matterhorn currently does not support any such logging. This ticket is a place to work out how we might do that. Some questions that come to mind:

* Incoming messages are in Markdown format. Should the Markdown be logged directly? Or should it be rendered as plain text? Should the user be able to choose? (My personal preference is: no user choice and one log format only. The question is, which format is least surprising and most useful?)
* Should it be possible to enable or disable message logging on a per-channel basis? Or is this on/off for all channels that the user is subscribed to?
* Will message logging be configurable in the configuration file or by some other means?
* Where will message logs be kept and how will we ensure that they are relatively discoverable and disambiguated by server? (We currently use team IDs to disambiguate history files, for example, but of course team IDs are not human-friendly.)
* How will message edits and deletions be represented in the log? (My preference is to feature then as their own log entries indicating the message that was edited or deleted.)

Other thoughts:
* To ensure user-friendly search support, the message logs should be divided up with one file per channel.
* I'll go ahead and claim that it isn't worth trying to ensure that logs are contiguous when a user reconnects. The principle here is simple: log what you have when you see it, but don't worry about gaps in the log (but maybe put markers in the log to indicate when the client connected).

**Comment by dpb1** [comment]
Thanks for putting this up @jtdaugherty.  As you asked for some opinions, I think it helps to look at weechat's features here, which are fairly easy to grok: 

https://weechat.org/files/doc/stable/weechat_user.en.html#logger_plugin

Basically, you have the gist of the configuration necessary in your bullet points

- log directory
- on/off per channel (though this is not overly useful for me personally, as disks are cheap)
- all this in the config file would be reasonable
- logs divided up one per channel/conversation makes sense
- most IRC clients give some way to rotate these files, usually with a filename/directory pattern, and will do it as frequently as once per day.  Personally, not something I particularly care about, as tools like logrotate already exist, but I expect someone would appreciate that feature.
- storing in markdown seems to make sense as that is the incoming format, and it's meant to be *just text* anyway
- and I don't think contiguous logs matter that much, it's just a record of what was viewed.  If there are a few duplicates, or if edits generate a new entry, or if reconnects had a gap, that would seem expected.

**Comment by jtdaugherty** [comment]
Thanks @dpb1!

**Comment by setharnold** [comment]
What would happen for edited or deleted messages? matterircd users of course see all these exposed as they happen, web client users see the end results only (I think, I didn't use it more than a few days). I could see benefits to logging the changes, logging the intended deletion; I could also see benefits to just doing the edits and deletes and modifying old logs, too.

**Comment by jtdaugherty** [comment]
That's a good question! I think to some extent it depends on the purpose of logging, which in my view is to *defeat* edits and deletes. 😊

**Comment by jtdaugherty** [comment]
I added a bullet to the main ticket summary about edits and deletes.

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.

**Comment by fictitiousexistence** [comment]
Hello. I was wondering if there was any recent new interest in this?
I use profanity for xmpp which logs messages as plain text.
This makes it simple to do some quick but advanced searches with grep.
/search in matterhorn does not work quite as well.

As of now I am using NOTIFY_JSON_LOG in the notifyV2 script to log messages.
The only downside is that only messages that come in while the client is up get logged.

Thanks.

**Comment by jtdaugherty** [comment]
Hi @fictitiousexistence - my time continues to be limited, so I don't currently have any plans to work on this. However, if someone else wanted to work on it, I would be happy to collaborate with them and provide guidance on the design and implementation.
