### ISSUE TITLE
Reflect one's own user status in the UI

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#594]
If I mark myself away, dnd or otherwise not online, I would expect that to be reflected in the UI; specifically around the [at]me in the top left of the UI?

**Comment by jtdaugherty** [comment]
Thanks for the report. This is indeed missing.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`: the status for the connected user appears just to the left of the username at the top of the channel sidebar, using the same layout / coloring as users elsewhere in the sidebar.
