### ISSUE TITLE
Provide clear indication of unread channels when the window is too large to show them

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#598]
Right now, if a user is a member of enough non-DM channels, any unread DM channel activity will not be visually indicated in the UI because the indicators that we currently provide -- the asterisk on the DM channel group header and the unread highlight of DM channels themselves -- will just not have room to be displayed. That makes it impossible to know the status of those channels, and when users want to prioritize visiting unread DM channels over others, that becomes a problem.

This ticket is about coming up with an additional visual indicator that is immune to this problem to give users a hint about the status of channels that are not shown in the sidebar.

For example, if the last line of the sidebar said something like
```
5 unread DMs
```
then that could address the concern. (That has the drawback that it also overshadows whatever would have been the last channel list entry in that spot, and that would need to be dealt with somehow since that channel could also have unread activity.)

I'm probably more of a fan of some kind of indicator that lives *outside* of the channel list sidebar and that summarizes the unread state - such as at the top of the window, or at the top of the channel list.

**Comment by david-christiansen** [comment]
> That has the drawback that it also overshadows whatever would have been the last channel list entry in that spot, and that would need to be dealt with somehow since that channel could also have unread activity.

For my way of using it, this is not so big of a problem. The difficulty that #598 addresses only arises when the user is in enough channels that they are not all visible at once, so there will already be perhaps many channels whose status is invisible. Having *n*+1 be invisible instead of *n* matters less and less as *n* increases. For my typical window size, *n* is typically about 12, and hiding 13 rather than 12 channels is not a huge problem.

**Comment by jtdaugherty** [comment]
Thanks for following up! I agree with you that the drawback isn't big. I pointed it out mostly as a way of saying that taking that approach would create more work and another problem to solve and that it's something to be aware of. (It might not be a big drawback, but we still do need to have a story for how to deal with it.) That's also why I thought it would be good to explore other approaches that don't come with that drawback.

**Comment by david-christiansen** [comment]
Definitely!

**Comment by jtroup** [comment]
I've now reached the stage where I have to reduce my font size to like 5 (nearly unreadable) to fit my channel list on screen, so I would be very happy to test any fixes for this (even if it means building a branch from source), for whatever that's worth.

**Comment by jtdaugherty** [comment]
Thanks, @jtroup!

**Comment by jtdaugherty** [comment]
This has been addressed to some extent on `develop`; the channel list's header now shows the number of channels with unread activity. I saw "some extent" because that can still scroll off the screen if you are scrolled down in the channel list, so I don't think that completely addresses this issue.
