### ISSUE TITLE
Support C-Left and C-Right for moving over words

### ISSUE THREAD

**Issue by thsnr** [matterhorn-chat/matterhorn#599]
As a new user to matterhorn I encountered two small "paper cut" issues when editing messages.

1. Home did not skip to the beginning of the line: already discussed in #258 and trivially fixable by unbinding `scroll-top`. But just to note, it did not work for me even in multi-line mode: a regression or was this never implemented?
2. Moving over words with C-Left and C-Right did not work. Basically the same behavior as provided by M-b and M-f, just alternative keybindings. The former are widely supported by other terminals and editors and are more comfortable on my layout.

It would be nice to add support for C-Left and C-Right.

**Comment by jtdaugherty** [comment]
The issues behind (1) are nuanced enough that I'd like to handle that in a separate ticket to keep the discussion clear.

As for (2), I just pushed [a patch](https://github.com/matterhorn-chat/matterhorn/commit/e726afadb012f48d2abec7f0f9feb4ca112d6985) to a branch that makes it possible to rebind *most* of the keys that affect the main message editor's behavior. That work is somewhat experimental and there is more to be done, but that is the approach I wanted to take in lieu of the patch you submitted (thank you!). In investigating this ticket I realized that a great many editor bindings for the main editor were hard-coded. My feature branch is migrating those to rebindable events so they can be customized like the other key bindings in the application. To be clear, *some* bindings will not be rebindable, such as `Enter`,`Backspace`, arrow keys, etc. But the rest -- the ones with modifier keys -- are rebindable in that branch. As part of that, there are now key events in that branch for moving to the next and previous word that can be rebound to keys of your choice, such as `C-Left` and `C-Right`.

With that said, we aren't quite out of the woods yet. That branch is going to need a bit of testing, and the commit message for my patch mentions a bit more work that needs to be done. I'll see about getting to that as soon as I can.

**Comment by thsnr** [comment]
Thank you for the quick response!

I checked out `feature/rebindable-edit-keys` and can confirm that the following simple configuration worked as expected:

```ini
[keybindings]
editor-prev-word = C-Left
editor-next-word = C-Right
```

This is indeed a much better solution than hardcoding additional bindings.

**Comment by jtdaugherty** [comment]
Okay, thank you for testing. I'm going to do some more work on that before merging. If that changes status, I'll update here.

**Comment by jtdaugherty** [comment]
As of 7012d43e208fd667fed04b6420953c677cb06dd8, the `feature/rebindable-edit-keys` branch now addresses the issue I mentioned earlier.

**Comment by jtdaugherty** [comment]
This feature is now merged to `develop`.

**Comment by thsnr** [comment]
Thank you!
