### ISSUE TITLE
Support emoji completion with custom emoji disabled

### ISSUE THREAD

**Issue by thsnr** [matterhorn-chat/matterhorn#600]
# Description

Autocompletion of standard emojis fails if the server has disabled custom emoji.

Matterhorn version: 50200.8.0
Mattermost version: 5.20.2

# Steps to reproduce

1. Connect to a Mattermost server with custom emoji disabled.
2. Type colon (`:`) and TAB.

# Expected results

Autocompletion of standard emojis listed in `emoji/emoji.json`.

# Actual results

The following error is printed:
```
Custom emoji have been disabled by the system admin.
```

# Details

Since I cannot find this error string anywhere in the code base (although GitHub's search is kind of iffy sometimes), I assume that it is an unhandled error from the server when trying to fetch the list of custom emoji to supplement standard ones. Even if custom emoji are disabled, Matterhorn should ignore this error and complete standard emoji from the bundled JSON.

**Comment by jtdaugherty** [comment]
Thanks for the report! We'll investigate.

**Comment by jtdaugherty** [comment]
As of 928577e7397e061df5fef22f1dc56a90d32bf3fd this is now fixed in `develop`. Thank you!

**Comment by thsnr** [comment]
Just tested and can confirm that completion now works if custom emoji are disabled. Thank you!

**Comment by jtdaugherty** [comment]
Great, thanks for the report!
