### ISSUE TITLE
Join a channel dialogue should filter out channels I'm already on

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#602]
This a UI nitpick, but it'd be nice if the channel selector box that pops up after I run /join filtered out channels I'm already a member of, IMO

**Comment by jtdaugherty** [comment]
Thank you for the report! This used to be the behavior and is a regression introduced in e7fefb9f. I just fixed this in `develop` in 26b824c99314a6cb41260cf3480689a01879940e.
