### ISSUE TITLE
Support Favourite Channel feature

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#603]
The Web UI allows the user to 'star' a channel which makes it appear in a 'Favourite Channels' list in the sidebar, above everything except Unreads.  As/if our company migrates onto Matermost (=> the number of channels I'm in skyrockets), I would see an increasing desire for this feature in Matterhorn too.

**Comment by jtdaugherty** [comment]
Thanks for filing this.

**Comment by dhenrich** [comment]
Yes, this would be very useful.

**Comment by jtdaugherty** [comment]
Things to consider:

* What API call(s) the browser makes to manage favorite channel status (currently this looks like preference management)
* How to add a new type of preference to `mattermost-api`
* How to handle new preference change events in Matterhorn (`Matterhorn.State.Channels.applyPreferenceChange`)
* How to represent the favorite channels in a new sidebar section (`Matterhorn.Types.mkChannelZipperList` and `Matterhorn.Types.ChannelListGroup`)
* How to draw the new sidebar group (`Matterhorn.Draw.ChannelList`)

**Comment by jtdaugherty** [comment]
This was implemented quite a while ago (`/toggle-favorite` changes favorite status, and the channel sidebar displays favorites grouped together).
