### ISSUE TITLE
Transient screen corruption from GH bot post

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#604]
A large post from a Github bot to one of our internal channels causes transient screen corruption when I a) switch to the channel or b) try to view the specific message.

I've attached a couple of screenshots as thankfully there's nothing private in the message.  I'm not sure if there's a way for me to get the exact contents of the message in question.  I tried logging, but it doesn't seem to capture it.

[Matterhorn on switch to channel](https://people.canonical.com/~james/nx/matterhorn.png)

[The same message in the web UI](https://people.canonical.com/~james/nx/matterhorn2.png)

**Comment by jtdaugherty** [comment]
What happens in Matterhorn if you press `C-l` in the presence of this corruption?

Does this also happen with other terminal emulators?

**Comment by jtroup** [comment]
C-l doesn't do anything.  It's reproducible with xfce4-terminal (my default) and gnome-terminal on Ubuntu 20.04.  Are there any particular others you'd like me to try?

**Comment by jtdaugherty** [comment]
No need - I was just wanting to make sure this wasn't connected to a single terminal emulator.

Out of curiosity, is the server in question publicly accessible?

**Comment by jtroup** [comment]
Unfortunately not, sorry.

**Comment by jtdaugherty** [comment]
Are you by chance running a build from source?

**Comment by jtroup** [comment]
Nope, I'm using a pre-built binary from yourselves from matterhorn-50200.8.0-ubuntu-18.04-bionic-x86_64.  (Full disclosure, I'm using it from the [snap](https://snapcraft.io/matterhorn) but I can't imagine that would impact on terminal rendering...)

**Comment by jtdaugherty** [comment]
Now I am obliged to ask: have you tried running a release build directly from our releases list rather than using the snap?

**Comment by jtroup** [comment]
I have now.  Same result.

**Comment by kquick** [comment]
If you could provide the content that the bot is posting (via your MITM proposal or similar) that would be helpful for us in determining what's going on.   We definitely appreciate your persistence and we definitely would like to identify what's happening here.

**Comment by jtroup** [comment]
OK, I've got mitmproxy up and running in transparent mode and was able to capture some messages.  It'll take me a little to scrub the mitmdump output so I can be sure I'm not leaking anything, but in the meantime, please have a look at one of [the suspect messages](https://people.canonical.com/~james/nx/matterhorn-001.txt).  The thing that jumps out at me is the \r\n's.  What makes me suspicious about them is, if I [clean it up](https://people.canonical.com/~james/nx/matterhorn-002.txt) and paste it into the web UI, the resulting message does not cause corruption in Matterhorn.  (Obviously, as part of my clean up/copy+paste, the \r\n's became simple new lines.)

**Comment by kquick** [comment]
Thank you for the post.  The BOT post contained `\r` characters, which are normally stripped, but not in verbatim sections, and those interfered with the rendering to cause the corruption you saw.  This is now fixed on the `develop` branch.
