### ISSUE TITLE
No documentation on how to create a custom theme

### ISSUE THREAD

**Issue by mamyn0va** [matterhorn-chat/matterhorn#605]
I wanted to create a dracula theme for matterhorn, but I found no documentation.
I could do some reverse-engineering from src/Themes.hs, but I'm too lazy :)

**Comment by jtdaugherty** [comment]
Are you interested in creating a new *built-in* theme? Or just a theme in your own configuration file for your own personal use/distribution?

**Comment by jtdaugherty** [comment]
If you are interested in the latter, see `/help themes`.

**Comment by jtdaugherty** [comment]
@mamyn0va I'm going to close this on the assumption that you `/help themes` is what you want. If it isn't, please feel free to re-open.

Thanks!
