### ISSUE TITLE
Build on Debian buster

### ISSUE THREAD

**Issue by southerntofu** [matterhorn-chat/matterhorn#608]
Hi, i'm on debian buster i successfully built matterhorn. Since there's no docs/script for Debian on this repo i thought i woud list the steps:

- sudo apt install cabal-install
- cabal update
- ./build.sh

Minus #606 weird git issue before build, and #607 problems with trust anchor on connection it appears to work. Can't really test it without connecting to a server, though.

I did not install the dependencies listed in setup_linux.sh and yet it built successfully. Are they optional? Should i expect runtime errors?

**Comment by jtdaugherty** [comment]
Thanks for the report! I'm glad to hear that you got it building.

Our `setup_linux.sh` script is assumed to be used 1) on the platforms we support for binary releases and 2) on a fresh install of said platform. That's likely the reason why you didn't need it: you installed the required build dependencies by hand.

If you were able to build the software then it will work on the relevant server versions. If you don't have a server to connect to, though, I'm not sure what I can do to help.

This ticket doesn't seem like a bug report. Is there anything else we can help with relevant to this ticket before we close it?

**Comment by jtdaugherty** [comment]
@southerntofu I'm going to close this on the assumption that there is nothing else we need to do. Please reopen if you need something else!

**Comment by southerntofu** [comment]
Thanks, nothing to add on my end. I just wanted to share my experience to let you know it was "working" on buster to some extent. Though i've diverged from the idea of using this build because not having LetsEncrypt in the trust anchor is a no-go.

Would be nice to see matterhorn packaged for Debian. As it is upstream to several distros you support, this would probably make packaging easier for you. Please update this ticket if that is ever the case.

Thanks

**Comment by jtdaugherty** [comment]
Thanks! It's good to know that it works for you on Debian. For what it's worth, we do not have the resources to publish a Debian package in addition to our other releases. For now we only have the resources to publish binary releases for the platforms that we currently support. However, it is not uncommon for other volunteers to re-package our releases for specific platforms. Perhaps someone will volunteer to do that for Debian.

As for Matterhorn and LetsEncrypt, in case you are not aware (and it isn't clear from your comment above): the lack of a LetsEncrypt certificate in your system's trusted certificates is something that you can resolve and is unrelated to Matterhorn. If you are interested in installing LetsEncrypt's root CA into your system keychain, you can seek out resources for how to take care of that on Debian. It looks like browsers often work around issues for authorities like LetsEncrypt but command-line utilities tend to rely directly on the system-wide CA bundle. So some additional steps may be needed to get Matterhorn working, but those are specific to your distribution.
