### ISSUE TITLE
Support escaped quotes on Mac OS notification script

### ISSUE THREAD

**Issue by spidey** [matterhorn-chat/matterhorn#613]
I've realized that the current example notification script for Mac OS X is failing with some formatted and programming-related messages. I've traced it down to not escaping correctly embedded backslashes. For instance, if you try running the original script with a message such as "Try this: \n" it will fail. You can try with this command:

```
$ ./notify-macos 1 someone 'Try this: escaped quote \" error'
```

**Comment by spidey** [comment]
The solution is simple, just adding an extra replacement pattern to double the backslashes found in the message.

```
#!/usr/bin/env bash

set -e

mentioned="${1?}"
sender="${2?}"
message="${3?}"
message="${message//\\/\\\\}"
message="${message//\"/\\\"}"

if [[ $mentioned -eq "1" ]]; then
    title="Mentioned by $sender"
else
    title="Message from $sender"
fi

osascript -e "display notification \"$message\" with title \"$title\""
```

I may commit and submit a PR myself at a later date, even though I'm not a Haskell developer, I can test just the script by itself and by using Matterhorn.

**Comment by spidey** [comment]
It's not just the backslash that was causing the issue, but the escaped quotes.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thank you!
