### ISSUE TITLE
Editing a message doesn't clear the input field

### ISSUE THREAD

**Issue by spernsteiner** [matterhorn-chat/matterhorn#614]
Editing a message with `^S` + `e` pastes the text of the message being edited at the current cursor position, without clearing the input field first.  So if you type `1234` and put the cursor on the `3`, then go to edit some `old message`, you end up in edit mode with the text `12old message34` in the input field, instead of just the expected `old message`.  (The unsent text `1234` is also lost upon leaving edit mode.)

I'm on current `develop`, 50ba092632f6f5deb3b6f6b36e537db30b3acd90.

**Comment by jtdaugherty** [comment]
Thank you! This is now fixed in `develop`.
