### ISSUE TITLE
Unable to build cabal-dependency-licenses on 32bit ppc

### ISSUE THREAD

**Issue by ingvarha** [matterhorn-chat/matterhorn#615]
Checking out latest git a53f9f58  on my old 32-bit ppc box, I can't get matterhorn to build. It fails on cabal-dependency-licenses compile errors.

Environment: Ubuntu 16.04/powerpc, cabal 1.22.6.0

See attached command dump.

I have also tested Debian sid 32-bit ppc, which has a newer version of cabal, but ran into config issues.

Ingvar

[matterhorn_build_error.txt](https://github.com/matterhorn-chat/matterhorn/files/4633504/matterhorn_build_error.txt)

(Note that matterhorn-chat's fork of cabal-dependency-licenses is not open for reporting of issues. I don't know if this is a github thing or not.)

**Comment by jtdaugherty** [comment]
What version of GHC are you running in the failed PPC build?

**Comment by ingvarha** [comment]
This is version 7.10.3, downstream Ubuntu 16.04.

**Comment by jtdaugherty** [comment]
Also, some context would be helpful - are you attempting to build a release archive for that platform?

**Comment by jtdaugherty** [comment]
After doing some build testing, it isn't entirely clear *why* that build failure occurs. But it is likely to be either the version of GHC (7.10.3 is quite old) or the version of `cabal` (1.22 is quite old). With that said, you will likely have better results by installing a newer GHC (8.x) and a newer `cabal` (3.x) from this Ubuntu repository:

http://ppa.launchpad.net/hvr/ghc/ubuntu

Please add that to your sources list, get newer versions of the tools, and give the build a try.

**Comment by jtdaugherty** [comment]
Also, thanks for reporting this here; I just enabled issues on the `cabal-dependency-licenses` repository. I didn't know those were disabled.

**Comment by jtdaugherty** [comment]
@ingvarha I hope you are able to try out the PPA I linked above. Please let me know if that gets your build working.

I should mention that for the purposes of our project's supported platforms, PPC is not a supported platform - this just means we cannot commit to ensuring that the build works reliably on PPC-based systems because we don't include it in the set of platforms for which we regularly make releases. However, it *ought* to build provided your Ubuntu package database includes sufficiently recent versions of GHC and `cabal` (hence the PPA). I'm going to close this, but please re-open if you need more help!

**Comment by ingvarha** [comment]
> Also, some context would be helpful - are you attempting to build a release archive for that platform?

I'm just using an old ppc laptop for irc and mattermost :-)  It runs Ubuntu 16, as that's the latest Ubuntu version for this platform. I may switch to Debian, as they still do have a more or less supported version of Debian for 32-bit ppc.

**Comment by ingvarha** [comment]
I can't use that PPA, as it does not have packages for powerpc. I'll continue with Debian 10, as it has updated packages (cabal-install 2.4.0, ghc-8.8). I'll follow up by reporting against cabal-dependency-licenses.

Ingvar

**Comment by jtdaugherty** [comment]
Okay, thanks!
