### ISSUE TITLE
Ability to configure editing keybinding

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#617]
Personally I'd like to be able to move around by word with Ctrl+arrows or delete the previous word with Ctrl+backspace... Unfortunately it seems that matterhorn doesn't use the readline configurations from `~/.inputrc` for this, so it's unclear how change more advanced keys

**Comment by jtdaugherty** [comment]
The latest release of `matterhorn` does not support customizing the editing keybindings, but the upcoming release will support customizing most of them. If you can't wait for the upcoming release (in the next few weeks) then you might consider building from source on the `develop` branch.
