### ISSUE TITLE
Support viewing recent mentions

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#620]
In the browser view there's a "see recent mentions" view that de-facto does just a search for all the configured mentions.

Now, doing the same with `/search mention1 mention2` doesn't work as those terms are AND'ed, so I wonder if this could be automatized (preferrably in the default UI, without extra scripts) to automatically trigger a search for all the recent mentions.

**Comment by jtdaugherty** [comment]
Thanks @3v1n0, we will explore adding this feature.

**Comment by setharnold** [comment]
I'm sorely missing a `/lastlog -hilight` command, as irssi spells it.

There's enough latency in tab-completion in mattermost that I'm noticing many of my co-workers are skipping the `@` symbols entirely. It would be nice if whatever the matterhorn team comes up with can match on a user-supplied list of words, not just what mattermost thinks refers to the user in question.

Thanks

**Comment by jtdaugherty** [comment]
@setharnold It seems like the two things you mentioned are unrelated. Is that right?

**Comment by jtdaugherty** [comment]
(Unrelated to each other as well as unrelated to this ticket.)

**Comment by jtdaugherty** [comment]
I ask because I want to make sure I understand how these relate (if at all) and file other tickets for independent requests where possible.

**Comment by setharnold** [comment]
@jtdaugherty, hello, if I've misunderstood what this ticket is for, I'm happy to be redirected somewhere else. :)

My workflow with irssi, each morning, was to use `/lastlog -hilight` in every channel where I had a highlight to find conversations that are relevant to me while I was away. (I created an alias `/l` for this.) I use irssi highlights on my nickname, name, as well as project names that I'm interested in. (These highlights are visible on-screen at the moment they are used, as well as setting a special activity indicator on the channel, and they raise the X11 `URGENT` flag to mark the client as needing my attention.)

I'd like to keep as much of this workflow as possible: make it easy to find every reference to me, by `@sarnold`, `@seth-arnold`, `sarnold`, `seth-arnold`, `Seth`, etc., as well as other important words, in all the channels I'm in, so I can sort through the thousands of messages to find the dozen references to me, or something I am responsible for.

To be clear, I'm not asking specifically for `/lastlog -hilight`; weechat's similar feature of using `alt+p` and `alt+n` to jump through highlights is probably better overall, as conversation context will be visible: https://weechat.org/files/doc/devel/weechat_faq.en.html#search_text

I'd just like some help to find references to me, or things I care about, among the thousands of messages. And I'd like some flexibility there to recognize things beyond just "my name", or an http rest api representation of me, etc :)

Thanks

**Comment by jtdaugherty** [comment]
@setharnold Thanks for your clarification! While this ticket is indeed about providing something similar to your description of `/lastlog -hilight`, I can at least say that Matterhorn already supports indicating which channels include mentions. The mentions are user-configured, although currently the configuration of the mentions can only be done in the web client. For example, if you set up `blah` as a mention keyword in your web client, then Matterhorn will get notified of mentions based on that keyword and will indicate the mention in the channel sidebar with a parenthesized number (e.g. `(1)`) to the right of the channel name with activity.

I'll also point out that Matterhorn does not highlight the mentions, so that's one way in which the current functionality differs from what you describe. But I wanted to make sure you were aware that, at least right now, some of what you want is already available/possible. This ticket is about a UI to show a list of all recent mentions (rather than just indicating them as they arrive, as is currently implemented).

**Comment by setharnold** [comment]
On Mon, Jun 29, 2020 at 05:23:01PM -0700, Jonathan Daugherty wrote:
> @setharnold Thanks for your clarification! While this ticket is indeed
> about providing something similar to your description of `/lastlog
> -hilight`, I can at least say that Matterhorn already supports
> indicating which channels include mentions. The mentions are

This I've already seen -- when I arrived this morning and saw several
notifications in several channels, and spent several minutes hitting
page-up, enter, enter, enter, to demand-load the messages, and inspecting
every one to try to figure out which ones mentioned me, I figured I was
probably doing something wrong. :)

> user-configured, although currently the configuration of the mentions
> can only be done in the web client. For example, if you set up `blah` as
> a mention keyword in your web client, then Matterhorn will get notified
> of mentions based on that keyword and will indicate the mention in the
> channel sidebar with a parenthesized number (e.g. `(1)`) to the right of
> the channel name with activity.

Configuring this via matterhorn would be nice, but "fire up the web client
to configure it" works. It's a fairly rare event (once at initial
configuration, once or twice a year after that) compared against wanting
to check these highlights (several times each day).

> I'll also point out that Matterhorn does not highlight the mentions, so
> that's one way in which the current functionality differs from what you
> describe. But I wanted to make sure you were aware that, at least right
> now, some of what you want is already available/possible. This ticket is
> about a UI to show a list of all recent mentions (rather than just
> indicating them as they arrive, as is currently implemented).

Excellent, then I think I'm in the right place. :)

Thanks! I really do like Matterhorn, it's a lot more approachable to me
than the Mattermost web interface.

**Comment by jtdaugherty** [comment]
@setharnold This ticket is for a search interface to display a list of posts in which mentions have occurred, but what you're looking for is different. I've [filed a new ticket for that](https://github.com/matterhorn-chat/matterhorn/issues/632).

**Comment by 3v1n0** [comment]
Yeah, in weechat I use https://weechat.org/scripts/source/highmon.pl.html/ that does what the mentions view should basically do :)

**Comment by jtdaugherty** [comment]
To be specific: this ticket is about implementing the behavior provided by the web client's "See recent mentions (@)" button that appears to the right of the search input box.

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.

**Comment by jtdaugherty** [comment]
Thanks for piling on with your current situation, @setharnold. My time is still limited, so I'm keen to work with anyone who wants to tackle this feature.
