### ISSUE TITLE
notify script doesn't handle properly UTF8 chars

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#623]
I'm using the [notify script](https://github.com/matterhorn-chat/matterhorn/blob/master/notification-scripts/notify) that is shipped by default with matterhorn

However, when people sends me messages with UTF chars it fails:

```
Program: /snap/matterhorn/7/matterhorn-50200.9.0-ubuntu-18.04-bionic-x86_64/notification-scripts/notify
Arguments: ["1","friend","just had to run \128517"]
Exit code: ExitFailure 1
Stdout:

Stderr:
/snap/matterhorn/7/matterhorn-50200.9.0-ubuntu-18.04-bionic-x86_64/notification-scripts/notify: recoverEncode: invalid argument (invalid character)

Program: /snap/matterhorn/7/matterhorn-50200.9.0-ubuntu-18.04-bionic-x86_64/notification-scripts/notify
Arguments: ["1","friend","that\8217s 5pm"]
Exit code: ExitFailure 1
Stdout:

Stderr:
/snap/matterhorn/7/matterhorn-50200.9.0-ubuntu-18.04-bionic-x86_64/notification-scripts/notify: recoverEncode: invalid argument (invalid character)
```

**Comment by jtdaugherty** [comment]
What is the value of `LANG` in the environment where `matterhorn` is running?

**Comment by 3v1n0** [comment]
> What is the value of the `LANG` environment variable in the environment where `matterhorn` is running?

`it_IT.UTF-8`

**Comment by jtdaugherty** [comment]
Follow-up ticket for posterity: https://github.com/haskell/process/issues/187

**Comment by jtdaugherty** [comment]
@3v1n0 Based on my conversation on the ticket linked above, you might not have the `it_IT` locale generated. Here's what I did on my Ubuntu test system to resolve this:

* Run `sudo apt-get install locales locales-all`
* Uncomment `it_IT.UTF-8 UTF-8` in `/etc/locale.gen`
* Run`sudo locale-gen`

**Comment by 3v1n0** [comment]
@jtdaugherty so that's already the case here...

But still not getting this properly, although the problem is when i'm running this in a confined environment (using a snap package) and so where I can't perform such actions.

**Comment by jtdaugherty** [comment]
Thanks, that's an important detail! You'll need to get in touch with the creator of the Snap package; we don't support Snap and did not make the package. It appears that Snap packages may sometimes have issues with compiled locales (which is what is going on in this case). Here is an example:

https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758

**Comment by cbay** [comment]
I have a similar issue, although it's *not* caused by a missing locale. Here's what the notification script receives:

```
{"from":"foo","mention":false,"message":"Ã§a va ?","version":2}
```

You can see that the encoding is wrong, it should be:

```
{"from":"foo","mention":false,"message":"ça va ?","version":2}
```

My `LANG` is set to `en_US.UTF-8`, which I do have:

```
$ localectl list-locales    
C.UTF-8
en_GB.UTF-8
en_US.UTF-8
fr_FR.UTF-8
```

I have also tried setting `LANG=C.UTF-8`, no difference.

**Comment by jtdaugherty** [comment]
@cbay Thanks! Please report problems using new tickets if there are no open tickets exactly matching your problem. If they're duplicates, I'll let you know and we can close in lieu of older/open tickets. I've opened #781 for your report above.
