### ISSUE TITLE
customized sounds

### ISSUE THREAD

**Issue by bladernr** [matterhorn-chat/matterhorn#624]
For at least the desktop app, please add the ability to add custom alert sounds.  I have mild hearing loss and generally have to use specific sharp sounds for alerts, otherwise they end up lost in the background noise.  For IRC, I have a specific audio file I use (it's a wav, so worries about mp3 or other codecs), and since the app (and web apps) already have an alert tone, it would be awesome to be able to change that alert tone to something else.

**Comment by jtdaugherty** [comment]
Hi @bladernr - did you perhaps mean to report this on the official Mattermost client?

**Comment by bladernr** [comment]
Perhaps... this was the lnk I was given when I asked about this internally at my company, and I just filed it... sorry if I got the wrong project.

**Comment by jtdaugherty** [comment]
No problem! Matterhorn does not specifically support sounds at all (although sounds *could* be triggered when the activity notification script is run). It does seem like your request is better off submitted to the official Mattermost project. Matterhorn is not affiliated with the official project at all. Good luck!
