### ISSUE TITLE
ARM release

### ISSUE THREAD

**Issue by Kabouik** [matterhorn-chat/matterhorn#631]
The README strongly recommends using a release version instead of building Matterhorn, but as far as I understand there are only x86_64 versions available. Yet, while I love using terminal-UI applications on my local computer, they are also very relevant on remote and headless machines, which are often arm-based. I believe an armv7 release would be very useful to run Matterhorn on Rasberry Pi, other single-board computers, as well as cheap servers. It could also be used on phones that have a hardware keyboard (I use **many** terminal applications on my Fxtec Pro1 running SailfishOS).

Perhaps less important, but it seems the current releases also can't run on old machines like Debian Jessie:

```
$ ~/matterhorn$ ./matterhorn
./matterhorn: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./matterhorn)
./matterhorn: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by ./matterhorn)
./matterhorn: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./matterhorn)
```

For the same reasons, I think it would be nice to have more builds for greater compatibility with many systems since this is usually one (among others) of the great advantages of TUIs. However I understand that running it on such old systems may be a corner case, especially as Jessie is hitting end of life pretty soon.

**Comment by jtdaugherty** [comment]
Thanks for your report!

We do recommend binary releases over source builds *when possible*, but yes, that only really applies to the platforms we already support. I definitely agree that supporting more platforms would be great. However, our resources for supporting platforms are somewhat limited, especially when it comes to ARM. And you're right: our builds do not run on Debian Jessie. In fact, we don't support any Debian releases; only Ubuntu 18.04 is supported. I'm afraid that the only options for greater platform support are:
* Manual builds done by end users such as yourself (we're happy to provide support on how to do a build)
* Users who build and maintain packages for other distribution systems as a way to help out the project (e.g. I recently heard that apparently someone made a [Snap package](https://snapcraft.io/))

I'm going to close this since there isn't much we can do right now, but please let me know if you are interested in help with a source build!

**Comment by Kabouik** [comment]
While I can't guarantee that I would easily keep up with every new release, I'd be happy to build Matterhorn on ARM. However I think I don't have `ghc`/`cabal` available on my device, which is why I initially asked here if the architecture could be officially supported in future releases.

If there are ways to build Matterhorn without that, or to build them too relatively easily without breaking things, then please let me know. I would also probably package Matterhorn into RPM for easier distribution among the SailfishOS community through the [community-driven repository](https://openrepos.net). Hopefully, the binary wouldn't be built against libraries that are too specific to my system and could run on other ARM devices, but I suppose a more generic approach using cross-compiling or anything fancier than building on device would be best for that. I don't know how to do that though.

**Comment by jtdaugherty** [comment]
What Linux distribution are you running on your ARM system?

**Comment by Kabouik** [comment]
On this particular device, it's SailfishOS. I don't think haskell is available unfortunately (but it's required just for building Matterhorn, right?), but could compile it if it does not require going to deep into other dependencies.

**Comment by jtdaugherty** [comment]
To get Matterhorn compiled, you'd need to first build [ghc](https://www.haskell.org/ghc/) and then build [cabal-install](http://hackage.haskell.org/package/cabal-install).

**Comment by Kabouik** [comment]
I compiled `ghc` and `llvm` (which was required for cabal-install`, I think successfully, but unfortunately the `./bootstrap.sh` step for cabal-install failed at the end of the process with the following errors:

```
Linking Setup ...
/usr/bin/ld.gold: error: cannot find -lgmp
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:coSb_info$def: error: undefined reference to '__gmpn_add_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cp1j_info$def: error: undefined reference to '__gmpn_sub_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cp5T_info$def: error: undefined reference to '__gmpn_sub_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cpdJ_info$def: error: undefined reference to '__gmpn_mul_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cpnr_info$def: error: undefined reference to '__gmpn_add'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cpDG_info$def: error: undefined reference to '__gmpn_sub'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cpNp_info$def: error: undefined reference to '__gmpn_mul'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cquG_info$def: error: undefined reference to '__gmpn_cmp'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cqvP_info$def: error: undefined reference to '__gmpn_cmp'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cqv9_info$def: error: undefined reference to '__gmpn_cmp'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cqKs_info$def: error: undefined reference to '__gmpn_cmp'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:csPB_info$def: error: undefined reference to '__gmpn_divrem_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:csXv_info$def: error: undefined reference to '__gmpn_divrem_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cuM4_info$def: error: undefined reference to '__gmpn_sub_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cuMw_info$def: error: undefined reference to '__gmpn_sub_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cye5_info$def: error: undefined reference to '__gmpn_popcount'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cye5_info$def: error: undefined reference to '__gmpn_popcount'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cA1m_info$def: error: undefined reference to '__gmpn_tdiv_qr'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cAY2_info$def: error: undefined reference to '__gmpn_divrem_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cATV_info$def: error: undefined reference to '__gmpn_divrem_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cDAk_info$def: error: undefined reference to '__gmpn_mod_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(Type.o):ghc_3.ll:cDyc_info$def: error: undefined reference to '__gmpn_mod_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_rshift: error: undefined reference to '__gmpn_rshift'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_rshift_2c: error: undefined reference to '__gmpn_rshift'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_lshift: error: undefined reference to '__gmpn_lshift'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_get_d: error: undefined reference to '__gmpz_get_d'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_get_d: error: undefined reference to '__gmpz_get_d_2exp'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_gcd_word: error: undefined reference to '__gmpn_gcd_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_init'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_gcd'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_clear'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_tdiv_r: error: undefined reference to '__gmpn_tdiv_qr'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_and_n: error: undefined reference to '__gmpn_and_n'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_andn_n: error: undefined reference to '__gmpn_andn_n'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_ior_n: error: undefined reference to '__gmpn_ior_n'
/home/nemo/Templates/ghc/ghc-8.10.1/INSTALLDIR/lib/ghc-8.10.1/integer-gmp-1.0.3.0/libHSinteger-gmp-1.0.3.0.a(wrappers.o):wrappers.c:function integer_gmp_mpn_xor_n: error: undefined reference to '__gmpn_xor_n'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

Error during cabal-install bootstrap:
Compiling the Setup script failed.
```

I should have run `./bootstrap.sh` in a sandboxed directory, now I have a billion of extra files in `/usr/bin` and `bootstrap.sh` doesn't provide a way to revert the change it did.

**Comment by jtdaugherty** [comment]
@Kabouik I'm glad to see that you're making progress, although it looks like you're running into issues. As for the GHC compilation putting files in undesirable places, I believe that can be resolved by changing the installation prefix (probably an argument to `bootstrap.sh`). It should definitely be possible to build and install GHC into a location of your choosing (such as e.g. `/usr/local/ghc`) rather than sprinkling files all over the usual parts of the filesystem.

**Comment by Kabouik** [comment]
The problem is it's `bootstrap.sh` that I didn't run in a sandboxed directory, and I cannot find a way to undo what `bootstrap.sh` does. If it placed noew files and directories into preexisting directories, I have no idea how to revert those changes in a clean way.

**Comment by Kabouik** [comment]
Just wanted to update this issue to report that I successfully built `matterhorn` on ARM using a Debian LXC container on that same SailfishOS phone I was using above.

I had to edit `build.sh` to use `cabal new-build -j1` instead of `cabal new-build -j --enable-tests` though, else the building procedure would hard reboot my device all the time even at low CPU temperatures (I saw similar bug reports in my web searches on `cabal`). It took quite some time with `-j1` of course so it won't be easy to update regularly, but now `matterhorn` is working beautifully. This confirms ARM releases would be great and really convenient as ARM CPUs are now quite widespread and even entering the market of full-fledged computers (ultraportable laptops, new Mac, in addition to mostly SBCs and phones in the past).

I haven't continued my attempts on SailfishOS because building `cabal-install` and its dependencies filled up my storage and the fact that I cluttered my filesystem was a bit demotivating, but I assume it should work too with more storage, and `matterhorn` could be made to work on SailfishOS and distributed as a rpm package relatively easily (which was my initial plan).

**Comment by lynchc** [comment]
Just wanted to leave an update on here for my fellow arm users who are looking for a way to use matterhorn but maybe don't want to go through the hassle of the full build process. There is an aarch64 release available in nix. one command and I was up and running with matterhorn

**Comment by jtdaugherty** [comment]
Thanks, @lynchc!

**Comment by Kabouik** [comment]
> Just wanted to leave an update on here for my fellow arm users who are looking for a way to use matterhorn but maybe don't want to go through the hassle of the full build process. There is an aarch64 release available in nix. one command and I was up and running with matterhorn

Thanks. Speaking of Nix, a Guix package would be pretty nice too.
