### ISSUE TITLE
View Message scrolling "page" left and right

### ISSUE THREAD

**Issue by thsnr** [matterhorn-chat/matterhorn#642]
We often use code blocks for pasting snippets from service logs: one log event inhabits one output line, so line breaks have meaning and we do not want them to get wrapped. However, in some cases log lines can get very long with a lot of context being prepended before the actual message (timestamps, IP addresses, request identifiers, etc).

The View Message window allows scrolling code blocks left and right, but it does so one column at a time. With long lines this gets very tedious and there is no easy way to speed this up or to jump to the end of the line (`C-e` does not work).

Would you consider adding `page-left` and `page-right` keybindings similarly to `page-up` and `page-down`, which would scroll by some larger number of columns (up and down use `pageAmount`)? I imagine the default bindings would either add some modifiers to the left and right arrows or to the page up and down keys.

**Comment by jtdaugherty** [comment]
Thanks for your report! This is now done on `develop` as of 174ac3f52eda4066acd185dc0096ed75738b344a and will go out in the next release.
