### ISSUE TITLE
Explore more aggressive caching of autocompletion results

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#643]
Hello, I'm seeing enough latency in `<tab>`-completion of names to be distracting.

Running matterhorn locally, `<tab>`-completion feels quite a bit slower than using `<tab>`-completion in an `irssi` instance running in a datacenter 14ms away from me.

My company's mattermost instance is about 200ms away from me.

Thanks

**Comment by jtdaugherty** [comment]
The latency of tab completion results appearing also depends on your server's performance. But in this case, it will be at least 200ms, and likely a bit more. I'm not sure what your request is, though; we can't affect your network or server performance.

**Comment by setharnold** [comment]
On Thu, Jul 16, 2020 at 01:29:56PM -0700, Jonathan Daugherty wrote:
> The latency of tab completion results appearing also depends on your
> server's performance. But in this case, it will be at least 200ms, and
> likely a bit more. I'm not sure what your request is, though; we can't
> affect your network or server performance.

I was hoping it'd be something like that, in which case locally caching
the nicknames could provide a pretty huge latency win.

Thanks

**Comment by jtdaugherty** [comment]
> I was hoping it'd be something like that, in which case locally caching the nicknames could provide a pretty huge latency win.

Matterhorn actually does do some caching of autocompletion results, but there are limits to how long those results can persist because knowing when to invalidate them is tricky.

**Comment by setharnold** [comment]
On Thu, Jul 16, 2020 at 04:23:29PM -0700, Jonathan Daugherty wrote:
> Matterhorn actually does do some caching of autocompletion results, but
> there are limits to how long those results can persist because knowing
> when to invalidate them is tricky.

Ha, this is wonderful! (At least 'matterhorn' is a very well chosen name. :)

Anyway, some way to make tab-completion avoid server round-trips would be
immensely helpful.

Thanks

**Comment by jtdaugherty** [comment]
I'm going to close this since it has not been an issue since it was originally reported. If someone wants to work on it, we'll be happy to assist.
