### ISSUE TITLE
Display exact total user count in /members UI

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#645]
In Matterhorn, if I go to a large channel (over 500 members) and run /members, it says:

 [Found 100 results]

Additionally if i scroll down to the bottom, it stops after the first 100, with no option to continue.  Searching for someone later in the alphabet *does* find them.

By contrast, if I go to the same channel in the web UI, it tells me the exact user count.  If I click on the person icon and select 'View Members' it shows says:

 1 - 50 members of XXX total

(Where XXX is the exact user count).   At the bottom of the modal dialog is a 'Next' button to move to the next 50.

It would be nice if Matterhorn were a little closer to the Web UI in this regard, i.e.:
 1. Being able to know the exact user count
 2. Being able to page through users, without having to use search to narrow down the results

**Comment by jtdaugherty** [comment]
Unfortunately, I believe knowing the full count means fetching them all. To do that requires making API requests for all pages of users in the channel. Considering that that will be prohibitive for channels with many users, we opted not to do that. I don't think we can change that behavior unless the server API gives us something else to work with.

In the mean time, though, we could update the UI to somehow communicate that not all users will be shown, though.

**Comment by jtdaugherty** [comment]
I'll reopen this as a reminder to investigate what the web client does to get the exact count (perhaps it doesn't fetch them all).

**Comment by jtdaugherty** [comment]
I looked into this and found that when the web client shows the "view members" UI, it makes a `stats` request. The response looks like:
```
{"channel_id":"...","member_count":148,"guest_count":0,"pinnedpost_count":1}
``` 
We can easily integrate that into our UI.

**Comment by jtdaugherty** [comment]
This is now fixed on `develop` and will go out in the next release. Thanks!
