### ISSUE TITLE
Please stay in scrollback reading mode when using `o` to open an attachment or url

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#646]
Hello, in a handful of channels I will read all the scrollback. Sometimes I want to view attachments or open urls from several days earlier. Using `o` to open the attachment or url also exits the scrollback reading mode, which means I need to use pageup several dozen times to find the position where I opened the attachment or url.

I would like to stay in scroll-back reading mode after opening an attachment or url, so I do not need to find my old position in scrollback again.

Thanks

**Comment by jtdaugherty** [comment]
This is now fixed in `develop` via a new configuration option, `messageSelectAfterURLOpen`. The setting defaults to `False` which yields the current behavior. Setting it to `True` will get the behavior requested in this ticket. The new feature will be included in the next release.

Thanks!

**Comment by setharnold** [comment]
Fantastic! Thanks :D
