### ISSUE TITLE
Hitting 'o' (open command), 'v', 'a' and 'Y' in selection view resets selection

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#652]
While browsing back to read old messages using selection, if one of those action is hit (and cancelled in the case of `v` or `a`) will cause the selection to be reset, while I'd expect this to need an explicit request.

I.e.:
 - Hit Ctrl+S (or any page up) to init selection
 - Got to a message with a link, hit `o`
 - The link opens but the selection state is reset, loosing the mark

Or:
 - Select a message, hit `v`
 - Press Escape, to go back
 - Selection is gone

And again: 
- Select a message, hit `a`
 - Press Escape to cancel the reaction
 - Selection is gone

**Comment by jtdaugherty** [comment]
Thanks! As of 9f0d760d4867dceb21e7b33b1e02d0ae815348a1 on `develop`, where it makes sense to do so (all of the cases you listed above), actions in message selection mode maintain the selection and can be invoked repeatedly without having to re-enter selection mode. Other actions (reply, edit, delete, tag, pin, yank) do not, but that shouldn't be surprising.

**Comment by 3v1n0** [comment]
Well, I think that it's fine to exit selection for reply, edit and delete - once is confirmed - but for other actions no, as if I yank a text or just give a reaction I may still want to continue reading the backlog.

**Comment by jtdaugherty** [comment]
In my experience the common case to yank a message and then do something with it; having to hit `Esc` to quit selection mode doesn't make sense to me in that case, so I don't anticipate changing the behavior of that particular action.
