### ISSUE TITLE
mute functionality does not work when a post is edited

### ISSUE THREAD

**Issue by dpb1** [matterhorn-chat/matterhorn#655]
Just wanted to repeat my thanks here for the mute feature, it's made matterhorn MUCH more usable for me for the many channels I need to keep track of.  I have uncovered one error however, and wanted to bring it up...

## What happens?

If a channel is muted `(m)`, an edit by another user in that channel will trigger an unread notification in the channel sidebar.

## What would I expect?

edits, reactions, replys should not notify me of a message, unless I'm mentioned in some way.

**Comment by jtdaugherty** [comment]
Thanks, we'll investigate.

**Comment by jtdaugherty** [comment]
What was the channel type? Normal/public, DM, group, private, etc.?

**Comment by jtdaugherty** [comment]
I was able to reproduce the behavior on a normal/public channel, so it's likely the type is not relevant to the bug.

**Comment by dpb1** [comment]
Thanks @jtdaugherty, it does appear to be all channel types  from what I can tell (just to close that loop)

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.

**Comment by jtdaugherty** [comment]
I'll have a bugfix release out later today.

**Comment by jtdaugherty** [comment]
@dpb1 Here you go - https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.10.1
