### ISSUE TITLE
Make current topic available when changing it

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#658]
It would be nice if the current topic was available when changing it (as it is with the web UI) without resorting to copy and paste.  One possible way to do this would be (how irssi does it which is) to add the current topic to the /topic line when the user presses tab after entering '/topic '.

**Comment by jtdaugherty** [comment]
Thanks for the request! My preference is to make `/topic` pop up an editor window when it is not given any arguments. The editor window would be populated with the current topic string and would allow the user to edit or cancel.

**Comment by jtroup** [comment]
Sure, that works for me too, FWIW.

**Comment by jtdaugherty** [comment]
This has been implemented on the `feature/interactive-topic-editor` branch and is being tested now.

**Comment by jtdaugherty** [comment]
This is now done and merged to `develop`.
