### ISSUE TITLE
Add 'copy link' functionality for messages

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#660]
The web UI offers a 'copy link' functionality for messages; it'd be nice if Matterhorn offered it too.  (I'm assuming the link is generated server side and available via the API)

FWIW, with our server, the link looks like this:

  https://$ON_PREM_MATTERMOST.com/$TEAM/pl/$26_CHAR_HASH

**Comment by jtdaugherty** [comment]
Thanks! This is a duplicate of #562.
