### ISSUE TITLE
Any reason why using all the git@ uris by default (submodules)?

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#668]
As mentioned here https://github.com/matterhorn-chat/matterhorn/blob/8a3eae9d72dac7d3fc13f1d4d49380cdd9935abb/scripts/local-mkrelease.sh#L14

It blocks automated systems and so you replace it in various places, is there any rationale why not to use https uris by default?

**Comment by jtdaugherty** [comment]
We do it this way because HTTPS URLs are a pain for the development workflow, and automated systems can be automated to use `sed` to compensate.
