### ISSUE TITLE
Show correct reply-to parent in Preview

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#670]
When replying to a message, the server generates the "parent" link as the origin message for the entire thread, regardless of which message in the thread was replied to.

When using message-select mode, hitting 'r' to reply to a message shows *that* message as the parent message in the Preview pane rather than the origin message of the entire thread.  This is dissonant with the actual parent message displayed when the response has been generated to the server and displayed in the main window.

We should probably display the thread origin message in the Preview area.

**Comment by jtdaugherty** [comment]
I agree, it's weird. I thought about this in the past and thought that it could also be confusing to hit `r` on a message and see a different one in the reply preview. I'm okay with changing it but wanted to point that out.

**Comment by kquick** [comment]
Yeah, I don't think either option is great.  I also thought about showing both, but in addition to showing multiple lines, it would probably necessitate some explanation somewhere as well.  My thought is that if we show the origin thread in the Preview then it will match what is seen after submission, so it's the least surprising.

**Comment by jtdaugherty** [comment]
>  My thought is that if we show the origin thread in the Preview then it will match what is seen after submission, so it's the least surprising.

That makes sense to me.

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`!

**Comment by kquick** [comment]
Nice, thanks!
