### ISSUE TITLE
Support strikethrough text

### ISSUE THREAD

**Issue by jasom** [matterhorn-chat/matterhorn#671]
Many X11 terminals support it:

`echo -e "\e[9mtest\e[0m"`

Shows that this works on konsole, gnome-terminal, xterm, xfce4-terminal and terminology but not rxvt or rxvt-unicode

However, terminfo(5) does not appear to have any attribute for this.  They use sgr parameter 9 for altcharset rather than strikethrough as ECMA-48 would suggest, and indeed no infocmp dumps I inspected had any code to generate a CSI 9m

Perhaps this could be a configurable option?

**Comment by jtdaugherty** [comment]
For `rxvt` and `rxvt-unicode`, what is the behavior instead of showing strikethrough text?

**Comment by jasom** [comment]
It displays the text with no particular styling

**Comment by jtdaugherty** [comment]
For the record, `tmux` also does not support strikethrough.

**Comment by jtdaugherty** [comment]
As best I can tell, neither do `Terminal.app` or `iTerm2` on macOS.

**Comment by jasom** [comment]
tmux absolutely supports strikethrough in the sense that it passes sgr codes through unmolested, so if the terminal you are running tmux under supports strikethrough, then so will tmux.

**Comment by jtdaugherty** [comment]
According to https://github.com/tmux/tmux/issues/612, I don't think the situation is that simple. Still, for the record, there are some things that need to happen in order for us to support strikethrough:
* The [vty](https://github.com/jtdaugherty/vty) library needs to be patched to support strikethrough.
* The Matterhorn Markdown translation to `RichText` needs to be hacked to look for strikethrough syntax since the Markdown parser does not recognize it (strikethrough is not a standard markdown feature).

**Comment by jasom** [comment]
Thanks for finding that tmux issue; I was able to trace things down.

`infocmp -x` shows the user_caps and includes the smxx capability for strikethrough, which tmux supports, so that would be the start for updating the vty library.

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
Strangely, even though I am not seeing working strikethrough in iTerm2, [this relatively old iTerm2 ticket](https://gitlab.com/gnachman/iterm2/-/issues/5130) references a commit that appears to add strikethrough support.

**Comment by jasom** [comment]
I have no mac, but the source makes me think iterm2 v3.3 or later should support it.

**Comment by jtdaugherty** [comment]
Thanks! I'm curious, where did you get the clue about 3.3? I couldn't find a full changelog to find out which version added it.

**Comment by jtdaugherty** [comment]
The `echo` command above did not trigger strikethrough for me (the input text is printed verbatim) but this *does* work for me on iTerm2:
```
printf '\033[9mtest\033[0m'
```

**Comment by jtdaugherty** [comment]
(And also from within `tmux`.)

**Comment by jtdaugherty** [comment]
`vty` now has strikethrough support as of https://github.com/jtdaugherty/vty/commit/1dc2379e3c5b973d4527747d92648662fd5f04d7.

**Comment by jtdaugherty** [comment]
There is now [a feature branch of matterhorn](https://github.com/matterhorn-chat/matterhorn/tree/feature/strikethrough-text) to support strikethrough text. It depends on the unreleased changes to `vty` at the moment.

**Comment by jasom** [comment]
The echo command is specific to bash.  the "-e" option is non portable, but printf is.

**Comment by jasom** [comment]
Thanks for implementing this in approximately zero time.

**Comment by jtdaugherty** [comment]
The `vty` changes are now released in 5.31: http://hackage.haskell.org/package/vty-5.31

**Comment by jtdaugherty** [comment]
Strikethrough support is now merged to `develop` and will go out in the next release. Thanks!
