### ISSUE TITLE
Flagging not working as expected with Mattermost 5.27.0

### ISSUE THREAD

**Issue by dhenrich** [matterhorn-chat/matterhorn#672]
As of 5.27, flagging a message is not represented in the UI. It does it get "flagged" in the sense that you can view it with meta-8, but it doesn't get reflected that it's flagged and you can't unflag it. I also notice in the web UI that they have transitioned from flagged to saved in terms of terminology and display so I don't know if it's related.

**Comment by jtdaugherty** [comment]
Can you file a new ticket for the disconnection issue?

**Comment by jtdaugherty** [comment]
Also, just to be explicit: which version of Matterhorn are you using?

**Comment by jtdaugherty** [comment]
And: what was the version of Mattermost you were were last using where flagging worked for you?

**Comment by dhenrich** [comment]
50200.10.1

**Comment by dhenrich** [comment]
We upgraded from 5.23.1 (that worked fine) to 5.27.0 that doesn't. As we didn't use versions in the interim I can't tell you when exactly it broke. I did peruse the release notes and I'm not seeing it detailed where the behavior changed but maybe I missed it during my skimming.

**Comment by jtdaugherty** [comment]
Okay, thank you - that will still probably be helpful information for us.

**Comment by jtdaugherty** [comment]
@dhenrich What platform are you on? I have a fix and I'd like to see I can make a binary for you to try out.

**Comment by dhenrich** [comment]
I'm on Ubuntu but I don't mind building from source if you have a branch.

**Comment by jtdaugherty** [comment]
Great! In that case:
```
$ git pull
$ git checkout bugfix/50200.10.0
$ git submodule update
$ ./build.sh
$ ./run.sh
```

**Comment by jtdaugherty** [comment]
(I was able to reproduce the flagging and disconnection issues and resolve them on that branch.)

**Comment by dhenrich** [comment]
I can confirm the flagging now works and I haven't seen the disconnects. I'll watch it tomorrow and then confirm here. Thanks for the quick response!

**Comment by jtdaugherty** [comment]
Great! Thanks for testing and reporting this. The issues are related: an unsupported websocket event (added by a recent release of the server) was causing a parsing exception in our websocket thread. Because that thread is also responsible for handling server events like flag status changes, it was dying and not handling those. That made it *look* like the flagging wasn't doing anything, but it was: the client just wasn't finding out about the result of the flag API requests.

**Comment by dhenrich** [comment]
I can confirm no disconnects as well, all looks good. Thanks again.

**Comment by jtdaugherty** [comment]
A bugfix release for this is now available:

https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.10.2

Thanks!
