### ISSUE TITLE
Wishlist: fuzzy matching for channel switcher

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#673]
One of the few things I still miss in Matterhorn compared to my IRC setup is fuzzy matching when switching channels.  For example given the following channel list:

 * TeamName Engineering
 * TeamName Internal
 * TeamName Outage
 * TeamName Tech Screen

I would like to be able to type 'tea&lt;space&gt;ou' and have it narrow down to 'TeamName Outage'.

**Comment by jtdaugherty** [comment]
Thanks for filing this. Right now our channel name matching is designed around the assumption that there is only one contiguous substring match. It would take significant work to implement fuzzy matching as you have described it while also continuing to support the features that it already has (matching by username, prefix, suffix). Unless someone else wants to volunteer to tackle this, I don't think we can plan on adding it. For now, my recommendation is for you to adjust your steps to 1) type `ou` and then 2) press `C-n` to get to the appropriate entry.

**Comment by jtroup** [comment]
FWIW, my digging into how it's done on Emacs suggests that fuzzy matching is either done by: a) inserting an implicit '.*' between every character, or b) treating ' ' as '.*'.  But I understand your perspective.  I guess maybe I need to start learning Haskell.  Thanks.

**Comment by jtdaugherty** [comment]
Thanks for that detail. I'll also add our new ticket label to this to mark it as something that we're not opposed to doing, but unable to do without more work.
