### ISSUE TITLE
Server v 5.28.1 + matterhorn 5200 = Error: HTTPResponseException "Server returned unexpected  (3,0,2) response" 

### ISSUE THREAD

**Issue by tiket18** [matterhorn-chat/matterhorn#676]
The server component of version 5.28 is currently being installed. Only version 5.2 is available to the client, in accordance with the declared principle of version compliance. 
I can download the client as a binary build, I can build from Aur (there are several options). They all give the same thing - the client in the terminal starts, you can enter the necessary parameters for connection, but in response the client says -

Error: HTTPResponseException "Server returned unexpected  (3,0,2) response"
![Снимок экрана от 2020-10-30 14-27-28](https://user-images.githubusercontent.com/18741088/97699967-16957700-1abc-11eb-8fce-87a311ebd6fd.png)

**Comment by jtdaugherty** [comment]
Presumably this is because your server is responding with a redirect for some reason. Matterhorn's authentication does not follow redirects (302 in this case) which is why it's behaving the way it is.

If you navigate to your Mattermost server in your web browser, what does the URL end up being? Have you tried pasting that URL into the "Server URL" field instead of entering only your hostname?

**Comment by tiket18** [comment]
#        location ~* ^.+\.\w+$ { deny all;}
#        location /socket.io/ { }

}

**Comment by tiket18** [comment]
I hate Microsoft - everything that is touched turns into .......
Now here's the git interface.

**Comment by jtdaugherty** [comment]
@tiket18 Thanks for the extra information, but it does not shed much light (to me) on why the server is giving a redirect response. My hypothesis is that the server is redirecting to a more canonical hostname than the one you are using. If you can capture the redirect response (e.g. using your web browser or a command-line utility like `wget` or `curl`) then that would be helpful in at least understanding what is going on here.

**Comment by tiket18** [comment]
Pidgin client works without any complaints.

wget https://mm.loftschool.com
--2020-11-03 12:30:19--  https://mm.loftschool.com/
Загружен сертификат CA «/etc/ssl/certs/ca-certificates.crt»
Распознаётся mm.loftschool.com (mm.loftschool.com)… 78.46.108.83
Подключение к mm.loftschool.com (mm.loftschool.com)|78.46.108.83|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 200 OK
Длина: 2859 (2,8K) [text/html]
Сохранение в: «index.html»

index.html                    100%[===============================================>]   2,79K  --.-KB/s    за 0s      

2020-11-03 12:30:19 (25,5 MB/s) - «index.html» сохранён [2859/2859]

curl https://mm.loftschool.com
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"><meta name="robots" content="noindex, nofollow"><meta name="referrer" content="no-referrer"><title>Mattermost</title><meta name="mobile-web-app-capable" content="yes"><meta name="application-name" content="Mattermost"><meta name="format-detection" content="telephone=no"><link rel="icon" type="image/png" href="/static/images/favicon/favicon-16x16.png" sizes="16x16"><link rel="icon" type="image/png" href="/static/images/favicon/favicon-32x32.png" sizes="32x32"><link rel="icon" type="image/png" href="/static/images/favicon/favicon-96x96.png" sizes="96x96"><link rel="stylesheet" class="code_theme"><style>.error-screen{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding-top:50px;max-width:750px;font-size:14px;color:#333;margin:auto;display:none;line-height:1.5}.error-screen h2{font-size:30px;font-weight:400;line-height:1.2}.error-screen ul{padding-left:15px;line-height:1.7;margin-top:0;margin-bottom:10px}.error-screen hr{color:#ddd;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}.error-screen-visible{display:block}</style><meta http-equiv="Content-Security-Policy" content="script-src 'self' cdn.rudderlabs.com/"><link href="/static/main.a33884eb1b67f1cb44c0.css" rel="stylesheet"><script src="/static/main.0f2d0e1224bffaa8a2da.js"></script><meta name="apple-mobile-web-app-title" content="Mattermost" /><meta name="apple-mobile-web-app-capable" content="yes" /><meta name="apple-mobile-web-app-status-bar-style" content="default" /><link rel="apple-touch-icon" sizes="76x76" href="/static/icon_76x76.png" /><link rel="apple-touch-icon" sizes="72x72" href="/static/icon_72x72.png" /><link rel="apple-touch-icon" sizes="60x60" href="/static/icon_60x60.png" /><link rel="apple-touch-icon" sizes="57x57" href="/static/icon_57x57.png" /><link rel="apple-touch-icon" sizes="152x152" href="/static/icon_152x152.png" /><link rel="apple-touch-icon" sizes="144x144" href="/static/icon_144x144.png" /><link rel="apple-touch-icon" sizes="120x120" href="/static/icon_120x120.png" /><link rel="manifest" href="/static/manifest.json" /></head><body class="font--open_sans enable-animations"><div id="root"><div class="error-screen"><h2>Cannot connect to Mattermost</h2><hr/><p>We're having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.</p><br/></div><div class="loading-screen" style="position:relative"><div class="loading__content"><div class="round round-1"></div><div class="round round-2"></div><div class="round round-3"></div></div></div></div><div id="root-portal"></div><noscript>To use Mattermost, please enable JavaScrip

I will delete the domain name later.

**Comment by tiket18** [comment]
This git in the hands of Bill Gates mutilated the curl text.

**Comment by jtdaugherty** [comment]
Thanks for the update, @tiket18. I'm not sure what to make of your post above. It looks like `wget` and `curl` aren't getting redirect responses at all.

Strangely, if I attempt to authenticate to `mm.loftschool.com` with Matterhorn, I don't get a 302 response (just failed auth, as expected). What do you make of that?

**Comment by tiket18** [comment]
Magic. It works.
I suppose the difficulties were related to the government's attempts to filter https & ssh due to its idiocy and terrorist attacks in France.

Please remove the direct reference to the domain name.
