### ISSUE TITLE
Show URL for attachments

### ISSUE THREAD

**Issue by Astranox** [matterhorn-chat/matterhorn#678]
Problem:
If matterhorn is run in a tmux-session on a remote machine it is difficult to open attachments/images as the URL is not shown anymore since v11.0. Before this change I could copy the url manually to the browser. (urlOpenCommand is not too useful in this setup)

Request:
Please show the post URL for attachments or make it configurable to do so.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
@Astranox while we can construct URLs for the attachments, that will still require a user to log into the web client in order to fetch the attachment itself. Rather than providing the URL and forcing the user to authenticate, I think it would be better to just make it possible to download the file directly to the system running Matterhorn. Would that work in your situation?

**Comment by Astranox** [comment]
Unsure, it doesn't reduce the tasks very much.
I think I also could do that by replacing the urlOpenCommand with wget with the current functionality.
But I'd still have to copy the file from the remote machine to the local machine.

Currently I have to open mattermost on my local machine, wait for it to finally load, and then browse to the channel containing the image/video/attachment to be able to see it.
Before I could just copy the link to my browser, and the attachment opened immediately, as I'm logged in anyway. (I have to use the web-version now an then, because handling of very long posts does not work properly in terminal, so the login-requirement is no obstacle.)

**Comment by hegga** [comment]
> @Astranox while we can construct URLs for the attachments, that will still require a user to log into the web client in order to fetch the attachment itself. Rather than providing the URL and forcing the user to authenticate, I think it would be better to just make it possible to download the file directly to the system running Matterhorn. Would that work in your situation?

This is the exact reason why I came here, to request this feature. Thank you for creating this awesome MatterMost client!

**Comment by jtdaugherty** [comment]
Thanks, @hegga!

**Comment by jtdaugherty** [comment]
Also related: https://github.com/matterhorn-chat/matterhorn/issues/586

**Comment by jtdaugherty** [comment]
The approach I described above (adding an option to download attachments) is now implemented in `feature/save-attachments`. The next step is for that to undergo review and additional testing.

**Comment by jtdaugherty** [comment]
`feature/save-attachments` is now merged to `develop` and will go out in the next release.

**Comment by Astranox** [comment]
this unfortunately does not fix my issue.
currently it shows the file name of the attachment when looking at the chat directly, like this:
`[attached: `Image Pasted at 2021-6-18 21-21.png`]`

when opening the attachment menu it also only shows the title, but not the url (same for post links, which only show the id, not the link to it, but this is less of an issue for me)

saving it locally does not help, as this is a remote machine.

an example for that is the opened attachment list (image), with links for the urls in posts, with the urls repeated in the second line; the post links with only one line showing the team and the post-id but no link, and the attachments with having the second line empty (missing the url to the attachment)

![shot_2021-06-18T21:32:28+02:00](https://user-images.githubusercontent.com/1219171/122609915-0f3cd100-d07f-11eb-8946-ecb027250ef7.png)

**Comment by jtdaugherty** [comment]
@Astranox I recognize that our solution is not ideal for your case. What may not be obvious to you is that *there is no URL for attachments*. They are only available by making API calls, which requires a client (either Matterhorn or the web client). The API endpoint URL for an attachment *could* be provided, but it would be useless because if you tried to access it in a browser, you'd get a response indicating that you made an invalid API request. So at present, due to the server's endpoint design for fetching attachments, we simply cannot provide an attachment URL.

**Comment by Astranox** [comment]
our instance should be a quite regular instance - having urls for attachments for us only depends on the id, which seems to be available, at least the urlOpenCommand does get the id for us.

the url itself looks like `https://domain.tld/api/v4/files/<postid_or_attachmentid>` (with no filename attached and no trailing slash!) - you need to be logged in to see the attachment, but if you are clicking the link works quite fine and opens the image (this also worked before, but i've verified it that it still works).
if i'm not logged in it complains about that, but I'm always logged in anyway.

for now i wrote a script that is called as urlOpenCommand which takes the id from the downloaded file path, deletes the downloaded file and writes the url to stdout, that I may click on it:

```
#!/bin/sh
echo $* | sed -e 's|/home/[a-z0-9]*/.cache/matterhorn/|https://domain.tld/api/v4/|' -e 's|/[^/]*$||'
rm -r ${HOME}/.cache/matterhorn/files/*
read line
```
I may not delete the `.cache/matterhorn/files` folder, as matterhorn just terminates the program with an error if this folder does not exist - if you like I can open a separate bug for that.

**Comment by jtdaugherty** [comment]
@Astranox it sounds like you have a workaround that works for you, which is great. I'm not sure what you mean about the error, but if you want to open another ticket for that with more details, we'd be happy to investigate.

**Comment by Astranox** [comment]
yes, but it is still only a workaround, because it still needs 2 steps to get to the actual url. i'll open a new issue for the termination thing.
