### ISSUE TITLE
Not clear which channels are unread when using FastlChannelSelect only

### ISSUE THREAD

**Issue by eyenx** [matterhorn-chat/matterhorn#680]
Hi

First of all thanks for this awesome TUI! 

I've got a feature request tho:

I do not use by default the ChannelList, as my CLI is rather compressed into only 1/5 of my screen (Using XMonad).

I know I can enabel it with useing <F2> and I then can see which channels have unread messages.

But I'd rather use directly The FastSwtichingMode to chose which channel to go to. But when using FastSelectMode, I only see which channel Groups are unread, but not which channels.

As far as I can read the code, I guess we are using `withDefAttr` here https://github.com/matterhorn-chat/matterhorn/blob/master/src/Matterhorn/Draw/ChannelList.hs#L202 to remove any Atributes.

I get it that it's need to remove formatting and colors to be able to focus on what I'm searching, but we could also add some kind of `*` not only on the group header but also on the Channel list? 

Thanks!

**Comment by jtdaugherty** [comment]
Hi @eyenx - the unreleased version of Matterhorn might have the behavior you want. In the unreleased version, unread channels appear with a different color in the fast selection mode the same way that they do in the normal channel list. We did some work (thanks to @benjaminselfridge) to make the fast selection mode more consistent with the normal channel list. Does that describe what you are looking for?

**Comment by eyenx** [comment]
As an example here is my Channel list when "visible" and when during "fast channel switch mode" with the same channel order

![screen173758](https://user-images.githubusercontent.com/1947882/101379803-fc1d9d00-38b4-11eb-89ec-2b5689f627f6.png)
![screen173803](https://user-images.githubusercontent.com/1947882/101379804-fcb63380-38b4-11eb-8a52-59c56c330ab4.png)

**Comment by jtdaugherty** [comment]
(To confirm, since you posted those images: in `develop` the fast selection mode looks just like the top image.)

**Comment by eyenx** [comment]
Perfect thanks! This can be closed then!

**Comment by jtdaugherty** [comment]
Okay, great! The change will be included in the next release. The best estimate I can give for the next release timeline right now is the next month or so.
