### ISSUE TITLE
Provide additional information to notification commands

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#681]
Right now the notification script API entails providing three command-line arguments to the notification command:
* A value of `1` to indicate that the user was mentioned, `2` otherwise
* The username of the message sender
* The message body

In addition there are other bits of information that it would be useful to provide, such as:
* A flag indicating whether the message was a DM
* A channel name, if possible
* The name of the team associated with the channel, if any (DMs have no associated team)

**Comment by jtdaugherty** [comment]
In terms of solutions, I don't think command-line arguments are going to be suitable or extensible enough to handle this extra data since so much of it is optional. Instead I am thinking that we'll need a "version 2" notification API that provides a JSON blob to the command's stdin rather than using command-line arguments.

In terms of compatibility, I am also thinking that we'll ned a "notification API version" config setting that defaults to "1" (the current behavior) that can be set to "2" for commands that want to use the new API.

**Comment by jtdaugherty** [comment]
@TieDyedDevil's work has been merged, so we now have a versioned interface for notification scripts. With that, we have a path forward for adding more information to the notifications. I'm going to leave this open since there were some ideas above about what we could add. Thanks, @TieDyedDevil!

**Comment by jtdaugherty** [comment]
Since this has been inactive for a while and I'm not sure when we can get to it (and because the work done on this puts things in great shape), I'm going to close this. We can re-open if desired.

**Comment by cbay** [comment]
I'd love to have the channel name and a DM flag as it would make notifications much easier to follow. The Mattermost application notifications include those details, for instance.

**Comment by jtdaugherty** [comment]
@cbay Thanks! Filed as #780.

**Comment by jtdaugherty** [comment]
@cbay for your awareness, https://github.com/matterhorn-chat/matterhorn/issues/780 is now closed and will go out in the next release.
