### ISSUE TITLE
switch between teams

### ISSUE THREAD

**Issue by bbbart** [matterhorn-chat/matterhorn#688]
Hi! Happy Matterhorn user here.

I was just wondering if easy switching between teams is supported by the Mattermost client. Coming from the web interface, I got used to easily switch between the five teams I am member of. Now, the only option I have found is `/quit`-and-restart.

Basically, I'm wondering if https://github.com/matterhorn-chat/matterhorn/wiki/Multiple-Sessions ever got implemented.

Thanks a lot!

(I'm posting this issue here, as in the documentation I read that issues could be posted to features from the web interface missing in Matterhorn.)

**Comment by jtdaugherty** [comment]
Hi @bbbart, you mentioned two different features, switching teams as well as multiple sessions. Matterhorn's latest release supports only team switching; if you are looking to run Matterhorn against multiple *servers*, then you will indeed need to run multiple instances of Matterhorn (just like the official web client). Which feature are you looking for?

**Comment by bbbart** [comment]
Oh yes, I see now that I am unclear.

I'm talking multiple teams on the same server, so it looks like I'm in for some good news then? :-)

**Comment by jtdaugherty** [comment]
I believe so. Have you upgraded to Matterhorn 50200.12.0?

**Comment by jtdaugherty** [comment]
@bbbart Have you tried the latest version of Matterhorn? It supports switching between teams with shortcut keys. The team list at the top of the window will list the teams that you are in, provided you are in more than one.

**Comment by bbbart** [comment]
I'm at 50200.10.1, the latest pre-compiled version available in Arch's AUR.

I see that version 50200.12.0 is available too, but not pre-compiled. As I'm on a low-spec machine, I tend to avoid packages that require compilation, but let me make an exception here. :-)

**Comment by jtdaugherty** [comment]
Okay. Please give the latest version a try and let us know how it works for you!

**Comment by bbbart** [comment]
compilation succeeded (using

**Comment by bbbart** [comment]
hm.. 

1. I downloaded the latest version from https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.12.0 (source code, .tar.gz)
2. unarchived and entered the directory
3. ran `./build.sh` which immediately returned an error: 
 ```The package directory 'submodules/mattermost-api' does not contain any .cabal file.```
  ```The package directory 'submodules/mattermost-api-qc' does not contain any .cabal file.```
4. removed two corresponding lines from `cabal.project`
5. ran `build.sh` again
6. things seemed to go well, but ultimately errored out again on `Failed to build SHA-1.6.4.4.` -> `Could not find module ‘Prelude’`

I guess I'll have to go hunting for some dependencies first. :-)

However, that first error (point 3 above) does seem like some oversight on your end, doesn't it? Do you want me to open another issue for that?

**Comment by jtdaugherty** [comment]
The error in step (3) is just because you didn't update the Git submodules; see `docs/BUILDING.md` for build instructions. But the SHA bit is weird to me and suggests there is something off about your GHC build environment or toolchain. We don't directly support Arch, so I can't comment; but perhaps if you follow the build steps I mentioned above, that might help.

**Comment by jtdaugherty** [comment]
Also, I don't know how Arch works but the error you mentioned about `libHSmatterhorn` does seem to be a problem with that package; perhaps the maintainer can help?

**Comment by bbbart** [comment]
yes, it seems that this `libHSmatterhorn`-error is known already: https://aur.archlinux.org/packages/matterhorn#comment-780102

about compiling myself, I wonder about the following:
 - I downloaded the .tar.gz from the release page here on github
 - the provided `build.sh` script doesn't work out of the box, first a `git submodules` is required
 - this `git submodules` command doesn't work either, as I donwnloaded the .tar.gz manually, I didn't clone the repository

Doesn't that mean that the source .tar.gz is useless? I eventually needed to `git clone` this repository anyway and not using the downloaded sources to initiate the build process.

Unless of course the source package is provided not for building, but for code inspection purposes.

Meanwhil, I have succeeded in getting rid of many build errors by simply installing more haskelle packages onto my system, but utlimately had to give up the compilation trials without success. I guess I'll just have to wait for Arch to come up with an updated matterhorn-bin package. :-)

**Comment by jtdaugherty** [comment]
If you're going to do a source build, I assumed you would clone the repo. But if you want to use the tarball, that should also be a valid way to build Matterhorn; but in that case you will need to remove the `cabal.project` file.

You're basically right, though - we don't get many users needing to build from source, so our documentation on that front is not especially developed. But I will update the build instructs to account for the tarball case.

I'm sorry to hear that this hasn't been a great experience for you. It does sound like the most straightforward thing to do will be to wait for the next Arch release, though. I don't know how much those lag behind ours.

**Comment by jtdaugherty** [comment]
@bbbart The updated build instructions can be found here: https://github.com/matterhorn-chat/matterhorn/blob/develop/docs/BUILDING.md

**Comment by bbbart** [comment]
Oh, the bad experience on the command line was more than compensation by the great experience right here.

Thank you for the great support. I'm sure I'll be able to switch between teams soon enough. :-)

**Comment by jtdaugherty** [comment]
Thanks @bbbart!

**Comment by bbbart** [comment]
Got the latest version now, and see that the team switching is implemented beautifully; it works exactly as I hoped it would

Thanks!

**Comment by jtdaugherty** [comment]
Great!
