### ISSUE TITLE
Add a command to attach a file to the message being composed

### ISSUE THREAD

**Issue by spidey** [matterhorn-chat/matterhorn#694]
Create a new `/` command to allow attaching with the filepath instead of restricting to navigating to the file from Matterhorn.
This would allow any file browser to be used to find files, avoiding navigating to big paths from the limited Matterhorn's file picker.

**Comment by jtdaugherty** [comment]
@spidey thanks for the request! Can you say a bit more about what you mean by "This would allow any file browser to be used to find files"? I'm not sure I understand how other file browsers would be involved here.

**Comment by spidey** [comment]
I mean that I can use the terminal/IDE/file explorer outside of Matterhorn to get the file path, then I can use something like `/attach <file_path>` to add it to the message.

**Comment by jtdaugherty** [comment]
Okay, thanks - that makes sense.

**Comment by jtdaugherty** [comment]
@karljs This actually might be a really good one for you to consider taking on once you are ready.

**Comment by karljs** [comment]
I'm looking in to this now.

**Comment by jtdaugherty** [comment]
I just merged @karljs's work on this to `develop`. It will go out in the next release.
