### ISSUE TITLE
Crash in absence of /etc/localtime

### ISSUE THREAD

**Issue by jvoisin** [matterhorn-chat/matterhorn#695]
I recently [packaged matterhorn for Alpine Linux]( https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/18488 ), but unfortunately, it crashes due to the absence of `/etc/localtime`.

Would it be possible to make matterhorn use UTC when this file isn't present?

**Comment by jtdaugherty** [comment]
Thanks for the report! Can you provide the crash output?

**Comment by jvoisin** [comment]
Sure:

```
matterhorn: /etc/localtime: openBinaryFile: does not exist (No such file or directory)                                                                                                            
```

**Comment by jtdaugherty** [comment]
@jvoisin Is an absence of `/etc/localtime` intended to be a valid thing for Alpine Linux? I suspect not having that file will break a great deal more than Matterhorn. Does Alpine keep it in a different location?

**Comment by jtdaugherty** [comment]
Also, related to this, have you run this?

https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-timezone

**Comment by jtdaugherty** [comment]
It also looks like Alpine Linux might use `/etc/TZ` instead of `/etc/localtime` to determine the time zone, in particular if uClibc is used. I would expect Matterhorn to just rely on the C library to get the time zone, but the string `/etc/localtime` is definitely embedded in the Matterhorn binary. I'll have to investigate.

**Comment by jtdaugherty** [comment]
Sure enough:
```
src/Matterhorn/TimeUtils.hs:28:lookupLocalTimeZone = getTimeZoneSeriesFromOlsonFile "/etc/localtime"
```
I'll look into how we can generalize that.

**Comment by jtdaugherty** [comment]
@jvoisin If I can get a patch together to improve this, would you be willing to give it a try on Alpine?

**Comment by jtdaugherty** [comment]
@jvoisin another request: if you have `/etc/TZ`, can you tell me what `file` says about it?
```
file /etc/TZ
```

**Comment by jvoisin** [comment]
I don't have an `/etc/TZ` either. uClibc isn't used, but [musl]( https://musl.libc.org ).

In the meantime, I installed the `tzdata` package, and `cp`'ed the right `/usr/share/zoneinfo/XX/XX` to `/etc/localtime` to make it work, then removed the package.

**Comment by jtdaugherty** [comment]
Okay, thanks. In the absence of another path to try, we'll just see about falling back to UTC as you originally suggested. Out of curiosity, do you have a `TZ` environment variable set?

**Comment by jvoisin** [comment]
```
~ # env | grep -i time
LC_TIME=en_US.UTF-8
XDG_RUNTIME_DIR=/run/user/0
~ # env | grep -i tz
~ #
```

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
And to confirm: with a `localtime` file put in place manually, have you had good results running `matterhorn` otherwise?

**Comment by jvoisin** [comment]
Absolutely, it's working great :)

**Comment by jtdaugherty** [comment]
Okay, that's great to know!

**Comment by jvoisin** [comment]
Well, I'm hitting #625 , but it's apparently being worked on in #569 :P

**Comment by jtdaugherty** [comment]
Unfortunately #569 is stalled. I'm not sure when it will be resumed because it depends on some overhauling of how character widths are computed. There are numerous issues with that and I'm not sure they're tractable in terminals.

**Comment by jtdaugherty** [comment]
(My last comment on #569 sheds some light on the issue.)

**Comment by jtdaugherty** [comment]
This should now be fixed on `develop` and will be included in the next release.
