### ISSUE TITLE
Consistently update user metadata when it changes

### ISSUE THREAD

**Issue by spidey** [matterhorn-chat/matterhorn#697]
I just noticed that a colleague still had a `[OOO]` tag in their nickname to show he was out of office. After notifying him, he mentioned it was already removed. After quitting and reopening matterhorn the new nickname was picked up indeed.

Is it possible to have it update the nickname every now and then? I'm usually running matterhorn under tmux, so it's running for a few days at a time.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
@karljs This one might also be a good one to take a look at. If you decide to take it on, I'll be happy to provide some details.

**Comment by jtdaugherty** [comment]
@karljs worked on a fix for this which is now merged to `develop` and will go out in the next release. Thanks for the report!
