### ISSUE TITLE
Attaching files is buggy on develop branch

### ISSUE THREAD

**Issue by karljs** [matterhorn-chat/matterhorn#702]
Currently, trying to attach a file using the file browser widget is buggy on the develop branch.  Expected behavior is:
- Press `C-x` to open browser
- Highlight file and press `Enter`.
- File browser is closed and the file is now added to attachment list

Actual behavior: after selecting the file as above, an asterisk is displayed and the file browser stays open.  Exiting via `ESC` or similar leaves the attachment list empty.

I bisected this and it appears that the commit that introduced the issue is:
350c7daf8d05cb5a3982ba5d2b57413fd6461218

I haven't yet had time to investigate exactly what is going wrong.

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
I believe this is the issue:
```haskell
      , mkKb FileBrowserSelectEnterEvent "Select file or enter directory" $
        mhHandleEventLensed' (csCurrentTeam.tsEditState.unsafeCedFileBrowser)
          FB.actionFileBrowserSelectEnter
```
In `Matterhorn.Events.ManageAttachments`, this is the key event handler for `Enter` in the attachment browser. That just calls `FB.actionFileBrowserSelectEnter`, which toggles the selected flag of the selected entry. The working implementation did forward the `Enter` event to the browser this way, but then it *also* closed the window and updated the attachment state. I believe 6c37f9045569b41f5a853161173a91026b633cc4 removed some code from `handleFileBrowserEvent` that needs to be reinstated.

**Comment by jtdaugherty** [comment]
Hmm, so I looked at `tryAddAttachment` and it *should* do the right thing (set the mode to `Main`).

**Comment by jtdaugherty** [comment]
Okay, I think the problem is that `tryAddAttachment` just isn't called on `Enter` now.

**Comment by jtdaugherty** [comment]
Fixed!
