### ISSUE TITLE
Single display of commands with optional arguments

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#704]
[Generated as a refinement of issue #657; see that issue for background context]

When the user begins typing a command in the command window, a command-completion list window is opened just above the entry box that shows commands which match (in name or description).  The TAB/shift-tab can be used to iterate through that list and select a command.  Typing a SPACE selects the currently highlighted (or typed) command and the command-window disappears.

Example:
```
    ...
    ------------Commands: 4 matches (Tab/Shift-Tab to select)------------------------
        /add-user - Search for a user to add to the current channel
        /add-user <@user> - Add a user to the current channel
        /log-mark <message> - Add a custom marker message to the Matterhorn debug log
     * /shrug [message] - Adds shrug emoji to your message
    ---------------------------------------------------------------------------------
    > /add#
```
(where the `#` marks the location of the cursor)

If the user then selects the command `/add-user` (via either typing or TAB selection) and hits space, the command window disappears and the user is simply left with:

```
    ...
    ---------------------------------------------------------------------------------
    > /add-user #
```

The concern raised by this issue is twofold:
1 - The `/add-user` is listed multiple times (due to different optional arguments), but the net result of selecting a specific entry in the list is the same
2 - Once selected, there is no more information available to the user to help them formulate the rest of the command they intended to use.

[Issue #657 also noted this behavior, but addressed a slightly different concern: that tabbing through the list would select both `/add-user` entries in sequence with no effective difference on the command-line.  The result of discussion on #657 was that when TABbing through a list, it would be more confusing to skip entries in the list than having multiple entries with identical results.]

**Comment by kquick** [comment]
Possible considerations for addressing this issue:

1. Display commands which differ only via optional arguments as a single entry in the available list.  Something along the lines of:
```
    ...
    ------------Commands: 4 matches (Tab/Shift-Tab to select)------------------------
        /add-user [@user] - Add a new user to the current channel (displays a search list if no user specified).
        /log-mark <message> - Add a custom marker message to the Matterhorn debug log
     * /shrug [message] - Adds shrug emoji to your message
    ---------------------------------------------------------------------------------
    > /add#
```

2. Keep the multiple entries, but once a command is selected, continue to display the list (only for exact command matches, not for words matched in the description) as a static display to help the user enter the rest of the command.  Something along the lines of:
```
    ...
    ------------Command syntax-------------------------------------------------------
        /add-user - Search for a user to add to the current channel
        /add-user <@user> - Add a user to the current channel
    ---------------------------------------------------------------------------------
    > /add-user #
```

There may be other approaches that could be taken here as well.

**Comment by jtdaugherty** [comment]
Thinking on whether we should keep this open, it occurs to me that this display issue is also going to require a pretty fundamental change in how the commands are represented internally. That's going to be a lot of work, and I'm not sure that the current behavior is bad enough to warrant that work. I'm going to close this due to low urgency, but let's re-open if someone wants to revisit this!
