### ISSUE TITLE
Support viewing admins in a channel + promoting members to admin

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#705]
The Mattermost web UI has a 'manage members' option available from the dropdown next to the channel name.  Matterhorn replicates much of this functionality through /invite, /remove and /members.  Things that I can't do in Matterhorn today (and fallback to the Web UI for) are:

 * Seeing who is an admin and who isn't
 * Promoting someone to admin

Please consider adding support for these two things?

**Comment by jtdaugherty** [comment]
@jtroup thanks for the request. Would you be willing to post some screenshots of the relevant bits of UI that you're relying on in the web client? That would help us know we are targeting the right things in this request.

**Comment by jtroup** [comment]
![matterhorn-x](https://user-images.githubusercontent.com/22205322/114791960-52c54700-9d7f-11eb-8cc1-7be338f45baa.png)

**Comment by jtroup** [comment]
![matterhorn-y](https://user-images.githubusercontent.com/22205322/114792013-683a7100-9d7f-11eb-8bac-f8536edfa33c.png)

**Comment by jtroup** [comment]
![matterhorn-z](https://user-images.githubusercontent.com/22205322/114792021-6f617f00-9d7f-11eb-8aac-8d8aa9bf8acd.png)

**Comment by jtroup** [comment]
@jtdaugherty Hopefully those 3 screenshots suffice, but let me know if you need more/something else; thanks!

**Comment by jtdaugherty** [comment]
I think those will be enough. Thank you!

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
