### ISSUE TITLE
Server returned unexpected (5,0,4) response

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#706]
Hello, I'm using popey's matterhorn snap, version 50200.12.0-42-gb87270a8, and have this message on screen:

```
[12:31:14]   An unexpected error has occurred! The exception encountered was:
HTTPResponseException "Server returned unexpected (5,0,4) response"
Please report this error at <https://github.com/matterhorn-chat/matterhorn/issues>
```

Thanks

**Comment by jtdaugherty** [comment]
@setharnold Thanks for the report! (Just in case it helps, that error isn't recoverable in Matterhorn so I suggest restarting if you see this again, but we can deal with the exception more gracefully by reporting to the user.)

**Comment by setharnold** [comment]
Thanks, that's very helpful :) I left this tab open to make it easy to see if there was more information necessary etc. when arriving to work this morning.

**Comment by jtdaugherty** [comment]
HTTP 504s are now silently ignored in `develop`. Thanks!
