### ISSUE TITLE
Support for yanking to Wayland clipboard (`wl-copy` command)

### ISSUE THREAD

**Issue by tgy** [matterhorn-chat/matterhorn#707]
Currently, yanking the content of a message (verbatim or not) is not possible because the `Hclip` library (called in [1]) assumes that any Linux system runs a X server.

An equivalent program to something like `xclip` exists in Wayland, called `wl-copy`.

I think extending the `Hclip` library is necessary for this to work... But I'm opening this issue.

[1] https://github.com/matterhorn-chat/matterhorn/blob/86fb97fae9aea66a2434fc085c1ff49c5bd96b86/src/Matterhorn/Clipboard.hs

**Comment by jtdaugherty** [comment]
@tgy Thanks for mentioning this! I recommend you open a ticket on [the Hclip project](https://github.com/jetho/Hclip). Once it is resolved there, we'd be happy to make any adjustments necessary to support it in Matterhorn (if any are even needed at all).

**Comment by verterok** [comment]
Apologize to resurrect this, but in case someone else wants/needs a workaround, This is a quick hack to get copy/paste working on wayland.
Add the following script in your PATH as xclip (before /usr/bin/xclip), e.g: drop it in ~/bin and run it like: `PATH=$HOME/bin:$PATH matterhorn`
```python3
#!/usr/bin/python3

import sys
import subprocess

args = sys.argv[1:]
cmd = 'wl-copy'
wl_args = ['-n']
if args:
    if '-o' in args:
        # requesting the contents, use wl-paste
        cmd = 'wl-paste'
    if '-selection' in args:
        sel_idx = args.index('-selection')
        if args[sel_idx+1] == 'primary':
            # use the primary clipboard
            wl_args.append('-p')

subprocess.check_call([cmd] + wl_args, stdin=sys.stdin, stdout=sys.stdout)
```

I filed https://github.com/jetho/Hclip/issues/7, but in the meantime this got me a working copy/paste

**Comment by jtdaugherty** [comment]
Thank you, @verterok!
