### ISSUE TITLE
Support searching for emoji using CLDR Unicode metadata

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#709]
[CLDR](http://cldr.unicode.org/) provides [json data](https://github.com/unicode-org/cldr-json) (also parsed by [emojibase](https://github.com/milesj/emojibase)) with approved keywords to search for emojis.

Would be nice if matterhorn could include it so that it would be possible to search for emojis using common terms and not only the shortcodes.

**Comment by jtdaugherty** [comment]
I doubt we will get to this ourselves, but if someone wants to explore what it would take to work on this, we'll be happy to discuss it. Currently we depend only on the JSON data that ships with the Mattermost server, and the versioning of that data would need to play well with whatever additional data is used for searching.
