### ISSUE TITLE
Enable changing channel while scrolled back

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#710]
This may be too esoteric to be worth considering, but I would find it incredibly useful if it were possible to, while scrolled back in one channel, switch to another.  

If it helps, my use case is that I often scroll back in an outage channel while working on RFO documents, but want to switch away temporarily to respond to a comment in a DM or other channel.  Ideally, I could switch channel (C-g) while scrolled back, and when I C-g back to the original channel, I end up back in the same place in channel history.

**Comment by jtroup** [comment]
This is a workflow I adopted in many years of using irssi; I notice the Mattermost web UI does **not** support it (in so much as, you can switch away, but your place in history is lost), so if Matterhorn did, it would be a differentiator.

**Comment by jtdaugherty** [comment]
I looked into this a bit. While I can definitely see the value in supporting this, it's not quite possible at the moment. The main reason is that there are keybindings that only make sense in message selection mode (i.e. channel scrolling) that need may clash with keybindings needed to interact with the rest of the UI (e.g. such as to switch channels). So I don't think we can support this at the moment. Thank you for the suggestion!
