### ISSUE TITLE
Support custom channel categories

### ISSUE THREAD

**Issue by XVilka** [matterhorn-chat/matterhorn#711]
#### Summary

If in Web-client Category is created it isn't shown in the Matterhorn

#### Steps to reproduce
1. Add a new category in Web client
2. Move some public  and private channels inside
3. Open the Matterhorn and see there are no categories

#### Expected behavior

Same categories as in Web

Also, there should be a way to create a new category and move in/out channels in the Matterhorn and then it should appear/change in the Web client.

#### Observed behavior (that appears unintentional)

No categories in Matterhon

Also related to the same missing feature/bug in Mattermost mobile client: https://github.com/mattermost/mattermost-mobile/issues/5387

**Comment by jtdaugherty** [comment]
Thanks for the request. It’s true that custom channel categories are not yet implemented in Matterhorn.

**Comment by jtdaugherty** [comment]
I don't have time to commit to supporting this, but this might make a good thing to work on for someone who wants to contribute!
