### ISSUE TITLE
Reactions flow off the edge of the terminal

### ISSUE THREAD

**Issue by RyanGlScott** [matterhorn-chat/matterhorn#715]
If you have a message with a _lot_ of reactions and a sufficiently narrow terminal, it will probably look something like this:

![matterhorn](https://user-images.githubusercontent.com/2364661/120668486-83129300-c45c-11eb-9bbe-4926097bd440.png)

Since there's not enough horizontal space to fit all of the reactions, would it make sense to overflow them like Matterhorn does for the message text itself?

**Comment by jtdaugherty** [comment]
Yeah, I agree, we should wrap them. Thanks for the report!

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks!
