### ISSUE TITLE
Maintaining Matterhorn Snap package

### ISSUE THREAD

**Issue by galgalesh** [matterhorn-chat/matterhorn#716]
The current maintainer of the Matterhorn Snap package [is looking for a successor](https://forum.snapcraft.io/t/seeking-owner-for-matterhorn-snap/24907) since he switched jobs and won't be using Mattermost anymore. Since the idea of Snap packages is that developers can publish directly to users, are you interested in taking over maintainership of the Snap package?

I'm happy to help anyone get started with snapcraft and help debug tough issues. If you have any questions, feel free to ask.

**Comment by 3v1n0** [comment]
I think this can be closed, I took over the maintainence. 

Snap code is now hosted at https://github.com/3v1n0/matterhorn-snap/

**Comment by jtdaugherty** [comment]
Thanks, @3v1n0!

**Comment by jtdaugherty** [comment]
I just added a section to the README to mention the Snap package in b41994f794be700731f67df874c81a8c3d972062.
