### ISSUE TITLE
The message input won't refresh

### ISSUE THREAD

**Issue by YukoOshima** [matterhorn-chat/matterhorn#717]
![image](https://user-images.githubusercontent.com/17468913/121628159-4b829700-caab-11eb-835b-7fbdc1eb024f.png)

How to resolve this issue?

**Comment by jtdaugherty** [comment]
Hi, thanks for the report. This is almost certainly because of the presence of the Unicode emoji in the screenshot. Matterhorn does not support those because they cause rendering issues in just about every terminal.

**Comment by jtdaugherty** [comment]
(As a clarification, I believe the input area *is* refreshing -- redrawing -- but because the layout calculations are wrong, it is not drawing in the right location on the screen, leading to the mess that we see above.)

**Comment by jtdaugherty** [comment]
If the channel above with the Unicode emoji can be renamed to remove the cake emoji, then I think this problem will go away.

**Comment by jtdaugherty** [comment]
[Here is the FAQ relevant to this ticket.](https://github.com/matterhorn-chat/matterhorn/blob/master/docs/FAQ.md#does-matterhorn-support-graphical-emoji)
