### ISSUE TITLE
Matterhorn just terminates if ${HOME}/.cache/matterhorn/files does not exist on urlOpenCommand

### ISSUE THREAD

**Issue by Astranox** [matterhorn-chat/matterhorn#719]
when opening the attachment window and pressing enter to run the urlOpenCommand, matterhorn just terminates if the folder `${HOME}/.cache/matterhorn/files` does not exist with the following error:

```
user@host ~/matterhorn-50200.13.0-centos-7-x86_64 $ ./matterhorn
matterhorn: /home/user/.cache/matterhorn/files/abcdefabcdefabcdefabcdefab: createDirectory: does not exist (No such file or directory)
```

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks!
