### ISSUE TITLE
Unexpected HTTPResponseException

### ISSUE THREAD

**Issue by benjaminselfridge** [matterhorn-chat/matterhorn#720]
Just encountered this error when switching channels:

```
An unexpected error has occurred! The exception encountered was:
HTTPResponseException "Server returned unexpected (5,0,3) response"
Please report this error at <https://github.com/matterhorn-chat/matterhorn/issues>
```

No idea what it means; my internet connectivity is strong, and I don't think I did anything weird.

**Comment by jtdaugherty** [comment]
These have become more common on the server where this was reported, and we're starting to think they may be related to connection limit exhaustion. I'm going to close this on that assumption, but if they keep happening, I'm sure I'll get reports from other folks who are seeing them.
