### ISSUE TITLE
Support custom sidebar categories

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#723]
A recent release of Mattermost added support for custom sidebar categories in the web client. This issue is a reminder to investigate what it would look like to support that feature in Matterhorn.

**Comment by XVilka** [comment]
Isn't this is the same as https://github.com/matterhorn-chat/matterhorn/issues/711 ?

**Comment by jtdaugherty** [comment]
Ah yes, thanks @XVilka!
