### ISSUE TITLE
Consider adding togglable truncation of long code blocks

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#725]
The Mattermost web UI elides long code blocks and allows the user to click a 'See more' button if they want to see the full thing.  As a result many of my colleagues paste hundreds of lines of text into code blocks and that's painful in Matterhorn.  Please consider adding similar togglable truncation of code blocks to Matterhorn?

**Comment by jtdaugherty** [comment]
Have you tried the "message view" window? `C-s`/`v` will allow you to scroll horizontally to view large code blocks.

**Comment by jtroup** [comment]
Thanks, I have used that (although I wish the dialog box was much wider by default)
, but my pain point is actually the main channel view; the 100s of lines paste wipes out everything else.

**Comment by jtdaugherty** [comment]
Oh, I see. I misunderstood the concern (many lines, not *long* lines). Thanks for clarifying.

**Comment by jtdaugherty** [comment]
I think we can add a toggle for this.

**Comment by jtdaugherty** [comment]
This is now implemented in 9493ffebd5c94bdbee8044c3b8b8d428929a152b. I'll update here once it is merged to `develop`.

**Comment by jtdaugherty** [comment]
There were a few adjustments to the original patch, but the functionality has been merged to `develop` and will go out in the next release.
