### ISSUE TITLE
Feature: auto-conversion of last message to reply

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#726]
Frequently I'll "reply" to a previous comment but forget to select the previous and use 'r' to generate an _actual_ reply.  This is even more awkward when it breaks an existing chain of replies.

It would be nice if there was a single key or short command that would automatically convert your last message from a top-level message to a reply to the message immediately before it.  There are corner cases where this might end up doing the wrong thing, but it should only be relatively safe (the message isn't lost, it's just mis-targeted), and it would presumably only work for a message within the "delete-able" timeframe set by the server.

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
