### ISSUE TITLE
Display of deleted messages

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#728]
In the web client, if a message is deleted, there is a visual display of the sender and time of message, along with the notation `(message deleted)`.  This happens only for messages deleted during the current web session; starting a new Mattermost web client will not show messages deleted before that client started.  Matterhorn does not currently display deleted messages at all.

There are two behavioral notes here:
1. The server still generates a notification, so in Matterhorn the channel is highlighted but going to the channel shows no changes from the previous status.
2. This is a small behavioral difference from the web client that may be somewhat surprising for users.

As a counter-note to the second note above, I find it nice to not have visual clutter from deleted messages, so I actually prefer the current Matterhorn behavior.

One possible resolution to this would be to add a configuration parameter controlling the display of deleted messages.  Presumably this would default to `Show` for user's new to Matterhorn from the WebUI, but could be changed by users with explicit intentions.

**Comment by jtdaugherty** [comment]
Thanks @kquick, a config option (defaulting to web client behavior) sounds good to me.

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
