### ISSUE TITLE
Search window: count messages, not result list entries

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#730]
I ran a /search term which, according to Matterhorn, returned 12 results (according to the title bar of the dialog) but only 9 are visible.  

If I run the same search in the web UI:

 * It shows 10 results
 * The last one (oldest) in the list is not visible in Matterhorn.

If it helps/matters, the search I ran was this:

/search after:2021-08-25 before:2021-08-31 elmo

I'm running the edge snap of Matterhorn:

  latest/edge:      50200.13.0-39-g49ec939e 2021-08-26 (229) 163MB -

**Comment by jtdaugherty** [comment]
(A note for myself for later or for someone else who gets to this first: the bug is that the total count displayed in the result window counts all list entries, *not* messages, meaning that it also counts the "date transition lines" that we insert.)

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
