### ISSUE TITLE
Search window: fix date lines to indicate dates of messages beneath them, not above

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#731]
When I do a search that spans multiple days, it took me a while to figure out what day each message was on, because the search results look like this:

```
search-result-1
search-result-2
search-result-3
------------------------------------------------ 2021-08-30 ---------------------------------------
search-result-4
search-result-5
------------------------------------------------ 2021-08-27 ---------------------------------------
search-result-6
search-result-7
search-result-8
------------------------------------------------ 2021-08-26 ---------------------------------------
```
It was until I compared the results to search in the web UI that I realised that the search results *above* the date came from that date.  Perhaps a simple UI tweak like adding an up arrow (or two) to the date lines would help?

**Comment by jtdaugherty** [comment]
Thanks for the report. The bug there is just that the date lines should correspond to messages below those lines. We'll fix this.

**Comment by jtdaugherty** [comment]
(That will also result in fixing the undesirable behavior that there is a trailing date line, as in the above example.)

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`.
