### ISSUE TITLE
Make /search interactive

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#732]
Similar to `/msg` and `/topic`, let's make `/search` open an interactive window if no search string is specified.

**Comment by kquick** [comment]
See also https://github.com/matterhorn-chat/matterhorn/wiki/Channel-History-Search

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
