### ISSUE TITLE
List dependencies in readme?

### ISSUE THREAD

**Issue by crdollar** [matterhorn-chat/matterhorn#734]
Had to track down that I needed ncurses-compat-libs for CentOS.

**Comment by jtdaugherty** [comment]
Hi @crdollar - thank you for the report! Out of curiosity, what version of CentOS are you running where this occurred?

**Comment by crdollar** [comment]
CentOS Stream 8

**Comment by jtdaugherty** [comment]
Ah, I see. That might explain what you ran into. The releases we put out for CentOS are for version 7, but we have not gotten any reports from users that this additional package was needed. (Maybe it was and nobody reported it, though.) I'll add it to the README. Thank you for letting us know!
