### ISSUE TITLE
 commitAndReleaseBuffer: invalid argument (invalid character) when typing UTF-8 characters

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#735]
If I type UTF-8 characters (e.g. ã or ö) into the terminal running Matterhorn, the warning below pops up

```
An unexpected error has occurred! The exception encountered was: 
fd:18: commitAndReleaseBuffer: invalid argument (invalid character)
Please report this error at <https://github.com/matterhorn-chat/matterhorn/issues>
```

It seems to be harmless; if I hit enter, my message goes through just fine.

I'm using the snap package from the edge channel (50200.13.0-61-g31ba5745) on Ubuntu 21.04 and kitty as my terminal.

**Comment by jtdaugherty** [comment]
Hi @jtroup, I didn't know what this was about and found [this](https://stackoverflow.com/questions/63746826/what-might-cause-commitandreleasebuffer-invalid-argument-invalid-character?noredirect=1&lq=1) that suggests the value of `LANG` in your environment might be involved. What is its current value?

**Comment by jtroup** [comment]
❯ env | grep -w LANG
LANG=en_GB.UTF-8
❯

Snaps run under a modified/confined environment, but I've confirmed (via 'snap run --shell') that the LANG variable is passed through.

**Comment by jtdaugherty** [comment]
Would it be possible for you to test the Matterhorn behavior with `LANG=C.UTF-8`?

**Comment by jtroup** [comment]
Ah, sorry, pretty sure this is a snap problem.  But, yes LANG=C.UTF-8 works.  I'll work with the snap package maintainer (hi @3v1n0 :-) to get this fixed.

**Comment by jtdaugherty** [comment]
Okay, awesome. Thank you!
