### ISSUE TITLE
Support spell checking via hunspell

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#736]
`hunspell` is used widely by many major applications such as firefox and libreoffice, so is often shipped in many systems.

Would be nice to add support for it so that one can avoid installing both aspell and hunspell dictionaries.

**Comment by jtdaugherty** [comment]
Hi @3v1n0 - thanks for the suggestion. Is there some reason why the current `aspell` support is not meeting your needs?

**Comment by toastal** [comment]
Central Thai has a(n experimental) Hunspell dictionary for use with LibreOffice. There's no `apell` dictionary. I don't have an immediate need for it, but LibreOffice may have a wider target audience and therefore more language options. I even raised my eyebrow at GNU only having one `en` language.

**Comment by jtdaugherty** [comment]
Thanks for the info, @toastal - that's helpful to about Thai. As for English, Aspell provides three variants, not one (CA, GB, and US).

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
