### ISSUE TITLE
Links in tables don't appear in C-o lists or open on 'o' in message select mode

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#739]
Hello, some of my teammates have written a friendly `/meet` command to generate a google hangouts link:

https://github.com/canonical-web-and-design/webteam-hubot/blob/4d18c6568eabb37c7c1850536fef31ccfb242be2/scripts/meet.js#L24

Unfortunately the link in the command's output won't open with the `o` keybinding and doesn't show up in the `CTRL+O` display.

Thanks

![meet](https://user-images.githubusercontent.com/5447148/137007343-90f5bb45-1fa5-490c-b429-d62f8e47ee88.png)

**Comment by jtdaugherty** [comment]
Hi @setharnold, it appears that the Markdown for the link is invalid, which would result in Matterhorn not parsing the Markdown and identifying the link. It could be that they're making an assumption about a Markdown extension. The markup I see in the screenshot that I am not familiar with is `=36 "Meet Icon"` within the link itself. As far as I know, the text in the parentheses should only be the URL and nothing else.

**Comment by jtdaugherty** [comment]
The issue with links inside of tables not showing up in the `C-o` list is now fixed in `develop`. Thanks for reporting this!

**Comment by setharnold** [comment]
Oh, sorry, it *was* intended for the other project :(

but it does look sharp, doesn't it? :)
