### ISSUE TITLE
Add support for completion to `/attach`

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#748]
It would be nice to be able to select a file via tab-completion, so basically it will be possible to do `/attach ~/[tab]` to go through the available files to attach in such path.

**Comment by jtdaugherty** [comment]
Thanks for the request. This is another example of context-sensitive completion similar to https://github.com/matterhorn-chat/matterhorn/issues/478. We don't currently have the resources to implement this so I'm going to close this to avoid lingering open tickets. But if anyone would like to work on this, we can re-open and I'll be happy to discuss it!
