### ISSUE TITLE
Deleted attachments remain in the list and crash matterhorn when selected

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#749]
Steps to reproduce:

 1) [In the web UI] msg yourself and attach an image
 2) [In Matterhorn] open the DM window with yourself
 3) [In the web UI] delete the message with the attachment
 4) [In Matterhorn] Hit C-o; noticed deleted attachment is still present
 5) [In Matterhorn] select deleted attachment

End result:

matterhorn: MattermostError {mattermostErrorId = "app.file_info.get.app_error", mattermostErrorMessage = "Unable to get the file info.", mattermostErrorRequestId = "4ifb9defqtri5bn1ao46nyeujy", mattermostErrorStatusCode = 404, mattermostErrorIsOAuth = False}

Mattermost server is 5.39.0; Matterhorn is 50200.13.0-67-g5161e1f3 from the 'edge' snap channel.

**Comment by jtdaugherty** [comment]
Thanks for the report! We'll investigate.

**Comment by jtdaugherty** [comment]
This has been fixed in `develop`. Thank you for reporting this!

**Comment by jtdaugherty** [comment]
The fix for this issue is now released in 50200.15.0.
