### ISSUE TITLE
Brackets in query string parameters are not considered part of the URL

### ISSUE THREAD

**Issue by taratatach** [matterhorn-chat/matterhorn#751]
Matterhorn ends links right before an opening bracket in a query string.

To reproduce : 

1. Post a message containing `https://example.org?param[]=one`
2. Try to open the generated link

**Expected behavior:**
`https://example.org?param[]=one` is opened in the browser.

**Actual behavior:**
`https://example.org?param` is opened in the browser.

Matterhorn version: 50200.15.0

**Comment by jtdaugherty** [comment]
Thanks for the report! The behavior that you’re seeing is the correct behavior because square brackets must be URL-encoded. For more details, see this page:

https://stackoverflow.com/questions/40568/are-square-brackets-permitted-in-urls
