### ISSUE TITLE
Support for `otpcmd` in the config.ini

### ISSUE THREAD

**Issue by msm-code** [matterhorn-chat/matterhorn#753]
Follow up for #228, especially [this comment](https://github.com/matterhorn-chat/matterhorn/issues/228#issuecomment-997544747).

As I've said, I personally don't think I'll use this feature, but I'm happy to implement it since it's closely related to my [previous PR](https://github.com/matterhorn-chat/matterhorn/pull/663).

1. Can one of the maintainers (@jtdaugherty I suppose) confirm that it's OK to implement? if yes, I'd like to work on it.
2. Do I understand correctly, that the behaviour should mirror that of `passcmd` and `tokencmd`, but the output of the command should be used as the 2fa token? The configuration key @jtdaugherty suggested is `otptokencmd`
3. is there anything special I should keep in mind? Especially @toastal and @eyenx.

**Comment by jtdaugherty** [comment]
1. Yes, this would definitely make sense to have and would be consistent with our other configurable commands that we provide for security and convenience purposes.
2. Yes, that's right!

**Comment by jtdaugherty** [comment]
As part of the changes I'd also like to get an update to `docs/sample-config.ini` that is written in a similar style (describe the setting and provide an example of the setting commented out with its default value).

**Comment by jtdaugherty** [comment]
Another request just to be explicit: also please make the PR against `develop`, not `master`.

**Comment by jtdaugherty** [comment]
Another thought I had, as I think ahead to how it might behave: if the command cannot be run for some reason, it would be nice if we can 1) show the OTP token UI and 2) report the error that we encountered when attempting to run the command, i.e. its nonzero exit status and perhaps the output of the failure in a temp file. (The output could be shown in the UI itself, but that could be unwieldy depending on how much output there was.)

**Comment by eyenx** [comment]
> 3. is there anything special I should keep in mind? Especially @toastal and @eyenx.

Only error handling comes to mind. And @jtdaugherty already mentioned it.


Thrnks for looking into this!

**Comment by toastal** [comment]
> error handling

Yes. If I've not yet unlocked my keyring via pinentry, I often get some pretty cryptic errors or no timeout in some applications.

**Comment by jtdaugherty** [comment]
@msm-code I wanted to check in since it has been a little while. Have you made any progress on implementing this feature? Is there anything I can do to help?

**Comment by msm-code** [comment]
Got it on my radar. I've worked on it a bit early this year, but was not 100% done. Then I became a bit busy last few weeks. Will get back to it soon and send a PR.

**Comment by jtdaugherty** [comment]
@msm-code checking in on this again: shall we close? Or is this something you'd still like to get to? If so, let's establish a timeline.

**Comment by msm-code** [comment]
Wow, a year has passed. Sorry, I had this in the back of my mind, but didn't realise 11 months have passed.

I would like to get to it. I've started working on it (presumably in February), become stuck on some language issue, decided to get a short break and here we are. I'll take another look at what I have soon, and if I become stuck again I'll just create a draft PR and ask instead of waiting months :).

As for the timeline - it's a bit hectic part of the year for me. Maybe I'll find an evening some time soon, but I don't want to be overly optimistic - what about solving this in a month (i.e. before Christmas).

**Comment by jtdaugherty** [comment]
@msm-code no problem. It's okay if you need help from us if something comes up and it's also okay if you need to put this down. I just wanted to check in and see if we should consider it an open task that anyone could work on to avoid it getting stuck in a limbo state. A month sounds like a good timeline on which to check in again. Thanks!

**Comment by jtdaugherty** [comment]
Thanks to work by @msm-code, this is now done on `develop`. Thanks, @msm-code!
