### ISSUE TITLE
Dhall config option alongside ini?

### ISSUE THREAD

**Issue by toastal** [matterhorn-chat/matterhorn#754]
Haskellers like types and config files are nice with them too. The neatest advantage is an Org can self-host the server and self-host the default Dhall configuration that the user can then extend beyond if needed--and this all happens in Dhall land so no extra features need to be added to support it.

**Comment by jtdaugherty** [comment]
Thanks for the recommendation. Dhall sounds pretty cool, but we're going to decline.
