### ISSUE TITLE
Add support for viewing threads

### ISSUE THREAD

**Issue by facundofc** [matterhorn-chat/matterhorn#762]
I believe this is the main pain point from matterhorn and the only one which occasionally forces me to open the web UI (:vomiting_face:).

It's about trying to read full threads. As it is now, threads messages are intermixed between different threads and un-threaded messages (just like in the main frame on the web UI). This makes it *very* difficult to properly ready a single thread.

I believe it would be nice if when on message select mode, there was a shortcut to go into "thread view mode." In my mind, this would open a pop-up just like `/search ...` does, but containing all messages pertaining to the currently selected message's thread (and, I guess, with the actual currently selected message pre-focused on the pop-up).

**Comment by jtdaugherty** [comment]
This is now mostly complete and undergoing testing on the `experimental/thread-window` branch.

**Comment by jtdaugherty** [comment]
This is now done and is merged to `develop`. It'll go out in the next release with details on how to use it provided in the changelog.
