### ISSUE TITLE
Users joining and parting a channel count as channel activity

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#763]
Hello,

When users leave or join a channel, it counts as 'channel activity' in the sidebar. I don't find this useful in practice.

I would like the 'channel activity' indicator to be made configurable, so only channels with unread messages would look active.

Thanks

**Comment by jtdaugherty** [comment]
Unfortunately for us, the channel messages that appear on join/leave events are system messages, so Matterhorn doesn't have control over whether those appear. I've seen others requesting the feature elsewhere but I don't think those can be disabled in account preferences or server settings.

**Comment by setharnold** [comment]
It's not the messages I mind; it's the cyan-highlighting in the sidebar that annoy me :)

Thanks

**Comment by jtdaugherty** [comment]
Yeah, the same is true there: aside from scraping the message text (which could change, making such scraping brittle), there isn't a way for Matterhorn to distinguish one type of server message from another in order to customize how we handle the activity indicator.

**Comment by setharnold** [comment]
oh :( dang. That's really frustrating. IRC has nice numerics for this kind of metadata. I just sort of assumed that mattermost would have something similar. Sigh. Thanks

**Comment by jtdaugherty** [comment]
Yeah, I wish it did! The protocol for some things like this could be better. :(
