### ISSUE TITLE
Release binary for ubuntu 22.04

### ISSUE THREAD

**Issue by Arpafaucon** [matterhorn-chat/matterhorn#774]
Hi Matterhorn team !

You probably don't remember me (I wrote the issue #656), but I did have 2 better years thanks to `matterhorn`! Again, a huge thanks for this project !!

Once again I'm back to ask you if you would be kind enough to provide a Ubuntu 22.04 binary in your future releases.

I am building the binary for myself already, but I suspect it could benefit others. I'd be glad to help if I can !

**Comment by jtdaugherty** [comment]
I've made a build for Ubuntu 22.04 and uploaded it for our most recent release here:

https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.17.0

I'll add Ubuntu 22.04 to our list of platforms for future releases. Thanks!
