### ISSUE TITLE
Access unread messages counter

### ISSUE THREAD

**Issue by oscarmcm** [matterhorn-chat/matterhorn#775]
Hi,

I use matterhorn with tmux on his own window, I was wondering if there's a way I can access the number of unread messages so then I can show up the number in tmux status line.

**Comment by jtdaugherty** [comment]
Hi @oscarmcm. Unfortunately, Matterhorn does not have a dedicated way to get at that information. However, you might consider using Matterhorn's support for working with external notification systems; perhaps you could query those in your tmux status bar configuration.

For details, see the information on `activityNotifyCommand` in `docs/sample-config.ini`.
