### ISSUE TITLE
New messages do not appear in thread window in DMs

### ISSUE THREAD

**Issue by chrnin** [matterhorn-chat/matterhorn#783]
Hi,

when I use thread window (ctrl+S -> t), existing messages appear but if I send or receive a new message, it doesn't display in the thread window whereas it is correctly displayed in the «main» window.

Thanks :)

Christophe

ps: I'm using ubuntu snap version 50200.17.0 (rev 356 from 3v1n0) and tested with 50200.17.0-4-g71917a58 but this problem looks unresolved.

**Comment by jtdaugherty** [comment]
Hi @chrnin - thanks for reporting this. I did a bit of work to reproduce the behavior, but I was unable to do so. Could you perhaps share a bit more? I have some questions:

* Is this on a public server that I could join and test, perhaps?
* Would it be possible for you to send a screenshot?
* What kind of channel you are in when this occurs? (public, private, a DM, etc.)

Thanks!

**Comment by chrnin** [comment]
Hi @jtdaugherty,
thanks for testing ! It's on a private mattermost server, maybe there's something with the configuration of this instance…

I tested more, and indeed for channels it works ! The issue append only in private messages (I did'nt see this at first…)

On the screenshot I tested with myself to leave my coworkers alone, but it's reproducible with any DM

- before I send the message:
![image](https://user-images.githubusercontent.com/36405135/203256635-af303925-03e6-4bfa-b56d-48cf213806c7.png)

- after I press enter, the message is in the upper part, but not in the thread:
![image](https://user-images.githubusercontent.com/36405135/203256757-416b64a4-bb81-43f7-88a5-e3b9b8f64a7c.png)

**Comment by jtdaugherty** [comment]
Out of curiosity, how did you manage to open a DM window with yourself? We did a few things with the intention of making that impossible. :)

**Comment by jtdaugherty** [comment]
Also, thanks - I've been able to reproduce this and I'll investigate.

**Comment by jtdaugherty** [comment]
This is now fixed in e58ad1f214ff3fad0381c448f075fd1a23ec9f3d and will go out in the next release. Thanks for reporting this!

**Comment by chrnin** [comment]
> Out of curiosity, how did you manage to open a DM window with yourself? We did a few things with the intention of making that impossible. :)

Hmm, I just typed `/msg @christophe.ninucci` and it popped, by the way this DM was already created with the mattermost GUI before I opened it there, maybe that helps.

And, imho, it's a rather nice feature to talk to myself, because I'm a free psychologist (but rather incompetent) and it's a private and convenient space where I can copy/paste things for my future «self with unknown device». Also it allows me to make some tests without bothering peoples in my organization ;)

**Comment by jtdaugherty** [comment]
Okay, thanks!
