### ISSUE TITLE
please support download of attachments without opening

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#795]
Hello! :)

I would like a way to download an attachment without any attempts to open or handle the attachment.

I would be perfectly content with saving the attachment with the given name into a standard location (much like Firefox downloading into `~/Downloads/`) but could see benefits to prompting for a place to store the file, a filename to use, etc.

My motivation: Currently, matterhorn offers commands to open an attachment:

```
├─[Y:yank-all f:flag t:thread l:copy-link p:pin r:reply v:view o:open 1 URL a:react]─
```

`open` uses `xdg-open` on my environment to open the attachment. (Worse yet, `xdg-open` within a snap. I have no idea how to configure that, if it is even configurable.)

`open` leads to a dialog box:

```
Allow snap "matterhorn" to open file "/home/sarnold/snap/matterhorn/369/.cache/matterhorn/files/m6bwfhntfiy7xns9hz8f3gco9e/REDACTED - pocs.zip"?
```

If I allow it, I don't know what the results will be: a gui window? unzipping the file in whatever the current working directory is? LibreOffice? (It's shocking how many file types get LibreOffice that really don't work well there.)

If I deny it, I get an error message like this:

```
An error occurred when running "xdg-open"; see "/tmp/matterhorn-subprocess2164915-0.log" for details.
```

(Of course, given snap, I'm not sure where that would live. I can't find it via: `find /snap ~/snap -name matterhorn-subprocess2164915-0.log` Anyway I suspect the details of this log aren't actually useful here.)

The other day, a coworker had attached a shell script to a message. What would happen if I allowed `xdg-open` to open this shell script? I don't know.

I'd rather just get the zip file or the shell script downloaded somewhere, told where it is, and then I could copy-and-paste that path to `unzip -l` or `scp` or `less` or whatever other tool I wanted to use next.

Thanks

**Comment by jtdaugherty** [comment]
Have you tried `C-o` (view URL and attachment list) and then `s` (save) on an attachment? That should prompt for a path and filename.

**Comment by setharnold** [comment]
Hey Jonathan, that works perfectly. I don't know why I never thought of using this interface.

I think a `Download` on the per-message interface might still be nice but the feature I wanted exists, so my feelings won't be hurt if you decide to close the issue. :)

Thanks again, it's always a pleasure.

**Comment by jtdaugherty** [comment]
Yeah, it's a little buried. At this point it's a challenge to add more keybindings to the per-message selection options because we're already running tight on horizontal space to show all the available shortcuts!

In the future, you might consider searching this page for things that might match what you want, which would then hopefully make it easier to tell which part of the UI will provide the shortcut:

https://github.com/matterhorn-chat/matterhorn/blob/master/docs/keybindings.md

**Comment by setharnold** [comment]
Oh that's helpful advice, I hadn't seen `focus-next-unread-user-or-channel` yet. I'll probably prefer this setting. :) Thanks!
