### ISSUE TITLE
Strikethrough text

### ISSUE THREAD

**Issue by nlhomme** [matterhorn-chat/matterhorn#796]
Hello,

I use matterhorn with iTerm2 on macOS 13.3.

Strikethrough text is displayed as regular text, which can be confusing.
I can't find anything related to strikethrough text in the user guide or in the sample-config.ini.

Am I missing something? Can you help me?

**Comment by jtdaugherty** [comment]
@nlhomme Have you had a chance to take a look at the link I posted above?

**Comment by nlhomme** [comment]
Hi @jtdaugherty, I don't have the time for the moment, I note that in my to-do list and keep you informed

**Comment by nlhomme** [comment]
Hi, I tried the link you posted but my TERM uses `xterm-256color`, and I don't know how to proceed.
I also don't know how to change the TERM to `xterm-256color`, onlines info are not clear.
Regards

**Comment by jtdaugherty** [comment]
Are you saying you don't know how to apply the steps in the link I mentioned? Or that you don't know how to change `TERM`? Or both?
