### ISSUE TITLE
larger channel /join list?

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#797]
Hello, can the `/join ~channelname` list of channels be made much larger?

I'm trying `/join ~sales` and see that there's thirty matches but only five are visible at once. (And, with the color-scheme I've got, the selected entry is actually very difficult to read -- making it more like four to read at once.)

I would love to see them all simultaneously.

Thanks

**Comment by jtdaugherty** [comment]
When you say "the list", are you referring to the window opened by `/join` (i.e. `/join` with no arguments)?

**Comment by setharnold** [comment]
Heh, I didn't know this existed. I meant typing:

```
/join ~sales
```

and then waiting a bit for this pane:

```
...─────Channels: 30 matches (Tab/Shift-Tab to select)──────...
```

Thanks

**Comment by jtdaugherty** [comment]
Ah, I see. While it's possible to make the autocomplete UI larger, I'd rather not show all of the alternatives at once, and in general there isn't a good way to know when to show just some vs. all. (And, at the end of the day, the amount of space we could use depends on your terminal window, in which case there will always be some cases where you can't see them all.) My recommendation is to use `/join` instead so you can type in a search term and scroll through the options. That window *does* show more choices, although its size is limited to show about 11 choices before you need to scroll. I hope that helps!
