### ISSUE TITLE
Stop automatically hiding of direct messages

### ISSUE THREAD

**Issue by nteodosio** [matterhorn-chat/matterhorn#798]
After some time of inactivity (a week?), interlocutors in the direct messages section will disappear, requiring a new /focus or /user command to start a conversation with them.

It would be nice to have the option to disable that.

**Comment by nteodosio** [comment]
Ugh, sorry, I missed that. Thanks for the quick response!

**Comment by jtdaugherty** [comment]
I'm happy to help. Let me know if that setting doesn't give you what you want.
