### ISSUE TITLE
handling of deleted users

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#80]
We probably want to do something about deleted users (should be able to tell by checking `delete_at` field). People might want to reference old chat messages (including dms) from deleted users, but at the same time we might want to tip off the user to them being deleted (different visual indicator, off screen by default, or something else).

**Comment by jtdaugherty** [comment]
This has been supported in `develop` since d73cee2ccfe0e357056d9cca977913fe7c4e78cf. We don't show deleted users, which is consistent with the web client.
