### ISSUE TITLE
Emoji reactions "linger" after removal

### ISSUE THREAD

**Issue by RyanGlScott** [matterhorn-chat/matterhorn#802]
To reproduce the issue, do the following on the `develop` branch:

1. Add a reaction (e.g., `:+1`) to a comment.
2. Afterwards, remove the comment's reaction.
3. View the comment using `Ctrl+s` followed by `v` and `Tab` to go to the Reactions pane.

Despite the fact that the reaction has been removed, it still appears in the Reactions pane, but with a count of 0:

![matterhorn](https://user-images.githubusercontent.com/2364661/233672079-0b990d43-5c4b-4270-86b0-a33ed5e5b114.png)

If you quit Matterhorn, restart it, and then go back to the Reactions pane for that comment, the `:+1` will have disappeared as expected.

**Comment by jtdaugherty** [comment]
Thanks for reporting this!

**Comment by jtdaugherty** [comment]
This is now fixed on `develop`.
