### ISSUE TITLE
snap matterhorn does not create config.ini file

### ISSUE THREAD

**Issue by kaddkaka** [matterhorn-chat/matterhorn#807]
Whenever I start matterhorn I can't access/create a config.ini and so my access token is never stored.

Installed with `sudo snap install matterhorn`,version:
```console
$ matterhorn --version
/snap/matterhorn/392/bin/matterhorn: line 7: /home/david/.config/matterhorn/config.ini: Permission denied
A default configuration file has been created at
  /home/david/.config/matterhorn/config.ini

Use with your $EDITOR to customize it

Call this command to setup an access token:
  snap run --shell matterhorn -c \
    'secret-tool store --label="$SNAP_NAME" $SNAP_NAME <token>'

Press any key to run matterhorn...
```
 
OS: `Ubuntu 22.04`

**Comment by kaddkaka** [comment]
If I touch the ini file and try to start mattermost I get:

```console
$ touch ~/.config/matterhorn/config.ini
$ matterhorn
Error loading config: Could not read "/home/david/.config/matterhorn/config.ini": permission denied
```

**Comment by jtdaugherty** [comment]
Hi @kaddkaka - sorry to hear you're having trouble. Since the Snap package is maintained by others, please report this at https://github.com/3v1n0/matterhorn-snap/

**Comment by kaddkaka** [comment]
Oh, that repo is a fork that doesn't allow issues and the original one is archived as read-only. I guess snap is just unsupported, thanks!

**Comment by jtdaugherty** [comment]
Oh, interesting. I don't know whether the original snap maintainers have moved on from it, but yes, your'e right - they're provided by a third party. So unfortunately I can't help much with them!
