### ISSUE TITLE
Support next/back in Ctrl-G channel select mode

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#81]
We should add `C-p` and `C-n` keybindings to navigate the list of matches when using `C-g`. We'll need a visual indicator of which match is the "selected" one. The easiest thing is probably to sort the list according to the zipper order so that the focused item is at the top.

**Comment by jtdaugherty** [comment]
I made a comment about this offline but the description above makes me think that if we had a cursor like `[...]` on a list like
```
[foo]
food
```
and then hit `C-n` we'd get
```
[food]
foo
```
Do I have that right?

**Comment by dagit** [comment]
Yeah, that's what I had in mind, but I'm open to other designs.

**Comment by jtdaugherty** [comment]
To me that would be confusing because it would cause the text to move around. I'd rather just have the typical rendering from
```
[foo]
food
```
to
```
foo
[food]
```

**Comment by jtdaugherty** [comment]
This is now supported in `develop`.
