### ISSUE TITLE
repeated first line of a thread is distracting

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#812]
Hello, I find the constant repetition of the first line of threads very distracting when there are two or more conversations going on -- or people joining or leaving the channel, etc.

I'd like to be able to configure those away -- the Thread Window will do a fine job of showing me the context of a conversation if I need it. (Perhaps a small one-character marker on a message to show that it is part of a thread would be a nice hint that the thread window will be useful.)

Thanks

**Comment by jtdaugherty** [comment]
If those were to be disabled, I'm not sure what a good UI indication would be. Right now, the `|` character indicates that a message is in a thread, but that only makes visual sense with the thread's root message displayed right above it. And if the root messages were hidden, then I don't know how to display two consecutive messages that are in *different* threads in a way that makes that obvious. If you have ideas, let me know. I'm going to close this in the mean time.
