### ISSUE TITLE
Invalid RootId parameter and Unable to get the channel member errors

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#813]
Hello, yesterday I received some error messages that I don't understand and our mattermost server admins couldn't track down to problems on the server-side:

I got `Unable to get the channel member` twice: once immediately after trying to send a private message to a coworker, and once in a public channel (perhaps without interaction).

I got `Invalid RootId parameter.` twice when trying to reply to a thread in a private channel; I believe these happened when sending the reply, not on the C-r.

A few seconds later I was able to send the private message and respond to the thread in the private channel without trouble.

These four errors happened in a span of fifteen minutes; I hadn't seen them in the years before nor in the hours since then.

Thanks

**Comment by jtdaugherty** [comment]
Hi @setharnold - that's interesting. Those messages are originating from the server. I'm not sure what would cause those, but by your other comments it sounds almost like your server suffered some temporary issue. On the assumption that that's what happened, I'm going to close this but if it happens again -- particularly if it lasts a while -- maybe enable logging and re-open this and provide your log file.

**Comment by setharnold** [comment]
Sounds good; I also suspect the server more than the client for reasons I can't articulate, but I figured I should be thorough. Thanks!
