### ISSUE TITLE
load large amounts of scrollback at once?

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#814]
Hello, since the mattermost search functionality is not helping me find a conversation I need, I would like to just read all the conversation between eg September first and today. This involves hitting `enter` on the message `Load older messages  ↥↥↥` several hundred times.

I wish there was a way to say "load the previous ten thousand lines" or "load the previous week" or "load the previous month" etc.

Thanks

**Comment by jtdaugherty** [comment]
Out of curiosity, do you know how you'd solve this problem in the official web client? Other than being able to search for a message by search term, I don't know how it would handle a situation like this.

**Comment by setharnold** [comment]
I'm sorry I missed your comment @jtdaugherty -- unfortunately I don't know how I would approach this in the web client. Matterhorn handles this case significantly better than the web interface already.

I'm just hoping that instead of loading ten or twenty messages at a time, it'd be easier to load thousands at a time.

Thanks

**Comment by setharnold** [comment]
Hello, I'm back after a four-day weekend to ask if it'd be possible to add a hot-key to the `Load Older Messages ↥↥↥` interface that could either load eg 200 messages at once, or load all unread messages, or something similar. Hitting `Enter` forty or fifty times just isn't fun.

Thanks

**Comment by jtdaugherty** [comment]
@setharnold thanks, that sounds frustrating. I just pushed eea25784ba519b8139a61d8d4a1158c3a7a69f73 to `develop` to significantly increase the number of messages fetched when `Load Older Messages` is selected.

**Comment by setharnold** [comment]
@jtdaugherty thanks!

**Comment by setharnold** [comment]
Thanks for the `90000.0.1` release, this is so much nicer!
