### ISSUE TITLE
Move away from connection

### ISSUE THREAD

**Issue by sternenseemann** [matterhorn-chat/matterhorn#818]
[connection is unmaintained now](https://github.com/vincenthz/hs-connection) and can't be built with `tls >= 1.7` which is going to make building matterhorn tricky going forward.

**Comment by jtdaugherty** [comment]
Thanks for reporting this!

**Comment by jtdaugherty** [comment]
Do you happen to know of any recommended alternative?

**Comment by jtdaugherty** [comment]
It turns out that `crypton-connection` is a drop-in replacement. This is now fixed. Thank you!

**Comment by sternenseemann** [comment]
mattermost-api needs this as well, of course, otherwise the switch is kind of pointless.

**Comment by jtdaugherty** [comment]
Yes, indeed; I made that change in https://github.com/matterhorn-chat/mattermost-api/commit/8df809df4d96930cf8b39d0d8f54cdb6d8f42b59.

**Comment by sternenseemann** [comment]
Thanks!
