### ISSUE TITLE
Keybind A-Up and A-Down does not work

### ISSUE THREAD

**Issue by phellarv** [matterhorn-chat/matterhorn#819]
When I try to add:
[keybindings]
focus-next-channel = A-Up
focus-prev-channel = A-Down

in the config.ini, it does not work. It removes the current binding, but it does not add the binding which I try to add.

**Comment by jtdaugherty** [comment]
Hi @phellarv. Different terminals send different sequences for certain key and modifier combinations and Matterhorn's terminal input processing might not recognize those sequences. What do you get when you perform these steps?
* Run `cat >/dev/null`
* Press `A-Down`
For example, when I do it, I get this:
```
$ cat >/dev/null
^[^[[B
```
Let me know what you get and then I'll see what we can do from there.

**Comment by phellarv** [comment]
Hi,

Thanks. Here is my results from /dev/null
```
$ cat >/dev/null
^[[1;3B
```

I hope that gives you something to work from.

**Comment by jtdaugherty** [comment]
Okay. Given that, I think the steps described in [this FAQ entry](https://github.com/matterhorn-chat/matterhorn/blob/master/docs/FAQ.md#why-doesnt-matterhorn-support-my-desired-keybindings) ought to be helpful. Can you take a look?

**Comment by phellarv** [comment]
Hi,
I did the steps outlined in the FAQ, and ended up with a `~/.vty/config` with a content like this:
```
map _ "\ESC[1;3B" KDown [MAlt]
map _ "\ESC[1;3A" KUp [MAlt]

```
But no cigar. Alt-Up and Alt-Down does not work.

I tried to see if there was a possibility that I could get some debug from matterhorn, and ran `VTY_DEBUG_LOG=/tmp/matterhorn-keys-debug matterhorn`. But that did not produce any logs.

Please advice on how to dig further, or tell me where I went wrong.

**Comment by phellarv** [comment]
By the way - I tried MMeta instead of MAlt, but still nothing.

**Comment by phellarv** [comment]
Hi,

I think I brainfarted. But anyways. This combo works now:
~/.vty/config
```
map _ "\ESC[1;3B" KDown [MMeta]
map _ "\ESC[1;3A" KUp [MMeta]
```
~/.config/matterhorn/config.ini
[keybindings]
```
focus-next-channel = M-Down
focus-prev-channel = M-Up
```

Thanks for pointing me in the right direction.

Regards
Per-Arne

**Comment by jtdaugherty** [comment]
I'm glad to hear that you've gotten it working!
