### ISSUE TITLE
C-n/p are unexpected in DM channel mode

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#82]
Right now when I'm in a DM channel, it's surprising that C-n/p take me entirely out it.  It'd be nice if C-n/p only did something when I'm in one of the channels that I can reach with C-n/p.

**Comment by dagit** [comment]
@jtdaugherty With all the new movement bindings, do you still feel this is a bug? @aisamanra and I talked it over and we like the current behavior.

**Comment by jtdaugherty** [comment]
Yeah, this is still a bug - I'm happy to discuss in person.

**Comment by dagit** [comment]
We chatted in person. We brainstormed several different options.

## Option 1
Keep the current order and next/previous goes to channels and also the last user(s) you talked to.

## Option 2
If revert to the old behavior where C-n/p works for normal and dm channels, but making that change will need us to address the following things:

  * Currently display order of user list is different than zipper traversal order
  * We'd create a dm channel with each user you visit. This is probably undesirable. It would probably be better to delay the channel creation until there is a message sent.

## Option 3
Have a friend/favorite list and not show other users. Then C-n/p would work for both channels and favorites. Non-favorited users would have to be added via a menu before they could be selected via C-n/p.

**Comment by dagit** [comment]
This is important, but the client seems minimally useful without these changes. So I'm moving this issue to a different milestone.
