### ISSUE TITLE
I think you skipped a few (tens of thousands of ) versions

### ISSUE THREAD

**Issue by alerque** [matterhorn-chat/matterhorn#820]
As someone who packages this for distros downstream, I'd like to point out that you skipped 39799 major versions between [50200.19.0](https://github.com/matterhorn-chat/matterhorn/releases/tag/50200.19.0) and [90000.0.0](https://github.com/matterhorn-chat/matterhorn/releases/tag/90000.0.0).

What the flaming coconut twizzler versioning scheme is this?

**Comment by jtdaugherty** [comment]
You can read all about how our versioning numbers work [in the README](https://github.com/matterhorn-chat/matterhorn?tab=readme-ov-file#our-versioning-scheme). The bump to `90000` is due to compatibility with server version `9.0` in the latest release.
