### ISSUE TITLE
[Q] Binary release 90000.0.0 for Fedora

### ISSUE THREAD

**Issue by SchweinDeBurg** [matterhorn-chat/matterhorn#822]
Many thanx for your excellent work! Will binary release 90000.0.0 be available for Fedora?

**Comment by jtdaugherty** [comment]
I had a build problem with that particular platform, but I just got it resolved! I just uploaded the build here:

https://github.com/matterhorn-chat/matterhorn/releases/edit/90000.0.0

**Comment by SchweinDeBurg** [comment]
@jtdaugherty So many, many thanx!
