### ISSUE TITLE
Explore supporting polls

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#828]
Hello, Mattermost has a 'poll' feature that can be used to collect structured answers from channel members. These don't render very well in Matterhorn, they're not very useful:

```
[18:12:08] matterpoll:
             > **************************************************************************************************************************************
             > Total votes: 34
             (edited)
```

It doesn't come up very often but it would be nice if it worked.

Thanks

**Comment by jtdaugherty** [comment]
Yeah, I agree. I've seen that on my server, too. I haven't looked into it deeply, but I am not sure whether it's possible to support polls in environments that don't assume mouse interaction. It would depend on the kind of structured data coming from the server about the poll.

I can't make supporting this a priority, but if someone wanted to investigate it and report their findings here, that would be super helpful.

**Comment by jtdaugherty** [comment]
Since I can't make this a priority, I don't want to keep it open - but I would be happy to work with anyone who wants to investigate what this would involve.
