### ISSUE TITLE
focus and return to your own username on start

### ISSUE THREAD

**Issue by crpb** [matterhorn-chat/matterhorn#831]
Hi,

i have the following problems:
1. it seems i can't do an `/focus $myusername` (w/o the '$' of course)
2. if i have myself in focus with other means and close the application and open it again i don't land in another channel than $myself
  - this works in the official mattermost app

**Comment by jtdaugherty** [comment]
> this works in the official mattermost app

By "this", what behavior are you referring to, exactly? (The official client doesn't have a `/focus` command, but it does have `/msg`. But `/msg @<my account>` didn't work for me in the web client for the server I'm using.)

**Comment by crpb** [comment]
Hi,
i can do ctrl-k which i think is the analogue thing to /focus?
![image](https://github.com/matterhorn-chat/matterhorn/assets/5575140/0b609791-cd08-4909-87e2-d185702351b2)

**Comment by jtdaugherty** [comment]
Thanks, I didn't know about shortcut!

**Comment by jtdaugherty** [comment]
This is now mostly resolved by bc9694e70489918a40c8763dc3f7d4c2d47509e0. That change makes it possible to use `/focus` to switch to your own DM channel. For now, I'm not going to change the startup behavior because Matterhorn already doesn't put you in a DM channel at startup.

**Comment by crpb** [comment]
Thank you. Now i just have to get it to build :P.
