### ISSUE TITLE
matterhorn: Lens.Micro.singular: empty traversal

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#832]
Hello, matterhorn crashed moments after I used `/leave` to leave a channel. It made some progress on rendering the next channel and then crashed with the following message:

```
$ ~/Downloads/matterhorn-90000.0.0-ubuntu-20.04-focal-x86_64/matterhorn 
matterhorn: Lens.Micro.singular: empty traversal
CallStack (from HasCallStack):
  error, called at src/Lens/Micro.hs:1057:20 in microlens-0.4.13.1-e63b1bd2616d097c066e6e391ca3d5330945601ee02559d72cf1dedf7ed08a0f:Lens.Micro
  singular, called at src/Matterhorn/Types.hs:1839:38 in matterhorn-90000.0.0-inplace:Matterhorn.Types
```

Upon relaunching matterhorn, going back to the channel that I think was loaded next, nothing unusual happened.

Thanks

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Thanks again!
