### ISSUE TITLE
Non-unique names make it hard to tell who sent a specific message

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#833]
Hello again,

My company is moderately large: we have many people who have partial name collisions.

Sometimes I'll want to reply in a thread to the person who asked the question but it's hard to tell which username to use to highlight the right person because there's just so many possible choices. (One recent example, `@Gabriel` brings up a menu that says there's ten matches and displays five of them. The asterisks help if the person hasn't left or joined the channel in the meantime.)

I'd like to suggest that the `View Message` window could be extended to show:
- the username
- the chosen "friendly" name
- the full name

This would give me an easier way to tell who sent a given message.

Thanks

**Comment by jtdaugherty** [comment]
This is now implemented on `develop`. Here's an example of what it looks like for one of my messages. Thanks!
<img width="1082" alt="Screenshot 2024-08-29 at 9 54 56 AM" src="https://github.com/user-attachments/assets/790fccb1-fdb5-49c7-b873-2805ff25d8f2">
