### ISSUE TITLE
NotifyV2 example: Use more robust `printf(1)` idiom

### ISSUE THREAD

**Issue by pstumpf** [matterhorn-chat/matterhorn#836]
The input to this script is sanitised (to a degree), but it is still safer to use the `printf` idiom below.  Depending on some circumstances, the JSON might be evaluated as shell patterns.  Ideally, something like this would not be written in Shell, but Perl or Python ...

```
diff --git a/notification-scripts/notifyV2 b/notification-scripts/notifyV2
index 9f406b99..37126d85 100755
--- a/notification-scripts/notifyV2
+++ b/notification-scripts/notifyV2
@@ -27,11 +27,11 @@ has notify-send || fail 'notify-send(1) is required but not present'
 
 # Extract the data to be notified. The data is in a JSON payload at stdin.
 json=`cat`
-version=`echo $json|jq -Mr .version`
+version=`printf "%s\n" "$json" | jq -Mr .version`
 [ "$version" = 2 ] || fail 'JSON payload has wrong version'
-sender=`echo $json|jq -Mr .from`
-message=`echo $json|jq -Mr .message`
-mentioned=`echo $json|jq -Mr .mention`
+sender=`printf "%s\n" "$json" | jq -Mr .from`
+message=`printf "%s\n" "$json" | jq -Mr .message`
+mentioned=`printf "%s\n" "$json" | jq -Mr .mention`
 
 # Now prepare the notification. The logic is essentially the same as for
 # the V1 notifier.
```

**Comment by jtdaugherty** [comment]
Thanks! Would you be willing to submit this as a PR?

**Comment by jtdaugherty** [comment]
(Based on `develop`.)

**Comment by fictitiousexistence** [comment]
@pstumpf I often get notifications that have a "*" in them and the notification ends up showing an ls of my home directory. That's what this patch will help with? Thanks :D

**Comment by jtdaugherty** [comment]
@fictitiousexistence I believe that'll be addressed just by switching to a version 2 notification script, since the wildcard character is not passed on the command line in that case.

**Comment by fictitiousexistence** [comment]
@jtdaugherty the notifyV2 script is the only one I've ever used. I never got around to troubleshooting it but I'll keep an eye out and give some details if I see it again.

**Comment by jtdaugherty** [comment]
Interesting. The v2 scripts do not receive command-line arguments at all, so I don't know how you would get the wildcard behavior you described above. To confirm, is `activityNotifyVersion` set to `2` in your Matterhorn configuration?

**Comment by fictitiousexistence** [comment]
Yep, activityNotifyVersion is set to 2. 
Looks like I have logging enabled so I can see some of the messages. The logs also report the version is 2. 

An example message:

🔥 host.example.com at host.example.com/Perc Drive Health is CRITICAL
** Global Storage Alarm WARNING ** PERC Channel is OK: PERC Battery is 36: All Disks are OK:

The way it shows in the notification log is like this:

🔥 host.example.com at host.example.com/Perc Drive Health is CRITICAL
** Global Storage Alarm WARNING Desktop Documents Downloads Pictures file1 file2 file3 PERC Channel is OK: PERC Battery is 36: All Disks are OK:

The second pair of ** get replaced with the home directory listing

**Comment by fictitiousexistence** [comment]
@jtdaugherty 

I did some testing. In notifyV2 the $json variable is not quoted so echo is expanding the *'s.

In mattermost you can bold something by putting 2 ** before and after what you want bolded. You can include a space or not. 
Ex:
**Testing**  or ** Testing ** will both bold.

The directories are not listed if I use the no space method. 
`echo **Testing**` prints out "**Testing**" but 
`echo ** Testing **` prints out the directory listing and Testing.


So this works:
```
version=`echo "$json"|jq -Mr .version`
[ "$version" = 2 ] || fail 'JSON payload has wrong version'
sender=`echo "$json"|jq -Mr .from`
message=`echo "$json"|jq -Mr .message`
mentioned=`echo "$json"|jq -Mr .mention`
```

@pstumpf 's patch has the $json variable quoted and it works for me.

**Comment by jtdaugherty** [comment]
@fictitiousexistence I see, thank you! I'll be sure to include the fix in the next release.

**Comment by jtdaugherty** [comment]
This is now fixed on `develop`.
