### ISSUE TITLE
Limited support in parameter `passcmd`

### ISSUE THREAD

**Issue by Spreadcat** [matterhorn-chat/matterhorn#838]
## Description

When I add a command into the parameter `passcmd` in the config file that uses the pipe symbol, matterhorn fails and cannot run the command. The same happens when using a command containing parameters or redirects as well.

## What's happening

```shell
$ pass show secret | head -n 1
foobar
```

```ini
# ~/.config/matterhorn/config.ini
...
passcmd: pass show secret | head -n 1
...
```

```shell
$ matterhorn --check-config
Could not execute password command: does not exist
```

If I replace the command in `passcmd` with the following string, it works:

```ini
# ~/.config/matterhorn/config.ini
...
passcmd: pass show secret \| head \-n 1
...
```

## What's expected

The parameter should support using the same syntax as can be used on the shell.

## Versions

```bash
$ matterhorn -v
matterhorn 90000.0.1 (master@2eede8b)
 using mattermost-api 90000.0.0 (HEAD@b082f9d)
```

* Fedora 40

**Comment by jtdaugherty** [comment]
Thanks for the report!

What you discovered is what we intended, which is that Matterhorn's configuration file command options support single commands but do not support arbitrary shell commands. If you would like to do something that requires using the shell, that can be done by writing a shell script that does what you want and then calling your custom script in the configuration file.

**Comment by Spreadcat** [comment]
Thanks for the explanation.
I fail to follow your reasoning though, since (as mentioned in the example) I am still able to adding those arbitrary shell commands by escaping them. Was the purpose just to make it harder, but not impossible? If so: would you be so kind to roughly outline the thought process on that? It still leaves me curious..

**Comment by jtdaugherty** [comment]
> I am still able to adding those arbitrary shell commands by escaping them

That's actually surprising to me and not deliberate. It appears that although the library we're using to run the command does not say so in its API, it has this behavior. I'm not exactly sure what call they're making under the hood, but they distinguish between a shell command API (which we are not using for this) and a single-command API (which we are).
