### ISSUE TITLE
Figure out what to do with private channels

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#84]
As of fde3ad2, we support private channels but just toss them into the same channel listing with everything else, only giving them a different sigil. If we want to mirror the web client more closely, we can include an optional section that includes only private channels, if you're in any private channels, or we might want to display them some other way.

We can already use them, so this is more of a what's-the-best-presentation kind of issue.

**Comment by dagit** [comment]
In the spirit of bikeshedding, I think we should color them differently. Say, make them magenta. Now that we don't color channels, I think this would be an effective way to make them standout a little bit.

**Comment by aisamanra** [comment]
We use `?` as a sigil here and otherwise support private channels, so this is resolved.
