### ISSUE TITLE
Create new user channels asynchronously

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#86]
Right now when you `/focus` or `C-g` to get to a user channel that doesn't already exist, it is done synchronously.  As a result on slow connections you stay in your old channel for a while before it is evident that anything is happening.  I'd like to make it so that similar to async message loading, where we give a message saying that we're loading scrollback, we switch to the user channel immediately and give a message saying that that it is "loading" (even though it's being created).

**Comment by dagit** [comment]
Right now the operation to create and switch focus is asynchronous, but we
can't focus using the normal focus logic until we get back the channel ID
from the creation request.

So I think fixing this will require a bit of refactoring to support
focusing on a channel even if we don't know the channel ID.

**Comment by jtdaugherty** [comment]
Yeah, that's what I had in mind.

**Comment by dagit** [comment]
When pending posts are created we have to populate the post id. We copied what the webclient does (it's something like current time plus user id, I forget). We could do something like that here. Then we could send ourselves a notification once the real details become available. As long as we send the old and new id pair it shouldn't be too hard to purge the old id while adding the new one.

We'll need to be careful about trying to use that channel id in the interim, but I think your suggestion of a loading screen addresses that.

Anyway, those are the details for anyone who wants to work on it.

**Comment by aisamanra** [comment]
We do most operations asynchronously at this point, including channel-fetching like this one.
