### ISSUE TITLE
Use base-compat to avoid redundant imports

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#97]
For older GHCs we import some things that aren't needed for newer versions of `base`. Jason's recommendation is to use `base-compat` to avoid this practice when possible.

**Comment by dagit** [comment]
I'm happy to make this change but since I don't have 7.8 installed I don't want to do it until our travis-ci build is stable again.

**Comment by jtdaugherty** [comment]
@dagit now that our travis-ci build seems to be stable, are you still interested in making this change?

**Comment by dagit** [comment]
This totally slipped my mind. It's probably not a hard change, but I see that we never got 7.8 builds working. So that means it's probably not a huge priority either.

So yes, I'm interested in doing this.

**Comment by dagit** [comment]
The only module I didn't update was `src/Draw.hs`. It doesn't use anything defined in the Prelude, so I got a warning about unused imports when I added the change there. So I opted to just not make the change in that module. If we add more code to that module later, we should be mindful that we might need to add the `import Prelude.Compat` at that time.

**Comment by jtdaugherty** [comment]
Thanks!
