### ISSUE TITLE
(Far Future) Feature Suggestion: OTR for DM channels

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#99]
This is a feature that's very much in the category of _might possibly be nice to maybe have at some point in the future_, but it popped into my head, so I wanted to write it down somewhere so I didn't forget.

[OTR](https://en.wikipedia.org/wiki/Off-the-Record_Messaging) is an encryption protocol designed to be used on top of existing stock IM protocols that provides per-session security. MatterMost's transport is encrypted by virtue of being done over SSL (using HTTP and WebSockets) but AFAIK there's no effort made towards end-to-end encryption—indeed, it would be kind of anathema to the searching and archiving features that MatterMost provides for general group chat.

On the other hand, for individual DM _sessions_, it might make sense to provide an opt-in form of end-to-end encryption: this could be invoked by a command like `/otr` command in an individual DM channel, which would direct Matterhorn to try to negotiate an OTR session. If the other participant isn't using a client that supports OTR, then this would fail. Because OTR uses session keys to guarantee forward secrecy, the OTR'ed messages would not be readable later, and would appear in the scrollback as opaque blobs and be unsearchable by both the MatterMost server and by clients: this is actively the point of using an OTR-like system, which is why it's important that it also be capable of being disabled after a given secure conversation is finished. (We could set OTR blobs off in MatterHorn scrollback by styling them in a different way, but that's very much a feature suggestion for another day.)

**Comment by jtdaugherty** [comment]
This has been migrated to the wiki: https://github.com/matterhorn-chat/matterhorn/wiki/Feature-Backlog
